// Generated by nupac
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <ncurses.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
#ifndef NPSTRING_NH
#define NPSTRING_NH
#ifndef YES
#define YES 1
#endif
#ifndef NO
#define NO 0
#endif
#endif
#include <ctype.h>
#ifndef TERMINAL_NCURSES_NH
#define TERMINAL_NCURSES_NH
#endif
struct nupa_vtable;
struct nupa_NPObject_meta_vtable;
struct nupa_Terminal__Ncurses__Button_meta_vtable;
struct nupa_Terminal__Ncurses__Label_meta_vtable;
struct nupa_Terminal__Ncurses__MenuBar_meta_vtable;
struct nupa_Terminal__Ncurses__Screen_meta_vtable;
struct nupa_Terminal__Ncurses__TextBox_meta_vtable;
struct nupa_Terminal__Ncurses__Window_meta_vtable;
struct nupa_NPString_meta_vtable;

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nupa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nupa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nupa_sel_isKindOf_ = {.name = "isKindOf:", .hash = 0x6E8A60C4};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nupa_sel_stringWithUTF8String_ = {.name = "stringWithUTF8String:", .hash = 0x3E782AA8};
static const SEL __nupa_sel_stringWithString_ = {.name = "stringWithString:", .hash = 0x2CFB20D9};
static const SEL __nupa_sel_initWithUTF8String_ = {.name = "initWithUTF8String:", .hash = 0x05E6D56D};
static const SEL __nupa_sel_initWithString_ = {.name = "initWithString:", .hash = 0xB81658EC};
static const SEL __nupa_sel_length = {.name = "length", .hash = 0x83D03615};
static const SEL __nupa_sel_UTF8String = {.name = "UTF8String", .hash = 0xE0A62C4B};
static const SEL __nupa_sel_characterAtIndex_ = {.name = "characterAtIndex:", .hash = 0xC331E633};
static const SEL __nupa_sel_isEqualToString_ = {.name = "isEqualToString:", .hash = 0x9E7D4A8B};
static const SEL __nupa_sel_compare_ = {.name = "compare:", .hash = 0xD70D388A};
static const SEL __nupa_sel_hasPrefix_ = {.name = "hasPrefix:", .hash = 0x3CE00E17};
static const SEL __nupa_sel_hasSuffix_ = {.name = "hasSuffix:", .hash = 0x4B5261C4};
static const SEL __nupa_sel_rangeOfString_ = {.name = "rangeOfString:", .hash = 0x92871CC4};
static const SEL __nupa_sel_substringFromIndex_ = {.name = "substringFromIndex:", .hash = 0xBEB53D4A};
static const SEL __nupa_sel_substringToIndex_ = {.name = "substringToIndex:", .hash = 0x562D1E57};
static const SEL __nupa_sel_substringWithRange_ = {.name = "substringWithRange:", .hash = 0x11ADC8DD};
static const SEL __nupa_sel_stringByAppendingString_ = {.name = "stringByAppendingString:", .hash = 0x7B77D840};
static const SEL __nupa_sel_stringByAppendingUTF8String_ = {.name = "stringByAppendingUTF8String:", .hash = 0x2217CF89};
static const SEL __nupa_sel_uppercaseString = {.name = "uppercaseString", .hash = 0x49EBFBAE};
static const SEL __nupa_sel_lowercaseString = {.name = "lowercaseString", .hash = 0x7ADD0937};
static const SEL __nupa_sel_hash = {.name = "hash", .hash = 0xCEC577D1};
static const SEL __nupa_sel_description = {.name = "description", .hash = 0x346F3B69};
static const SEL __nupa_sel_copy = {.name = "copy", .hash = 0xE562EA44};
static const SEL __nupa_sel_screen = {.name = "screen", .hash = 0x55C54C11};
static const SEL __nupa_sel_update = {.name = "update", .hash = 0x280F9474};
static const SEL __nupa_sel_clearScr = {.name = "clearScr", .hash = 0xB9B5C6F6};
static const SEL __nupa_sel_readChar = {.name = "readChar", .hash = 0x58E7483D};
static const SEL __nupa_sel_rows = {.name = "rows", .hash = 0x2A37B398};
static const SEL __nupa_sel_cols = {.name = "cols", .hash = 0xD744BF26};
static const SEL __nupa_sel_mouseEvent = {.name = "mouseEvent", .hash = 0xDFC6059C};
static const SEL __nupa_sel_mouseX = {.name = "mouseX", .hash = 0xEE3FBD94};
static const SEL __nupa_sel_mouseY = {.name = "mouseY", .hash = 0xEF3FBF27};
static const SEL __nupa_sel_initWithRect_y_w_h_ = {.name = "initWithRect:y:w:h:", .hash = 0x926C9415};
static const SEL __nupa_sel_drawBox = {.name = "drawBox", .hash = 0x6AA028B4};
static const SEL __nupa_sel_moveTo_x_ = {.name = "moveTo:x:", .hash = 0x66457087};
static const SEL __nupa_sel_print_x_text_ = {.name = "print:x:text:", .hash = 0x0C0F3C27};
static const SEL __nupa_sel_handle = {.name = "handle", .hash = 0x2E7FCBD3};
static const SEL __nupa_sel_initWithWindow_x_y_text_ = {.name = "initWithWindow:x:y:text:", .hash = 0x8DEA0E15};
static const SEL __nupa_sel_draw = {.name = "draw", .hash = 0xA88BF413};
static const SEL __nupa_sel_setText_ = {.name = "setText:", .hash = 0x4C43F6DA};
static const SEL __nupa_sel_initWithWindow_x_y_w_text_ = {.name = "initWithWindow:x:y:w:text:", .hash = 0x8F26BAEA};
static const SEL __nupa_sel_setHighlight_ = {.name = "setHighlight:", .hash = 0x5394E869};
static const SEL __nupa_sel_initWithWindow_x_y_w_ = {.name = "initWithWindow:x:y:w:", .hash = 0x641CDB53};
static const SEL __nupa_sel_edit = {.name = "edit", .hash = 0x5BE7D591};
static const SEL __nupa_sel_text = {.name = "text", .hash = 0xBDE64E3E};
static const SEL __nupa_sel_initWithWindow_w_ = {.name = "initWithWindow:w:", .hash = 0x3886AAFA};
static const SEL __nupa_sel_addItem_ = {.name = "addItem:", .hash = 0xCF2F47E3};
static const SEL __nupa_sel_selected = {.name = "selected", .hash = 0x4E0A1774};

#ifndef __NUPA_ROOT_DEFINED
#define __NUPA_ROOT_DEFINED
struct __nupa_root {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct __nupa_root __nupa_root;
#endif
#ifndef NPOBJECT_DEFINED
#define NPOBJECT_DEFINED
struct NPObject {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPObject NPObject;
#endif
struct Terminal__Ncurses__Button;
typedef struct Terminal__Ncurses__Button Terminal__Ncurses__Button;
struct Terminal__Ncurses__Label;
typedef struct Terminal__Ncurses__Label Terminal__Ncurses__Label;
struct Terminal__Ncurses__MenuBar;
typedef struct Terminal__Ncurses__MenuBar Terminal__Ncurses__MenuBar;
struct Terminal__Ncurses__Screen;
typedef struct Terminal__Ncurses__Screen Terminal__Ncurses__Screen;
struct Terminal__Ncurses__TextBox;
typedef struct Terminal__Ncurses__TextBox Terminal__Ncurses__TextBox;
struct Terminal__Ncurses__Window;
typedef struct Terminal__Ncurses__Window Terminal__Ncurses__Window;
struct NPString;
typedef struct NPString NPString;

typedef struct NPRange {
    int location;
    int length;
} NPRange;

NPObject * __nupa_root_init(NPObject * self, SEL _cmd);
void __nupa_root_dealloc(NPObject * self, SEL _cmd);
void __nupa_root_release(NPObject * self, SEL _cmd);
NPObject * __nupa_root_retain(NPObject * self, SEL _cmd);
_Bool __nupa_root_isKindOf_(NPObject * self, SEL _cmd, NPClass * cls);
NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
NPString * NPString_stringWithUTF8String_(NPClass * self, SEL _cmd, const char * cstr);
NPString * NPString_stringWithString_(NPClass * self, SEL _cmd, NPString * str);
NPString * NPString_initWithUTF8String_(NPObject * self, SEL _cmd, const char * cstr);
NPString * NPString_initWithString_(NPObject * self, SEL _cmd, NPString * str);
size_t NPString_length(NPObject * self, SEL _cmd);
const char * NPString_UTF8String(NPObject * self, SEL _cmd);
char NPString_characterAtIndex_(NPObject * self, SEL _cmd, size_t index);
int NPString_isEqualToString_(NPObject * self, SEL _cmd, NPString * other);
int NPString_compare_(NPObject * self, SEL _cmd, NPString * other);
int NPString_hasPrefix_(NPObject * self, SEL _cmd, NPString * prefix);
int NPString_hasSuffix_(NPObject * self, SEL _cmd, NPString * suffix);
NPRange NPString_rangeOfString_(NPObject * self, SEL _cmd, NPString * substring);
NPString * NPString_substringFromIndex_(NPObject * self, SEL _cmd, size_t from);
NPString * NPString_substringToIndex_(NPObject * self, SEL _cmd, size_t to);
NPString * NPString_substringWithRange_(NPObject * self, SEL _cmd, NPRange range);
NPString * NPString_stringByAppendingString_(NPObject * self, SEL _cmd, NPString * other);
NPString * NPString_stringByAppendingUTF8String_(NPObject * self, SEL _cmd, const char * cstr);
NPString * NPString_uppercaseString(NPObject * self, SEL _cmd);
NPString * NPString_lowercaseString(NPObject * self, SEL _cmd);
uint32_t NPString_hash(NPObject * self, SEL _cmd);
NPString * NPString_description(NPObject * self, SEL _cmd);
NPString * NPString_copy(NPObject * self, SEL _cmd);
void NPString_dealloc(NPObject * self, SEL _cmd);
NPObject * Terminal__Ncurses__Screen_screen(NPClass * self, SEL _cmd);
void Terminal__Ncurses__Screen_dealloc(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Screen_update(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Screen_clearScr(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Screen_readChar(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Screen_rows(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Screen_cols(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Screen_mouseEvent(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Screen_mouseX(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Screen_mouseY(NPObject * self, SEL _cmd);
NPObject * Terminal__Ncurses__Window_initWithRect_y_w_h_(NPObject * self, SEL _cmd, int x, int y, int w, int h);
void Terminal__Ncurses__Window_dealloc(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Window_update(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Window_drawBox(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Window_moveTo_x_(NPObject * self, SEL _cmd, int y, int x);
void Terminal__Ncurses__Window_print_x_text_(NPObject * self, SEL _cmd, int y, int x, NPString * text);
int Terminal__Ncurses__Window_readChar(NPObject * self, SEL _cmd);
WINDOW * Terminal__Ncurses__Window_handle(NPObject * self, SEL _cmd);
NPObject * Terminal__Ncurses__Label_initWithWindow_x_y_text_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int x, int y, NPString * text);
void Terminal__Ncurses__Label_dealloc(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Label_draw(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Label_setText_(NPObject * self, SEL _cmd, NPString * text);
NPObject * Terminal__Ncurses__Button_initWithWindow_x_y_w_text_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int x, int y, int w, NPString * text);
void Terminal__Ncurses__Button_dealloc(NPObject * self, SEL _cmd);
int Terminal__Ncurses__Button_draw(NPObject * self, SEL _cmd);
void Terminal__Ncurses__Button_setHighlight_(NPObject * self, SEL _cmd, int hl);
NPObject * Terminal__Ncurses__TextBox_initWithWindow_x_y_w_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int x, int y, int w);
const char * Terminal__Ncurses__TextBox_edit(NPObject * self, SEL _cmd);
const char * Terminal__Ncurses__TextBox_text(NPObject * self, SEL _cmd);
NPObject * Terminal__Ncurses__MenuBar_initWithWindow_w_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int w);
void Terminal__Ncurses__MenuBar_addItem_(NPObject * self, SEL _cmd, const char * label);
int Terminal__Ncurses__MenuBar_draw(NPObject * self, SEL _cmd);
int Terminal__Ncurses__MenuBar_selected(NPObject * self, SEL _cmd);
NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * self);
void nupa_release(NPObject * obj);
NPObject * nupa_retain(NPObject * obj);
int nk_mouse_get_event(int * x, int * y, int * btn);
float nk_cpu_usage(void );
void nk_mem_info(unsigned long long * used, unsigned long long * total);
void nk_disk_info(unsigned long long * used, unsigned long long * total);
int main(void);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * Terminal__Ncurses__Button_getClass(NPClass * self, SEL _cmd);
NPClass * Terminal__Ncurses__Label_getClass(NPClass * self, SEL _cmd);
NPClass * Terminal__Ncurses__MenuBar_getClass(NPClass * self, SEL _cmd);
NPClass * Terminal__Ncurses__Screen_getClass(NPClass * self, SEL _cmd);
NPClass * Terminal__Ncurses__TextBox_getClass(NPClass * self, SEL _cmd);
NPClass * Terminal__Ncurses__Window_getClass(NPClass * self, SEL _cmd);
NPClass * NPString_getClass(NPClass * self, SEL _cmd);

struct nupa_vtable {
    const char * (*UTF8String)(NPObject *, SEL);
    void (*addItem_)(NPObject *, SEL, const char *);
    char (*characterAtIndex_)(NPObject *, SEL, size_t);
    void (*clearScr)(NPObject *, SEL);
    int (*cols)(NPObject *, SEL);
    int (*compare_)(NPObject *, SEL, NPString *);
    NPString * (*copy)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPString * (*description)(NPObject *, SEL);
    int (*draw)(NPObject *, SEL);
    void (*drawBox)(NPObject *, SEL);
    const char * (*edit)(NPObject *, SEL);
    WINDOW * (*handle)(NPObject *, SEL);
    int (*hasPrefix_)(NPObject *, SEL, NPString *);
    int (*hasSuffix_)(NPObject *, SEL, NPString *);
    uint32_t (*hash)(NPObject *, SEL);
    NPObject * (*init)(NPObject *, SEL);
    NPObject * (*initWithRect_y_w_h_)(NPObject *, SEL, int, int, int, int);
    NPString * (*initWithString_)(NPObject *, SEL, NPString *);
    NPString * (*initWithUTF8String_)(NPObject *, SEL, const char *);
    NPObject * (*initWithWindow_w_)(NPObject *, SEL, Terminal__Ncurses__Window *, int);
    NPObject * (*initWithWindow_x_y_text_)(NPObject *, SEL, Terminal__Ncurses__Window *, int, int, NPString *);
    NPObject * (*initWithWindow_x_y_w_)(NPObject *, SEL, Terminal__Ncurses__Window *, int, int, int);
    NPObject * (*initWithWindow_x_y_w_text_)(NPObject *, SEL, Terminal__Ncurses__Window *, int, int, int, NPString *);
    int (*isEqualToString_)(NPObject *, SEL, NPString *);
    _Bool (*isKindOf_)(NPObject *, SEL, NPClass *);
    size_t (*length)(NPObject *, SEL);
    NPString * (*lowercaseString)(NPObject *, SEL);
    int (*mouseEvent)(NPObject *, SEL);
    int (*mouseX)(NPObject *, SEL);
    int (*mouseY)(NPObject *, SEL);
    void (*moveTo_x_)(NPObject *, SEL, int, int);
    void (*print_x_text_)(NPObject *, SEL, int, int, NPString *);
    NPRange (*rangeOfString_)(NPObject *, SEL, NPString *);
    int (*readChar)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    int (*rows)(NPObject *, SEL);
    int (*selected)(NPObject *, SEL);
    void (*setHighlight_)(NPObject *, SEL, int);
    void (*setText_)(NPObject *, SEL, NPString *);
    NPString * (*stringByAppendingString_)(NPObject *, SEL, NPString *);
    NPString * (*stringByAppendingUTF8String_)(NPObject *, SEL, const char *);
    NPString * (*substringFromIndex_)(NPObject *, SEL, size_t);
    NPString * (*substringToIndex_)(NPObject *, SEL, size_t);
    NPString * (*substringWithRange_)(NPObject *, SEL, NPRange);
    const char * (*text)(NPObject *, SEL);
    void (*update)(NPObject *, SEL);
    NPString * (*uppercaseString)(NPObject *, SEL);
};

struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Terminal__Ncurses__Button_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Terminal__Ncurses__Label_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Terminal__Ncurses__MenuBar_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Terminal__Ncurses__Screen_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPObject * (*screen)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Terminal__Ncurses__TextBox_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Terminal__Ncurses__Window_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_NPString_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPString * (*stringWithUTF8String_)(NPClass *, SEL, const char *);
    NPString * (*stringWithString_)(NPClass *, SEL, NPString *);
    NPClass * (*class)(NPClass *, SEL);
};

struct Terminal__Ncurses__Button {
    struct NPClass *isa;
    uint32_t retain_count;
    WINDOW * _win;
    int _x;
    int _y;
    int _w;
    NPString * _text;
    int _highlighted;
};
typedef struct Terminal__Ncurses__Button Terminal__Ncurses__Button;

struct Terminal__Ncurses__Label {
    struct NPClass *isa;
    uint32_t retain_count;
    WINDOW * _win;
    int _x;
    int _y;
    NPString * _text;
};
typedef struct Terminal__Ncurses__Label Terminal__Ncurses__Label;

struct Terminal__Ncurses__MenuBar {
    struct NPClass *isa;
    uint32_t retain_count;
    WINDOW * _win;
    int _w;
    int _count;
    char _items[320];
    int _selected;
};
typedef struct Terminal__Ncurses__MenuBar Terminal__Ncurses__MenuBar;

struct Terminal__Ncurses__Screen {
    struct NPClass *isa;
    uint32_t retain_count;
    int _rows;
    int _cols;
    int _mouseX;
    int _mouseY;
    int _mouseBtn;
};
typedef struct Terminal__Ncurses__Screen Terminal__Ncurses__Screen;

struct Terminal__Ncurses__TextBox {
    struct NPClass *isa;
    uint32_t retain_count;
    WINDOW * _win;
    int _x;
    int _y;
    int _w;
    char _buf[256];
    int _len;
};
typedef struct Terminal__Ncurses__TextBox Terminal__Ncurses__TextBox;

struct Terminal__Ncurses__Window {
    struct NPClass *isa;
    uint32_t retain_count;
    WINDOW * _win;
    int _x;
    int _y;
    int _w;
    int _h;
};
typedef struct Terminal__Ncurses__Window Terminal__Ncurses__Window;

struct NPString {
    struct NPClass *isa;
    uint32_t retain_count;
    char * _cstr;
    size_t _length;
    uint32_t _hash;
    int _hashIsValid;
};
typedef struct NPString NPString;

extern NPClass nupa___nupa_root_class;
extern NPClass nupa_NPObject_class;
extern NPClass nupa_Terminal__Ncurses__Button_class;
extern NPClass nupa_Terminal__Ncurses__Label_class;
extern NPClass nupa_Terminal__Ncurses__MenuBar_class;
extern NPClass nupa_Terminal__Ncurses__Screen_class;
extern NPClass nupa_Terminal__Ncurses__TextBox_class;
extern NPClass nupa_Terminal__Ncurses__Window_class;
extern NPClass nupa_NPString_class;
void nupa_meta_init(void);

struct nupa_vtable nupa___nupa_root_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))__nupa_root_dealloc,
    .description = NULL,
    .draw = NULL,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))__nupa_root_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))__nupa_root_release,
    .retain = (NPObject * (*)(NPObject *, SEL))__nupa_root_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = NULL,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_NPObject_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .description = NULL,
    .draw = NULL,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = NULL,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_Terminal__Ncurses__Button_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Terminal__Ncurses__Button_dealloc,
    .description = NULL,
    .draw = (int (*)(NPObject *, SEL))Terminal__Ncurses__Button_draw,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = (NPObject * (*)(NPObject *, SEL, Terminal__Ncurses__Window *, int, int, int, NPString *))Terminal__Ncurses__Button_initWithWindow_x_y_w_text_,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = (void (*)(NPObject *, SEL, int))Terminal__Ncurses__Button_setHighlight_,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = NULL,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_Terminal__Ncurses__Label_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Terminal__Ncurses__Label_dealloc,
    .description = NULL,
    .draw = (int (*)(NPObject *, SEL))Terminal__Ncurses__Label_draw,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = (NPObject * (*)(NPObject *, SEL, Terminal__Ncurses__Window *, int, int, NPString *))Terminal__Ncurses__Label_initWithWindow_x_y_text_,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = (void (*)(NPObject *, SEL, NPString *))Terminal__Ncurses__Label_setText_,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = NULL,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_Terminal__Ncurses__MenuBar_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = (void (*)(NPObject *, SEL, const char *))Terminal__Ncurses__MenuBar_addItem_,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .description = NULL,
    .draw = (int (*)(NPObject *, SEL))Terminal__Ncurses__MenuBar_draw,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = (NPObject * (*)(NPObject *, SEL, Terminal__Ncurses__Window *, int))Terminal__Ncurses__MenuBar_initWithWindow_w_,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = (int (*)(NPObject *, SEL))Terminal__Ncurses__MenuBar_selected,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = NULL,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_Terminal__Ncurses__Screen_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = (void (*)(NPObject *, SEL))Terminal__Ncurses__Screen_clearScr,
    .cols = (int (*)(NPObject *, SEL))Terminal__Ncurses__Screen_cols,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Terminal__Ncurses__Screen_dealloc,
    .description = NULL,
    .draw = NULL,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = (int (*)(NPObject *, SEL))Terminal__Ncurses__Screen_mouseEvent,
    .mouseX = (int (*)(NPObject *, SEL))Terminal__Ncurses__Screen_mouseX,
    .mouseY = (int (*)(NPObject *, SEL))Terminal__Ncurses__Screen_mouseY,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = (int (*)(NPObject *, SEL))Terminal__Ncurses__Screen_readChar,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = (int (*)(NPObject *, SEL))Terminal__Ncurses__Screen_rows,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = (void (*)(NPObject *, SEL))Terminal__Ncurses__Screen_update,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_Terminal__Ncurses__TextBox_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .description = NULL,
    .draw = NULL,
    .drawBox = NULL,
    .edit = (const char * (*)(NPObject *, SEL))Terminal__Ncurses__TextBox_edit,
    .handle = NULL,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = (NPObject * (*)(NPObject *, SEL, Terminal__Ncurses__Window *, int, int, int))Terminal__Ncurses__TextBox_initWithWindow_x_y_w_,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = NULL,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = (const char * (*)(NPObject *, SEL))Terminal__Ncurses__TextBox_text,
    .update = NULL,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_Terminal__Ncurses__Window_vtable_inst = {
    .UTF8String = NULL,
    .addItem_ = NULL,
    .characterAtIndex_ = NULL,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = NULL,
    .copy = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Terminal__Ncurses__Window_dealloc,
    .description = NULL,
    .draw = NULL,
    .drawBox = (void (*)(NPObject *, SEL))Terminal__Ncurses__Window_drawBox,
    .edit = NULL,
    .handle = (WINDOW * (*)(NPObject *, SEL))Terminal__Ncurses__Window_handle,
    .hasPrefix_ = NULL,
    .hasSuffix_ = NULL,
    .hash = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = (NPObject * (*)(NPObject *, SEL, int, int, int, int))Terminal__Ncurses__Window_initWithRect_y_w_h_,
    .initWithString_ = NULL,
    .initWithUTF8String_ = NULL,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = NULL,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = NULL,
    .lowercaseString = NULL,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = (void (*)(NPObject *, SEL, int, int))Terminal__Ncurses__Window_moveTo_x_,
    .print_x_text_ = (void (*)(NPObject *, SEL, int, int, NPString *))Terminal__Ncurses__Window_print_x_text_,
    .rangeOfString_ = NULL,
    .readChar = (int (*)(NPObject *, SEL))Terminal__Ncurses__Window_readChar,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = NULL,
    .stringByAppendingUTF8String_ = NULL,
    .substringFromIndex_ = NULL,
    .substringToIndex_ = NULL,
    .substringWithRange_ = NULL,
    .text = NULL,
    .update = (void (*)(NPObject *, SEL))Terminal__Ncurses__Window_update,
    .uppercaseString = NULL,
};

struct nupa_vtable nupa_NPString_vtable_inst = {
    .UTF8String = (const char * (*)(NPObject *, SEL))NPString_UTF8String,
    .addItem_ = NULL,
    .characterAtIndex_ = (char (*)(NPObject *, SEL, size_t))NPString_characterAtIndex_,
    .clearScr = NULL,
    .cols = NULL,
    .compare_ = (int (*)(NPObject *, SEL, NPString *))NPString_compare_,
    .copy = (NPString * (*)(NPObject *, SEL))NPString_copy,
    .dealloc = (void (*)(NPObject *, SEL))NPString_dealloc,
    .description = (NPString * (*)(NPObject *, SEL))NPString_description,
    .draw = NULL,
    .drawBox = NULL,
    .edit = NULL,
    .handle = NULL,
    .hasPrefix_ = (int (*)(NPObject *, SEL, NPString *))NPString_hasPrefix_,
    .hasSuffix_ = (int (*)(NPObject *, SEL, NPString *))NPString_hasSuffix_,
    .hash = (uint32_t (*)(NPObject *, SEL))NPString_hash,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithRect_y_w_h_ = NULL,
    .initWithString_ = (NPString * (*)(NPObject *, SEL, NPString *))NPString_initWithString_,
    .initWithUTF8String_ = (NPString * (*)(NPObject *, SEL, const char *))NPString_initWithUTF8String_,
    .initWithWindow_w_ = NULL,
    .initWithWindow_x_y_text_ = NULL,
    .initWithWindow_x_y_w_ = NULL,
    .initWithWindow_x_y_w_text_ = NULL,
    .isEqualToString_ = (int (*)(NPObject *, SEL, NPString *))NPString_isEqualToString_,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .length = (size_t (*)(NPObject *, SEL))NPString_length,
    .lowercaseString = (NPString * (*)(NPObject *, SEL))NPString_lowercaseString,
    .mouseEvent = NULL,
    .mouseX = NULL,
    .mouseY = NULL,
    .moveTo_x_ = NULL,
    .print_x_text_ = NULL,
    .rangeOfString_ = (NPRange (*)(NPObject *, SEL, NPString *))NPString_rangeOfString_,
    .readChar = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .rows = NULL,
    .selected = NULL,
    .setHighlight_ = NULL,
    .setText_ = NULL,
    .stringByAppendingString_ = (NPString * (*)(NPObject *, SEL, NPString *))NPString_stringByAppendingString_,
    .stringByAppendingUTF8String_ = (NPString * (*)(NPObject *, SEL, const char *))NPString_stringByAppendingUTF8String_,
    .substringFromIndex_ = (NPString * (*)(NPObject *, SEL, size_t))NPString_substringFromIndex_,
    .substringToIndex_ = (NPString * (*)(NPObject *, SEL, size_t))NPString_substringToIndex_,
    .substringWithRange_ = (NPString * (*)(NPObject *, SEL, NPRange))NPString_substringWithRange_,
    .text = NULL,
    .update = NULL,
    .uppercaseString = (NPString * (*)(NPObject *, SEL))NPString_uppercaseString,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Terminal__Ncurses__Button_meta_vtable nupa_Terminal__Ncurses__Button_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Terminal__Ncurses__Button_getClass,
};

struct nupa_Terminal__Ncurses__Label_meta_vtable nupa_Terminal__Ncurses__Label_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Terminal__Ncurses__Label_getClass,
};

struct nupa_Terminal__Ncurses__MenuBar_meta_vtable nupa_Terminal__Ncurses__MenuBar_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Terminal__Ncurses__MenuBar_getClass,
};

struct nupa_Terminal__Ncurses__Screen_meta_vtable nupa_Terminal__Ncurses__Screen_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .screen = Terminal__Ncurses__Screen_screen,
    .class = Terminal__Ncurses__Screen_getClass,
};

struct nupa_Terminal__Ncurses__TextBox_meta_vtable nupa_Terminal__Ncurses__TextBox_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Terminal__Ncurses__TextBox_getClass,
};

struct nupa_Terminal__Ncurses__Window_meta_vtable nupa_Terminal__Ncurses__Window_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Terminal__Ncurses__Window_getClass,
};

struct nupa_NPString_meta_vtable nupa_NPString_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .stringWithUTF8String_ = NPString_stringWithUTF8String_,
    .stringWithString_ = NPString_stringWithString_,
    .class = NPString_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Terminal__Ncurses__Button_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Terminal__Ncurses__Label_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Terminal__Ncurses__MenuBar_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Terminal__Ncurses__Screen_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Terminal__Ncurses__TextBox_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Terminal__Ncurses__Window_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * NPString_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nupa___nupa_root_class;
NPClass nupa_NPObject_class;
NPClass nupa_Terminal__Ncurses__Button_class;
NPClass nupa_Terminal__Ncurses__Label_class;
NPClass nupa_Terminal__Ncurses__MenuBar_class;
NPClass nupa_Terminal__Ncurses__Screen_class;
NPClass nupa_Terminal__Ncurses__TextBox_class;
NPClass nupa_Terminal__Ncurses__Window_class;
NPClass nupa_NPString_class;

void nupa_meta_init(void) {
    nupa___nupa_root_class = (NPClass){
        .name = "__nupa_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __nupa_root),
        .vtable = &nupa___nupa_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = &nupa___nupa_root_class,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Terminal__Ncurses__Button_class = (NPClass){
        .name = "Terminal::Ncurses::Button",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Terminal__Ncurses__Button),
        .vtable = &nupa_Terminal__Ncurses__Button_vtable_inst,
        .class_vtable = &nupa_Terminal__Ncurses__Button_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Terminal__Ncurses__Label_class = (NPClass){
        .name = "Terminal::Ncurses::Label",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Terminal__Ncurses__Label),
        .vtable = &nupa_Terminal__Ncurses__Label_vtable_inst,
        .class_vtable = &nupa_Terminal__Ncurses__Label_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Terminal__Ncurses__MenuBar_class = (NPClass){
        .name = "Terminal::Ncurses::MenuBar",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Terminal__Ncurses__MenuBar),
        .vtable = &nupa_Terminal__Ncurses__MenuBar_vtable_inst,
        .class_vtable = &nupa_Terminal__Ncurses__MenuBar_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Terminal__Ncurses__Screen_class = (NPClass){
        .name = "Terminal::Ncurses::Screen",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Terminal__Ncurses__Screen),
        .vtable = &nupa_Terminal__Ncurses__Screen_vtable_inst,
        .class_vtable = &nupa_Terminal__Ncurses__Screen_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Terminal__Ncurses__TextBox_class = (NPClass){
        .name = "Terminal::Ncurses::TextBox",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Terminal__Ncurses__TextBox),
        .vtable = &nupa_Terminal__Ncurses__TextBox_vtable_inst,
        .class_vtable = &nupa_Terminal__Ncurses__TextBox_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Terminal__Ncurses__Window_class = (NPClass){
        .name = "Terminal::Ncurses::Window",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Terminal__Ncurses__Window),
        .vtable = &nupa_Terminal__Ncurses__Window_vtable_inst,
        .class_vtable = &nupa_Terminal__Ncurses__Window_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPString_class = (NPClass){
        .name = "NPString",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPString),
        .vtable = &nupa_NPString_vtable_inst,
        .class_vtable = &nupa_NPString_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject *nupa_string_from_cstr(const char *cstr) {
    if (!cstr) cstr = "";
    NPObject *obj = nupa_alloc(&nupa_NPString_class);
    if (!obj) return NULL;
    struct NPString *str = (struct NPString *)obj;
    size_t len = strlen(cstr);
    str->_cstr = (char *)malloc(len + 1);
    if (str->_cstr) strcpy(str->_cstr, cstr);
    str->_length = len;
    str->_hash = 0;
    str->_hashIsValid = 0;
    return nupa_autorelease(obj);
}

NPObject * __nupa_root_init(NPObject * self, SEL _cmd) {
    return nupa_init(self);
}

void __nupa_root_dealloc(NPObject * self, SEL _cmd) {
    return;
}

void __nupa_root_release(NPObject * self, SEL _cmd) {
    nupa_release(self);
}

NPObject * __nupa_root_retain(NPObject * self, SEL _cmd) {
    return nupa_retain(self);
}

_Bool __nupa_root_isKindOf_(NPObject * self, SEL _cmd, NPClass * cls) {
    return nupa_isKindOf(self, cls);
}

NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    return nupa_init(self);
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    return;
}

void NPObject_release(NPObject * self, SEL _cmd) {
    nupa_release(self);
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
    return nupa_retain(self);
}

NPString * NPString_stringWithUTF8String_(NPClass * self, SEL _cmd, const char * cstr) {
    return ({ NPObject *__nupa_tmp_0 = ((NPObject *)(NPObject_alloc(self, __nupa_sel_alloc))); __nupa_tmp_0 ? ((struct nupa_vtable *)__nupa_tmp_0->isa->vtable)->initWithUTF8String_(__nupa_tmp_0, __nupa_sel_initWithUTF8String_, cstr) : 0; });
}

NPString * NPString_stringWithString_(NPClass * self, SEL _cmd, NPString * str) {
    return ({ NPObject *__nupa_tmp_1 = ((NPObject *)(NPObject_alloc(self, __nupa_sel_alloc))); __nupa_tmp_1 ? ((struct nupa_vtable *)__nupa_tmp_1->isa->vtable)->initWithString_(__nupa_tmp_1, __nupa_sel_initWithString_, (NPString *)(str)) : 0; });
}

NPString * NPString_initWithUTF8String_(NPObject * self, SEL _cmd, const char * cstr) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if ((self && cstr))     {
        ((struct NPString *)self)->_length = strlen(cstr);
        ((struct NPString *)self)->_cstr = (char *)malloc((((struct NPString *)self)->_length + 1));
        if (((struct NPString *)self)->_cstr)         {
            strcpy(((struct NPString *)self)->_cstr, cstr);
        }
        ((struct NPString *)self)->_hash = 0;
        ((struct NPString *)self)->_hashIsValid = 0;
    }
    return self;
}

NPString * NPString_initWithString_(NPObject * self, SEL _cmd, NPString * str) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if ((self && str))     {
        char * src = (char *)(((struct nupa_vtable *)(str->isa->vtable))->UTF8String((NPObject *)(str), __nupa_sel_UTF8String));
        if (src)         {
            ((struct NPString *)self)->_length = strlen(src);
            ((struct NPString *)self)->_cstr = (char *)malloc((((struct NPString *)self)->_length + 1));
            if (((struct NPString *)self)->_cstr)             {
                strcpy(((struct NPString *)self)->_cstr, src);
            }
        }
        ((struct NPString *)self)->_hash = 0;
        ((struct NPString *)self)->_hashIsValid = 0;
    }
    return self;
}

size_t NPString_length(NPObject * self, SEL _cmd) {
    return ((struct NPString *)self)->_length;
}

const char * NPString_UTF8String(NPObject * self, SEL _cmd) {
    return ((struct NPString *)self)->_cstr ? ((struct NPString *)self)->_cstr : "";
}

char NPString_characterAtIndex_(NPObject * self, SEL _cmd, size_t index) {
    if ((((struct NPString *)self)->_cstr && (index < ((struct NPString *)self)->_length)))     {
        return ((struct NPString *)self)->_cstr[index];
    }
    return '\x00';
}

int NPString_isEqualToString_(NPObject * self, SEL _cmd, NPString * other) {
    if (self == (NPObject *)other)     return 1;
    if (!other)     return 0;
    char * s1 = (char *)(((struct nupa_vtable *)(self->isa->vtable))->UTF8String(self, __nupa_sel_UTF8String));
    char * s2 = (char *)(((struct nupa_vtable *)(other->isa->vtable))->UTF8String((NPObject *)(other), __nupa_sel_UTF8String));
    return strcmp(s1, s2) == 0;
}

int NPString_compare_(NPObject * self, SEL _cmd, NPString * other) {
    if (!other)     return 1;
    char * s1 = (char *)(((struct nupa_vtable *)(self->isa->vtable))->UTF8String(self, __nupa_sel_UTF8String));
    char * s2 = (char *)(((struct nupa_vtable *)(other->isa->vtable))->UTF8String((NPObject *)(other), __nupa_sel_UTF8String));
    return strcmp(s1, s2);
}

int NPString_hasPrefix_(NPObject * self, SEL _cmd, NPString * prefix) {
    if (!prefix)     return 0;
    char * pre = (char *)(((struct nupa_vtable *)(prefix->isa->vtable))->UTF8String((NPObject *)(prefix), __nupa_sel_UTF8String));
    char * str = (char *)(((struct nupa_vtable *)(self->isa->vtable))->UTF8String(self, __nupa_sel_UTF8String));
    size_t preLen = strlen(pre);
    return strncmp(str, pre, preLen) == 0;
}

int NPString_hasSuffix_(NPObject * self, SEL _cmd, NPString * suffix) {
    if (!suffix)     return 0;
    char * suf = (char *)(((struct nupa_vtable *)(suffix->isa->vtable))->UTF8String((NPObject *)(suffix), __nupa_sel_UTF8String));
    char * str = (char *)(((struct nupa_vtable *)(self->isa->vtable))->UTF8String(self, __nupa_sel_UTF8String));
    size_t sufLen = strlen(suf);
    size_t strLen = strlen(str);
    if ((sufLen > strLen))     return 0;
    return strcmp(((str + strLen) - sufLen), suf) == 0;
}

NPRange NPString_rangeOfString_(NPObject * self, SEL _cmd, NPString * substring) {
    NPRange range = { 0, 0 };
    if ((!substring || !((struct NPString *)self)->_cstr))     return range;
    char * sub = (char *)(((struct nupa_vtable *)(substring->isa->vtable))->UTF8String((NPObject *)(substring), __nupa_sel_UTF8String));
    char * found = (char *)(strstr(((struct NPString *)self)->_cstr, sub));
    if (found)     {
        range.location = (size_t)(found - ((struct NPString *)self)->_cstr);
        range.length = strlen(sub);
    }
    else     {
        range.location = (size_t)-1;
        range.length = 0;
    }
    return range;
}

NPString * NPString_substringFromIndex_(NPObject * self, SEL _cmd, size_t from) {
    if ((!((struct NPString *)self)->_cstr || (from > ((struct NPString *)self)->_length)))     return NULL;
    return NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, (((struct NPString *)self)->_cstr + from));
}

NPString * NPString_substringToIndex_(NPObject * self, SEL _cmd, size_t to) {
    if (!((struct NPString *)self)->_cstr)     return NULL;
    if ((to > ((struct NPString *)self)->_length))     to = ((struct NPString *)self)->_length;
    char * buf = (char *)malloc((to + 1));
    strncpy(buf, ((struct NPString *)self)->_cstr, to);
    buf[to] = '\x00';
    NPString * result = (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf));
    free(buf);
    return result;
}

NPString * NPString_substringWithRange_(NPObject * self, SEL _cmd, NPRange range) {
    if (!((struct NPString *)self)->_cstr)     return NULL;
    if (((range.location > ((struct NPString *)self)->_length) || ((range.location + range.length) > ((struct NPString *)self)->_length)))     {
        return NULL;
    }
    char * buf = (char *)malloc((range.length + 1));
    strncpy(buf, (((struct NPString *)self)->_cstr + range.location), range.length);
    buf[range.length] = '\x00';
    NPString * result = (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf));
    free(buf);
    return result;
}

NPString * NPString_stringByAppendingString_(NPObject * self, SEL _cmd, NPString * other) {
    if (!other)     return ((struct nupa_vtable *)(self->isa->vtable))->copy(self, __nupa_sel_copy);
    char * s1 = (char *)(((struct nupa_vtable *)(self->isa->vtable))->UTF8String(self, __nupa_sel_UTF8String));
    char * s2 = (char *)(((struct nupa_vtable *)(other->isa->vtable))->UTF8String((NPObject *)(other), __nupa_sel_UTF8String));
    size_t len1 = strlen(s1);
    size_t len2 = strlen(s2);
    char * buf = (char *)malloc(((len1 + len2) + 1));
    strcpy(buf, s1);
    strcat(buf, s2);
    NPString * result = (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf));
    free(buf);
    return result;
}

NPString * NPString_stringByAppendingUTF8String_(NPObject * self, SEL _cmd, const char * cstr) {
    if (!cstr)     return ((struct nupa_vtable *)(self->isa->vtable))->copy(self, __nupa_sel_copy);
    char * s1 = (char *)(((struct nupa_vtable *)(self->isa->vtable))->UTF8String(self, __nupa_sel_UTF8String));
    size_t len1 = strlen(s1);
    size_t len2 = strlen(cstr);
    char * buf = (char *)malloc(((len1 + len2) + 1));
    strcpy(buf, s1);
    strcat(buf, cstr);
    NPString * result = (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf));
    free(buf);
    return result;
}

NPString * NPString_uppercaseString(NPObject * self, SEL _cmd) {
    if (!((struct NPString *)self)->_cstr)     return NULL;
    char * buf = (char *)malloc((((struct NPString *)self)->_length + 1));
    for (unsigned long i = 0;
(i <= ((struct NPString *)self)->_length); (i)++)     {
        buf[i] = (char)toupper((unsigned char)((struct NPString *)self)->_cstr[i]);
    }
    NPString * result = (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf));
    free(buf);
    return result;
}

NPString * NPString_lowercaseString(NPObject * self, SEL _cmd) {
    if (!((struct NPString *)self)->_cstr)     return NULL;
    char * buf = (char *)malloc((((struct NPString *)self)->_length + 1));
    for (unsigned long i = 0;
(i <= ((struct NPString *)self)->_length); (i)++)     {
        buf[i] = (char)tolower((unsigned char)((struct NPString *)self)->_cstr[i]);
    }
    NPString * result = (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf));
    free(buf);
    return result;
}

uint32_t NPString_hash(NPObject * self, SEL _cmd) {
    if (((struct NPString *)self)->_hashIsValid)     return ((struct NPString *)self)->_hash;
    uint32_t h = 2166136261;
    if (((struct NPString *)self)->_cstr)     {
        for (unsigned long i = 0;
(i < ((struct NPString *)self)->_length); (i)++)         {
            (h ^= (uint8_t)((struct NPString *)self)->_cstr[i]);
            (h *= 16777619);
        }
    }
    ((struct NPString *)self)->_hash = h;
    ((struct NPString *)self)->_hashIsValid = 1;
    return h;
}

NPString * NPString_description(NPObject * self, SEL _cmd) {
    return ((struct nupa_vtable *)(self->isa->vtable))->copy(self, __nupa_sel_copy);
}

NPString * NPString_copy(NPObject * self, SEL _cmd) {
    return NPString_stringWithString_(&nupa_NPString_class, __nupa_sel_stringWithString_, self);
}

void NPString_dealloc(NPObject * self, SEL _cmd) {
    if (((struct NPString *)self)->_cstr)     {
        free(((struct NPString *)self)->_cstr);
        ((struct NPString *)self)->_cstr = NULL;
    }
    ((struct NPString *)self)->_length = 0;
    (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

NPObject * Terminal__Ncurses__Screen_screen(NPClass * self, SEL _cmd) {
    self = ({ NPObject *__nupa_tmp_2 = ((NPObject *)(NPObject_alloc(self, __nupa_sel_alloc))); __nupa_tmp_2 ? ((struct nupa_vtable *)__nupa_tmp_2->isa->vtable)->init(__nupa_tmp_2, __nupa_sel_init) : 0; });
    if (self)     {
        initscr();
        cbreak();
        noecho();
        keypad(stdscr, TRUE);
        curs_set(0);
        mousemask((ALL_MOUSE_EVENTS | REPORT_MOUSE_POSITION), NULL);
        ((struct Terminal__Ncurses__Screen *)self)->_rows = getmaxy(stdscr);
        ((struct Terminal__Ncurses__Screen *)self)->_cols = getmaxx(stdscr);
    }
    return self;
}

void Terminal__Ncurses__Screen_dealloc(NPObject * self, SEL _cmd) {
    endwin();
    (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

void Terminal__Ncurses__Screen_update(NPObject * self, SEL _cmd) {
    refresh();
}

void Terminal__Ncurses__Screen_clearScr(NPObject * self, SEL _cmd) {
    clear();
}

int Terminal__Ncurses__Screen_readChar(NPObject * self, SEL _cmd) {
    return wgetch(stdscr);
}

int Terminal__Ncurses__Screen_rows(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__Screen *)self)->_rows;
}

int Terminal__Ncurses__Screen_cols(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__Screen *)self)->_cols;
}

int Terminal__Ncurses__Screen_mouseEvent(NPObject * self, SEL _cmd) {
    int x, y, btn;
    int r = nk_mouse_get_event(&x, &y, &btn);
    if (r)     {
        ((struct Terminal__Ncurses__Screen *)self)->_mouseX = x;
        ((struct Terminal__Ncurses__Screen *)self)->_mouseY = y;
        ((struct Terminal__Ncurses__Screen *)self)->_mouseBtn = btn;
    }
    return r;
}

int Terminal__Ncurses__Screen_mouseX(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__Screen *)self)->_mouseX;
}

int Terminal__Ncurses__Screen_mouseY(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__Screen *)self)->_mouseY;
}

NPObject * Terminal__Ncurses__Window_initWithRect_y_w_h_(NPObject * self, SEL _cmd, int x, int y, int w, int h) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if (self)     {
        ((struct Terminal__Ncurses__Window *)self)->_x = x;
        ((struct Terminal__Ncurses__Window *)self)->_y = y;
        ((struct Terminal__Ncurses__Window *)self)->_w = w;
        ((struct Terminal__Ncurses__Window *)self)->_h = h;
        ((struct Terminal__Ncurses__Window *)self)->_win = (WINDOW *)(newwin(h, w, y, x));
    }
    return self;
}

void Terminal__Ncurses__Window_dealloc(NPObject * self, SEL _cmd) {
    if (((struct Terminal__Ncurses__Window *)self)->_win)     delwin(((struct Terminal__Ncurses__Window *)self)->_win);
    (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

void Terminal__Ncurses__Window_update(NPObject * self, SEL _cmd) {
    wrefresh(((struct Terminal__Ncurses__Window *)self)->_win);
}

void Terminal__Ncurses__Window_drawBox(NPObject * self, SEL _cmd) {
    box(((struct Terminal__Ncurses__Window *)self)->_win, 0, 0);
}

void Terminal__Ncurses__Window_moveTo_x_(NPObject * self, SEL _cmd, int y, int x) {
    wmove(((struct Terminal__Ncurses__Window *)self)->_win, y, x);
}

void Terminal__Ncurses__Window_print_x_text_(NPObject * self, SEL _cmd, int y, int x, NPString * text) {
    mvwprintw(((struct Terminal__Ncurses__Window *)self)->_win, y, x, "%s", ((struct nupa_vtable *)(text->isa->vtable))->UTF8String((NPObject *)(text), __nupa_sel_UTF8String));
}

int Terminal__Ncurses__Window_readChar(NPObject * self, SEL _cmd) {
    return wgetch(((struct Terminal__Ncurses__Window *)self)->_win);
}

WINDOW * Terminal__Ncurses__Window_handle(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__Window *)self)->_win;
}

NPObject * Terminal__Ncurses__Label_initWithWindow_x_y_text_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int x, int y, NPString * text) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if (self)     {
        ((struct Terminal__Ncurses__Label *)self)->_win = (WINDOW *)(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle));
        ((struct Terminal__Ncurses__Label *)self)->_x = x;
        ((struct Terminal__Ncurses__Label *)self)->_y = y;
        ((struct Terminal__Ncurses__Label *)self)->_text = text;
        ((struct nupa_vtable *)(text->isa->vtable))->retain((NPObject *)(text), __nupa_sel_retain);
    }
    return self;
}

void Terminal__Ncurses__Label_dealloc(NPObject * self, SEL _cmd) {
    if (((struct Terminal__Ncurses__Label *)self)->_text)     ({ NPObject *__nupa_tmp_3 = ((NPObject *)(((struct Terminal__Ncurses__Label *)self)->_text)); __nupa_tmp_3 ? ((struct nupa_vtable *)__nupa_tmp_3->isa->vtable)->release(__nupa_tmp_3, __nupa_sel_release) : 0; });
    (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

void Terminal__Ncurses__Label_draw(NPObject * self, SEL _cmd) {
    if (((struct Terminal__Ncurses__Label *)self)->_text)     mvwprintw(((struct Terminal__Ncurses__Label *)self)->_win, ((struct Terminal__Ncurses__Label *)self)->_y, ((struct Terminal__Ncurses__Label *)self)->_x, "%s", ({ NPObject *__nupa_tmp_4 = ((NPObject *)(((struct Terminal__Ncurses__Label *)self)->_text)); __nupa_tmp_4 ? ((struct nupa_vtable *)__nupa_tmp_4->isa->vtable)->UTF8String(__nupa_tmp_4, __nupa_sel_UTF8String) : 0; }));
}

void Terminal__Ncurses__Label_setText_(NPObject * self, SEL _cmd, NPString * text) {
    if (((struct Terminal__Ncurses__Label *)self)->_text)     ({ NPObject *__nupa_tmp_5 = ((NPObject *)(((struct Terminal__Ncurses__Label *)self)->_text)); __nupa_tmp_5 ? ((struct nupa_vtable *)__nupa_tmp_5->isa->vtable)->release(__nupa_tmp_5, __nupa_sel_release) : 0; });
    ((struct Terminal__Ncurses__Label *)self)->_text = text;
    ((struct nupa_vtable *)(text->isa->vtable))->retain((NPObject *)(text), __nupa_sel_retain);
}

NPObject * Terminal__Ncurses__Button_initWithWindow_x_y_w_text_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int x, int y, int w, NPString * text) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if (self)     {
        ((struct Terminal__Ncurses__Button *)self)->_win = (WINDOW *)(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle));
        ((struct Terminal__Ncurses__Button *)self)->_x = x;
        ((struct Terminal__Ncurses__Button *)self)->_y = y;
        ((struct Terminal__Ncurses__Button *)self)->_w = w;
        ((struct Terminal__Ncurses__Button *)self)->_text = text;
        ((struct nupa_vtable *)(text->isa->vtable))->retain((NPObject *)(text), __nupa_sel_retain);
        ((struct Terminal__Ncurses__Button *)self)->_highlighted = 0;
    }
    return self;
}

void Terminal__Ncurses__Button_dealloc(NPObject * self, SEL _cmd) {
    if (((struct Terminal__Ncurses__Button *)self)->_text)     ({ NPObject *__nupa_tmp_6 = ((NPObject *)(((struct Terminal__Ncurses__Button *)self)->_text)); __nupa_tmp_6 ? ((struct nupa_vtable *)__nupa_tmp_6->isa->vtable)->release(__nupa_tmp_6, __nupa_sel_release) : 0; });
    (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

int Terminal__Ncurses__Button_draw(NPObject * self, SEL _cmd) {
    char * cstr = ((struct Terminal__Ncurses__Button *)self)->_text ? ({ NPObject *__nupa_tmp_7 = ((NPObject *)(((struct Terminal__Ncurses__Button *)self)->_text)); __nupa_tmp_7 ? ((struct nupa_vtable *)__nupa_tmp_7->isa->vtable)->UTF8String(__nupa_tmp_7, __nupa_sel_UTF8String) : 0; }) : "";
    if (((struct Terminal__Ncurses__Button *)self)->_highlighted)     {
        wattron(((struct Terminal__Ncurses__Button *)self)->_win, A_REVERSE);
        mvwprintw(((struct Terminal__Ncurses__Button *)self)->_win, ((struct Terminal__Ncurses__Button *)self)->_y, ((struct Terminal__Ncurses__Button *)self)->_x, "%-*s", ((struct Terminal__Ncurses__Button *)self)->_w, cstr);
        wattroff(((struct Terminal__Ncurses__Button *)self)->_win, A_REVERSE);
    }
    else     {
        mvwprintw(((struct Terminal__Ncurses__Button *)self)->_win, ((struct Terminal__Ncurses__Button *)self)->_y, ((struct Terminal__Ncurses__Button *)self)->_x, "%-*s", ((struct Terminal__Ncurses__Button *)self)->_w, cstr);
    }
    return ((struct Terminal__Ncurses__Button *)self)->_highlighted;
}

void Terminal__Ncurses__Button_setHighlight_(NPObject * self, SEL _cmd, int hl) {
    ((struct Terminal__Ncurses__Button *)self)->_highlighted = hl;
}

NPObject * Terminal__Ncurses__TextBox_initWithWindow_x_y_w_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int x, int y, int w) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if (self)     {
        ((struct Terminal__Ncurses__TextBox *)self)->_win = (WINDOW *)(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle));
        ((struct Terminal__Ncurses__TextBox *)self)->_x = x;
        ((struct Terminal__Ncurses__TextBox *)self)->_y = y;
        ((struct Terminal__Ncurses__TextBox *)self)->_w = w;
        memset(((struct Terminal__Ncurses__TextBox *)self)->_buf, 0, 256);
        ((struct Terminal__Ncurses__TextBox *)self)->_len = 0;
    }
    return self;
}

const char * Terminal__Ncurses__TextBox_edit(NPObject * self, SEL _cmd) {
    int ch;
    int pos = ((struct Terminal__Ncurses__TextBox *)self)->_len;
    while (1)     {
        mvwprintw(((struct Terminal__Ncurses__TextBox *)self)->_win, ((struct Terminal__Ncurses__TextBox *)self)->_y, ((struct Terminal__Ncurses__TextBox *)self)->_x, "%-*s", ((struct Terminal__Ncurses__TextBox *)self)->_w, ((struct Terminal__Ncurses__TextBox *)self)->_buf);
        wmove(((struct Terminal__Ncurses__TextBox *)self)->_win, ((struct Terminal__Ncurses__TextBox *)self)->_y, (((struct Terminal__Ncurses__TextBox *)self)->_x + pos));
        wrefresh(((struct Terminal__Ncurses__TextBox *)self)->_win);
        ch = wgetch(stdscr);
        if ((ch == '\n' || ch == KEY_ENTER))         break;
        if ((ch == KEY_BACKSPACE || ch == 127))         {
            if ((pos > 0))             {
                memmove(&((struct Terminal__Ncurses__TextBox *)self)->_buf[(pos - 1)], &((struct Terminal__Ncurses__TextBox *)self)->_buf[pos], (((struct Terminal__Ncurses__TextBox *)self)->_len - pos));
                (pos)--;
                (((struct Terminal__Ncurses__TextBox *)self)->_len)--;
                ((struct Terminal__Ncurses__TextBox *)self)->_buf[((struct Terminal__Ncurses__TextBox *)self)->_len] = '\x00';
            }
        }
        else         if (ch == KEY_LEFT)         {
            if ((pos > 0))             (pos)--;
        }
        else         if (ch == KEY_RIGHT)         {
            if ((pos < ((struct Terminal__Ncurses__TextBox *)self)->_len))             (pos)++;
        }
        else         if ((((ch >= 32) && (ch < 127)) && (((struct Terminal__Ncurses__TextBox *)self)->_len < 255)))         {
            memmove(&((struct Terminal__Ncurses__TextBox *)self)->_buf[(pos + 1)], &((struct Terminal__Ncurses__TextBox *)self)->_buf[pos], (((struct Terminal__Ncurses__TextBox *)self)->_len - pos));
            ((struct Terminal__Ncurses__TextBox *)self)->_buf[pos] = (char)ch;
            (pos)++;
            (((struct Terminal__Ncurses__TextBox *)self)->_len)++;
            ((struct Terminal__Ncurses__TextBox *)self)->_buf[((struct Terminal__Ncurses__TextBox *)self)->_len] = '\x00';
        }
    }
    return ((struct Terminal__Ncurses__TextBox *)self)->_buf;
}

const char * Terminal__Ncurses__TextBox_text(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__TextBox *)self)->_buf;
}

NPObject * Terminal__Ncurses__MenuBar_initWithWindow_w_(NPObject * self, SEL _cmd, Terminal__Ncurses__Window * win, int w) {
    self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
    if (self)     {
        ((struct Terminal__Ncurses__MenuBar *)self)->_win = (WINDOW *)(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle));
        ((struct Terminal__Ncurses__MenuBar *)self)->_w = w;
        ((struct Terminal__Ncurses__MenuBar *)self)->_count = 0;
        ((struct Terminal__Ncurses__MenuBar *)self)->_selected = 0;
        memset(((struct Terminal__Ncurses__MenuBar *)self)->_items, 0, 320);
    }
    return self;
}

void Terminal__Ncurses__MenuBar_addItem_(NPObject * self, SEL _cmd, const char * label) {
    if ((((struct Terminal__Ncurses__MenuBar *)self)->_count < 10))     {
        int offset = (((struct Terminal__Ncurses__MenuBar *)self)->_count * 32);
        strncpy((((struct Terminal__Ncurses__MenuBar *)self)->_items + offset), label, 31);
        ((struct Terminal__Ncurses__MenuBar *)self)->_items[(offset + 31)] = '\x00';
        (((struct Terminal__Ncurses__MenuBar *)self)->_count)++;
    }
}

int Terminal__Ncurses__MenuBar_draw(NPObject * self, SEL _cmd) {
    int x = 1;
    for (int i = 0;
(i < ((struct Terminal__Ncurses__MenuBar *)self)->_count); (i)++)     {
        int offset = (i * 32);
        if (i == ((struct Terminal__Ncurses__MenuBar *)self)->_selected)         {
            wattron(((struct Terminal__Ncurses__MenuBar *)self)->_win, A_REVERSE);
            mvwprintw(((struct Terminal__Ncurses__MenuBar *)self)->_win, 0, x, " %s ", (((struct Terminal__Ncurses__MenuBar *)self)->_items + offset));
            wattroff(((struct Terminal__Ncurses__MenuBar *)self)->_win, A_REVERSE);
        }
        else         {
            mvwprintw(((struct Terminal__Ncurses__MenuBar *)self)->_win, 0, x, " %s ", (((struct Terminal__Ncurses__MenuBar *)self)->_items + offset));
        }
        (x += ((int)strlen((((struct Terminal__Ncurses__MenuBar *)self)->_items + offset)) + 2));
    }
    return ((struct Terminal__Ncurses__MenuBar *)self)->_selected;
}

int Terminal__Ncurses__MenuBar_selected(NPObject * self, SEL _cmd) {
    return ((struct Terminal__Ncurses__MenuBar *)self)->_selected;
}

NPObject * nupa_alloc(struct NPClass * cls);

NPObject * nupa_init(NPObject * self);

void nupa_release(NPObject * obj);

NPObject * nupa_retain(NPObject * obj);

int nk_mouse_get_event(int * x, int * y, int * btn);

float nk_cpu_usage(void );

void nk_mem_info(unsigned long long * used, unsigned long long * total);

void nk_disk_info(unsigned long long * used, unsigned long long * total);

int main(void) {
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __nupa_pool = nupa_autoreleasepool_push();
        Terminal__Ncurses__Screen * scr = (Terminal__Ncurses__Screen *)(Terminal__Ncurses__Screen_screen(&nupa_Terminal__Ncurses__Screen_class, __nupa_sel_screen));
        int cols = ((struct nupa_vtable *)(scr->isa->vtable))->cols((NPObject *)(scr), __nupa_sel_cols), rows = ((struct nupa_vtable *)(scr->isa->vtable))->rows((NPObject *)(scr), __nupa_sel_rows);
        NPObject *__nupa_tmp_8 = (NPObject_alloc(&nupa_Terminal__Ncurses__Window_class, __nupa_sel_alloc));
        Terminal__Ncurses__Window * win = (Terminal__Ncurses__Window *)(((struct nupa_vtable *)__nupa_tmp_8->isa->vtable)->initWithRect_y_w_h_(__nupa_tmp_8, __nupa_sel_initWithRect_y_w_h_, 0, 0, cols, rows));
        NPObject *__nupa_tmp_9 = (NPObject_alloc(&nupa_Terminal__Ncurses__Button_class, __nupa_sel_alloc));
        Terminal__Ncurses__Button * quitBtn = (Terminal__Ncurses__Button *)(((struct nupa_vtable *)__nupa_tmp_9->isa->vtable)->initWithWindow_x_y_w_text_(__nupa_tmp_9, __nupa_sel_initWithWindow_x_y_w_text_, win, 2, (rows - 2), 10, nupa_string_from_cstr(" Quit ")));
        int running = 1;
        while (running)         {
            float cpu = nk_cpu_usage();
            unsigned long long mem_used = 0, mem_total = 0;
            unsigned long long disk_used = 0, disk_total = 0;
            nk_mem_info(&mem_used, &mem_total);
            nk_disk_info(&disk_used, &disk_total);
            char buf[128];
            ((struct nupa_vtable *)(win->isa->vtable))->drawBox((NPObject *)(win), __nupa_sel_drawBox);
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 0, 2, (NPString *)(nupa_string_from_cstr(" System Monitor ")));
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 2, 2, (NPString *)(nupa_string_from_cstr("CPU")));
            int cpu_bars = (int)(cpu / 5.0f);
            if ((cpu_bars > 20))             cpu_bars = 20;
            memset(buf, ' ', 20);
            buf[20] = '\x00';
            for (int i = 0;
((i < cpu_bars) && (i < 20)); (i)++)             buf[i] = '#';
            wattron(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle), A_REVERSE);
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 3, 4, (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf)));
            wattroff(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle), A_REVERSE);
            snprintf(buf, sizeof(buf), "  %.1f%%", cpu);
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 3, 26, (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf)));
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 5, 2, (NPString *)(nupa_string_from_cstr("Memory")));
            float mem_pct = (mem_total > 0) ? (((float)mem_used / mem_total) * 100.0f) : 0;
            int mem_bars = (int)(mem_pct / 5.0f);
            if ((mem_bars > 20))             mem_bars = 20;
            memset(buf, ' ', 20);
            buf[20] = '\x00';
            for (int i = 0;
((i < mem_bars) && (i < 20)); (i)++)             buf[i] = '#';
            wattron(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle), A_REVERSE);
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 6, 4, (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf)));
            wattroff(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle), A_REVERSE);
            snprintf(buf, sizeof(buf), "  %.1f%%  (%llu MB / %llu MB)", mem_pct, (mem_used / 1000000), (mem_total / 1000000));
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 6, 26, (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf)));
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 8, 2, (NPString *)(nupa_string_from_cstr("Disk")));
            float disk_pct = (disk_total > 0) ? (((float)disk_used / disk_total) * 100.0f) : 0;
            int disk_bars = (int)(disk_pct / 5.0f);
            if ((disk_bars > 20))             disk_bars = 20;
            memset(buf, ' ', 20);
            buf[20] = '\x00';
            for (int i = 0;
((i < disk_bars) && (i < 20)); (i)++)             buf[i] = '#';
            wattron(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle), A_REVERSE);
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 9, 4, (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf)));
            wattroff(((struct nupa_vtable *)(win->isa->vtable))->handle((NPObject *)(win), __nupa_sel_handle), A_REVERSE);
            snprintf(buf, sizeof(buf), "  %.1f%%  (%llu GB / %llu GB)", disk_pct, (disk_used / 1000000000), (disk_total / 1000000000));
            ((struct nupa_vtable *)(win->isa->vtable))->print_x_text_((NPObject *)(win), __nupa_sel_print_x_text_, 9, 26, (NPString *)(NPString_stringWithUTF8String_(&nupa_NPString_class, __nupa_sel_stringWithUTF8String_, buf)));
            ((struct nupa_vtable *)(quitBtn->isa->vtable))->draw((NPObject *)(quitBtn), __nupa_sel_draw);
            ((struct nupa_vtable *)(win->isa->vtable))->update((NPObject *)(win), __nupa_sel_update);
            refresh();
            timeout(2000);
            int ch = wgetch(stdscr);
            if ((ch == 'q' || ch == 'Q'))             running = 0;
        }
        ((struct nupa_vtable *)(quitBtn->isa->vtable))->release((NPObject *)(quitBtn), __nupa_sel_release);
        ((struct nupa_vtable *)(win->isa->vtable))->release((NPObject *)(win), __nupa_sel_release);
        ((struct nupa_vtable *)(scr->isa->vtable))->release((NPObject *)(scr), __nupa_sel_release);
        nupa_autoreleasepool_pop(__nupa_pool);
    }
    return 0;
}

