// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Box_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Box_vtable_index_size 4
#define nupa_Box_vtable_index_setSize_ 5

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_setSize_ = {.name = "setSize_", .hash = 0x74BDCB47};
static const SEL __nupa_sel_size = {.name = "size", .hash = 0x23A0D95C};

typedef struct NPObject NPObject;
typedef struct Box Box;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
int Box_size(NPObject * self, SEL _cmd);
void Box_setSize_(NPObject * self, SEL _cmd, int s);
NPClass * Box_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Box_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Box {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Box Box;
struct nupa_Box_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    int (*size)(NPObject *, SEL);
    void (*setSize_)(NPObject *, SEL, int);
};
struct nupa_Box_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
int Box_size(NPObject * self, SEL _cmd) {
    struct Box * _self = ((struct Box *)(self));
    {
        return 99;
    }
}

void Box_setSize_(NPObject * self, SEL _cmd, int s) {
    struct Box * _self = ((struct Box *)(self));
    {
        printf("setSize called with %d\n", s);
    }
}

NPClass * Box_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Box_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Box_class, __nupa_sel_alloc));
    Box * b = ((struct nupa_NPObject_vtable *)__nupa_tmp_0->isa->vtable)->init(__nupa_tmp_0, __nupa_sel_init);
    ((struct nupa_Box_vtable *)b->isa->vtable)->setSize_(b, __nupa_sel_setSize_, 42);
    printf("Size: %d\n", ((struct nupa_Box_vtable *)b->isa->vtable)->size(b, __nupa_sel_size));
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Box_vtable nupa_Box_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .size = Box_size,
    .setSize_ = Box_setSize_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Box_meta_vtable nupa_Box_meta_vtable_inst = {
    .class = Box_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Box_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Box_class = (NPClass){
        .name = "Box",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Box),
        .vtable = &nupa_Box_vtable_inst,
        .class_vtable = &nupa_Box_meta_vtable_inst,
        .protocol_count = 0,
    };
}
