// Generated by nupac
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <termios.h>
#include <unistd.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
struct nupa_vtable;
struct nupa_NPObject_meta_vtable;
struct nupa_JSON__Bool_meta_vtable;
struct nupa_JSON__Editor_meta_vtable;
struct nupa_JSON__Error_meta_vtable;
struct nupa_JSON__Null_meta_vtable;
struct nupa_JSON__Number_meta_vtable;
struct nupa_JSON__Object_meta_vtable;
struct nupa_JSON__Parser_meta_vtable;
struct nupa_JSON__String_meta_vtable;
struct nupa_Buffer_meta_vtable;
struct nupa_Watcher_meta_vtable;
struct nupa_JSON__Array_meta_vtable;

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nupa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nupa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nupa_sel_initWithMessage_ = {.name = "initWithMessage:", .hash = 0x0E8ADDA8};
static const SEL __nupa_sel_message = {.name = "message", .hash = 0x24F208E4};
static const SEL __nupa_sel_sharedNull = {.name = "sharedNull", .hash = 0x001694A1};
static const SEL __nupa_sel_initWithBool_ = {.name = "initWithBool:", .hash = 0xC668AD5F};
static const SEL __nupa_sel_value = {.name = "value", .hash = 0x425ED3CA};
static const SEL __nupa_sel_setValue_ = {.name = "setValue_", .hash = 0xA9DE6A6D};
static const SEL __nupa_sel_initWithDouble_ = {.name = "initWithDouble:", .hash = 0xF2F662D4};
static const SEL __nupa_sel_initWithInt_ = {.name = "initWithInt:", .hash = 0x521FA2AA};
static const SEL __nupa_sel_initWithString_ = {.name = "initWithString:", .hash = 0xB81658EC};
static const SEL __nupa_sel_count = {.name = "count", .hash = 0x39B1DDF4};
static const SEL __nupa_sel_at_ = {.name = "at:", .hash = 0xE1612736};
static const SEL __nupa_sel_add_ = {.name = "add:", .hash = 0x88D7D0CA};
static const SEL __nupa_sel_removeAt_ = {.name = "removeAt:", .hash = 0x88C7B5CE};
static const SEL __nupa_sel_each_ = {.name = "each:", .hash = 0x4F0B8F56};
static const SEL __nupa_sel_get_ = {.name = "get:", .hash = 0xBCEB9097};
static const SEL __nupa_sel_set_forKey_ = {.name = "set:forKey:", .hash = 0xB82ECF8D};
static const SEL __nupa_sel_remove_ = {.name = "remove:", .hash = 0x6DF84845};
static const SEL __nupa_sel_atKey_ = {.name = "atKey:", .hash = 0x0A62FDD7};
static const SEL __nupa_sel_atVal_ = {.name = "atVal:", .hash = 0xD36F53D7};
static const SEL __nupa_sel_parse_ = {.name = "parse:", .hash = 0x194A36E2};
static const SEL __nupa_sel_run = {.name = "run", .hash = 0x2ACD4ECA};
static const SEL __nupa_sel_push_ = {.name = "push:", .hash = 0x1C4FD8A5};
static const SEL __nupa_sel_initWithTarget_ = {.name = "initWithTarget:", .hash = 0xBE72A9EC};
static const SEL __nupa_sel_target = {.name = "target", .hash = 0x32608848};
static const SEL __nupa_sel_setTarget_ = {.name = "setTarget_", .hash = 0xE955D57B};
static const SEL __nupa_sel_typeName = {.name = "typeName", .hash = 0x9C504D6E};
static const SEL __nupa_sel_printOn_ = {.name = "printOn:", .hash = 0x36D822D1};
static const SEL __nupa_sel_copyValue = {.name = "copyValue", .hash = 0xD9B6303D};
static const SEL __nupa_sel_printKeys = {.name = "printKeys", .hash = 0x9868196C};
static const SEL __nupa_sel_refreshDisplay = {.name = "refreshDisplay", .hash = 0x161B1A7A};
static const SEL __nupa_sel_cmdPrint = {.name = "cmdPrint", .hash = 0x13C0DA7A};
static const SEL __nupa_sel_cmdSet_ = {.name = "cmdSet:", .hash = 0xA0636CF9};
static const SEL __nupa_sel_cmdGet_ = {.name = "cmdGet:", .hash = 0xCC455A2D};
static const SEL __nupa_sel_cmdDel_ = {.name = "cmdDel:", .hash = 0xE601CDA2};
static const SEL __nupa_sel_cmdKeys = {.name = "cmdKeys", .hash = 0x6F38E773};
static const SEL __nupa_sel_cmdType_ = {.name = "cmdType:", .hash = 0x68D8A04B};
static const SEL __nupa_sel_cmdLen = {.name = "cmdLen", .hash = 0x3139D4AA};
static const SEL __nupa_sel_cmdNew = {.name = "cmdNew", .hash = 0x71A9391B};
static const SEL __nupa_sel_cmdParse_ = {.name = "cmdParse:", .hash = 0x0E350D1C};
static const SEL __nupa_sel_cmdElist = {.name = "cmdElist", .hash = 0xCFB3CC26};
static const SEL __nupa_sel_cmdSels = {.name = "cmdSels", .hash = 0x579F2436};
static const SEL __nupa_sel_cmdHelp = {.name = "cmdHelp", .hash = 0x7EDE2BE8};
static const SEL __nupa_sel_cmdQuit = {.name = "cmdQuit", .hash = 0x094B4084};

#ifndef __NUPA_ROOT_DEFINED
#define __NUPA_ROOT_DEFINED
struct __nupa_root {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct __nupa_root __nupa_root;
#endif
#ifndef NPOBJECT_DEFINED
#define NPOBJECT_DEFINED
struct NPObject {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPObject NPObject;
#endif
struct JSON__Bool;
typedef struct JSON__Bool JSON__Bool;
struct JSON__Editor;
typedef struct JSON__Editor JSON__Editor;
struct JSON__Error;
typedef struct JSON__Error JSON__Error;
struct JSON__Null;
typedef struct JSON__Null JSON__Null;
struct JSON__Number;
typedef struct JSON__Number JSON__Number;
struct JSON__Object;
typedef struct JSON__Object JSON__Object;
struct JSON__Parser;
typedef struct JSON__Parser JSON__Parser;
struct JSON__String;
typedef struct JSON__String JSON__String;
struct Buffer;
typedef struct Buffer Buffer;
struct Watcher;
typedef struct Watcher Watcher;
struct JSON__Array;
typedef struct JSON__Array JSON__Array;

NPObject * __nupa_root_init(NPObject * self, SEL _cmd);
void __nupa_root_dealloc(NPObject * self, SEL _cmd);
void __nupa_root_release(NPObject * self, SEL _cmd);
NPObject * __nupa_root_retain(NPObject * self, SEL _cmd);
NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
NPObject * JSON__Error_initWithMessage_(NPObject * self, SEL _cmd, const char * msg);
const char * JSON__Error_message(NPObject * self, SEL _cmd);
void JSON__Error_dealloc(NPObject * self, SEL _cmd);
NPObject * JSON__Null_sharedNull(NPClass * self, SEL _cmd);
NPObject * JSON__Bool_initWithBool_(NPObject * self, SEL _cmd, _Bool val);
_Bool JSON__Bool_value(NPObject * self, SEL _cmd);
void JSON__Bool_setValue_(NPObject * self, SEL _cmd, _Bool value);
NPObject * JSON__Number_initWithDouble_(NPObject * self, SEL _cmd, double val);
NPObject * JSON__Number_initWithInt_(NPObject * self, SEL _cmd, int val);
double JSON__Number_value(NPObject * self, SEL _cmd);
void JSON__Number_setValue_(NPObject * self, SEL _cmd, double value);
NPObject * JSON__String_initWithString_(NPObject * self, SEL _cmd, const char * val);
void JSON__String_dealloc(NPObject * self, SEL _cmd);
const char * JSON__String_value(NPObject * self, SEL _cmd);
void JSON__String_setValue_(NPObject * self, SEL _cmd, const char * value);
NPObject * JSON__Array_init(NPObject * self, SEL _cmd);
void JSON__Array_dealloc(NPObject * self, SEL _cmd);
int JSON__Array_count(NPObject * self, SEL _cmd);
NPObject * JSON__Array_at_(NPObject * self, SEL _cmd, int idx);
void JSON__Array_add_(NPObject * self, SEL _cmd, NPObject * val);
void JSON__Array_removeAt_(NPObject * self, SEL _cmd, int idx);
void JSON__Array_each_(NPObject * self, SEL _cmd, void (^block)(int, NPObject *));
NPObject * JSON__Object_init(NPObject * self, SEL _cmd);
void JSON__Object_dealloc(NPObject * self, SEL _cmd);
int JSON__Object_count(NPObject * self, SEL _cmd);
NPObject * JSON__Object_get_(NPObject * self, SEL _cmd, const char * key);
void JSON__Object_set_forKey_(NPObject * self, SEL _cmd, NPObject * val, const char * key);
void JSON__Object_remove_(NPObject * self, SEL _cmd, const char * key);
const char * JSON__Object_atKey_(NPObject * self, SEL _cmd, int idx);
NPObject * JSON__Object_atVal_(NPObject * self, SEL _cmd, int idx);
void JSON__Object_each_(NPObject * self, SEL _cmd, void (^block)(int, NPObject *));
NPObject * JSON__Parser_parse_(NPClass * self, SEL _cmd, const char * input);
NPObject * JSON__Editor_init(NPObject * self, SEL _cmd);
void JSON__Editor_dealloc(NPObject * self, SEL _cmd);
void JSON__Editor_run(NPObject * self, SEL _cmd);
NPObject * Buffer_init(NPObject * self, SEL _cmd);
void Buffer_push_(NPObject * self, SEL _cmd, NPObject * item);
NPObject * Buffer_get_(NPObject * self, SEL _cmd, int index);
int Buffer_count(NPObject * self, SEL _cmd);
NPObject * Watcher_initWithTarget_(NPObject * self, SEL _cmd, NPObject * t);
NPObject * Watcher_target(NPObject * self, SEL _cmd);
void Watcher_setTarget_(NPObject * self, SEL _cmd, NPObject * value);
const char * JSON__Null_typeName(NPObject * self, SEL _cmd);
void JSON__Null_printOn_(NPObject * self, SEL _cmd, int indent);
NPObject * JSON__Null_copyValue(NPObject * self, SEL _cmd);
const char * JSON__Bool_typeName(NPObject * self, SEL _cmd);
void JSON__Bool_printOn_(NPObject * self, SEL _cmd, int indent);
NPObject * JSON__Bool_copyValue(NPObject * self, SEL _cmd);
const char * JSON__Number_typeName(NPObject * self, SEL _cmd);
void JSON__Number_printOn_(NPObject * self, SEL _cmd, int indent);
NPObject * JSON__Number_copyValue(NPObject * self, SEL _cmd);
const char * JSON__String_typeName(NPObject * self, SEL _cmd);
void JSON__String_printOn_(NPObject * self, SEL _cmd, int indent);
NPObject * JSON__String_copyValue(NPObject * self, SEL _cmd);
const char * JSON__Array_typeName(NPObject * self, SEL _cmd);
void JSON__Array_printOn_(NPObject * self, SEL _cmd, int indent);
NPObject * JSON__Array_copyValue(NPObject * self, SEL _cmd);
const char * JSON__Object_typeName(NPObject * self, SEL _cmd);
void JSON__Object_printOn_(NPObject * self, SEL _cmd, int indent);
NPObject * JSON__Object_copyValue(NPObject * self, SEL _cmd);
void JSON__Object_printKeys(NPObject * self, SEL _cmd);
void JSON__Editor_refreshDisplay(NPObject * self, SEL _cmd);
void JSON__Editor_cmdPrint(NPObject * self, SEL _cmd);
void JSON__Editor_cmdSet_(NPObject * self, SEL _cmd, const char * arg);
void JSON__Editor_cmdGet_(NPObject * self, SEL _cmd, const char * arg);
void JSON__Editor_cmdDel_(NPObject * self, SEL _cmd, const char * arg);
void JSON__Editor_cmdKeys(NPObject * self, SEL _cmd);
void JSON__Editor_cmdType_(NPObject * self, SEL _cmd, const char * arg);
void JSON__Editor_cmdLen(NPObject * self, SEL _cmd);
void JSON__Editor_cmdNew(NPObject * self, SEL _cmd);
void JSON__Editor_cmdParse_(NPObject * self, SEL _cmd, const char * arg);
void JSON__Editor_cmdElist(NPObject * self, SEL _cmd);
void JSON__Editor_cmdSels(NPObject * self, SEL _cmd);
void JSON__Editor_cmdHelp(NPObject * self, SEL _cmd);
void JSON__Editor_cmdQuit(NPObject * self, SEL _cmd);
void Watcher_dealloc(NPObject * self, SEL _cmd);
NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * self);
void nupa_release(NPObject * obj);
NPObject * nupa_retain(NPObject * obj);
int read_line(char * buf, int size);
void skip_ws(const char * * p);
int parse_hex4(const char * * p);
char * parse_raw_string(const char * * p);
NPObject * json_parse_value(const char * * p);
void THROW(const char * msg);
NPObject * json_parse_null(const char * * p);
NPObject * json_parse_true(const char * * p);
NPObject * json_parse_false(const char * * p);
NPObject * json_parse_number(const char * * p);
NPObject * json_parse_string(const char * * p);
NPObject * json_parse_array(const char * * p);
NPObject * json_parse_object(const char * * p);
NPObject * json_parse_value(const char * * p);
void cmdHelpPrint(void );
void cmdHelpSet(void );
void cmdHelpGet(void );
void cmdHelpDel(void );
void cmdHelpKeys(void );
void cmdHelpType(void );
void cmdHelpLen(void );
void cmdHelpNew(void );
void cmdHelpParse(void );
void cmdHelpElist(void );
void cmdHelpSel(void );
void cmdHelpHelp(void );
void cmdHelpQuit(void );
SEL cmdSel(const char * name);
int main(int argc, const char * argv[]);

static JSON__Null * s_sharedNull = NULL;

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Bool_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Editor_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Error_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Null_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Number_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Object_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Parser_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__String_getClass(NPClass * self, SEL _cmd);
NPClass * Buffer_getClass(NPClass * self, SEL _cmd);
NPClass * Watcher_getClass(NPClass * self, SEL _cmd);
NPClass * JSON__Array_getClass(NPClass * self, SEL _cmd);

struct nupa_vtable {
    void (*add_)(NPObject *, SEL, NPObject *);
    const char * (*atKey_)(NPObject *, SEL, int);
    NPObject * (*atVal_)(NPObject *, SEL, int);
    NPObject * (*at_)(NPObject *, SEL, int);
    void (*cmdDel_)(NPObject *, SEL, const char *);
    void (*cmdElist)(NPObject *, SEL);
    void (*cmdGet_)(NPObject *, SEL, const char *);
    void (*cmdHelp)(NPObject *, SEL);
    void (*cmdKeys)(NPObject *, SEL);
    void (*cmdLen)(NPObject *, SEL);
    void (*cmdNew)(NPObject *, SEL);
    void (*cmdParse_)(NPObject *, SEL, const char *);
    void (*cmdPrint)(NPObject *, SEL);
    void (*cmdQuit)(NPObject *, SEL);
    void (*cmdSels)(NPObject *, SEL);
    void (*cmdSet_)(NPObject *, SEL, const char *);
    void (*cmdType_)(NPObject *, SEL, const char *);
    NPObject * (*copyValue)(NPObject *, SEL);
    int (*count)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*each_)(NPObject *, SEL, void (^)(int, NPObject *));
    NPObject * (*get_)(NPObject *, SEL, const char *);
    NPObject * (*init)(NPObject *, SEL);
    NPObject * (*initWithBool_)(NPObject *, SEL, _Bool);
    NPObject * (*initWithDouble_)(NPObject *, SEL, double);
    NPObject * (*initWithInt_)(NPObject *, SEL, int);
    NPObject * (*initWithMessage_)(NPObject *, SEL, const char *);
    NPObject * (*initWithString_)(NPObject *, SEL, const char *);
    NPObject * (*initWithTarget_)(NPObject *, SEL, NPObject *);
    const char * (*message)(NPObject *, SEL);
    void (*printKeys)(NPObject *, SEL);
    void (*printOn_)(NPObject *, SEL, int);
    void (*push_)(NPObject *, SEL, NPObject *);
    void (*refreshDisplay)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    void (*removeAt_)(NPObject *, SEL, int);
    void (*remove_)(NPObject *, SEL, const char *);
    NPObject * (*retain)(NPObject *, SEL);
    void (*run)(NPObject *, SEL);
    void (*setTarget_)(NPObject *, SEL, NPObject *);
    void (*setValue_)(NPObject *, SEL, _Bool);
    void (*set_forKey_)(NPObject *, SEL, NPObject *, const char *);
    NPObject * (*target)(NPObject *, SEL);
    const char * (*typeName)(NPObject *, SEL);
    _Bool (*value)(NPObject *, SEL);
};

struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Bool_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Editor_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Error_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Null_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPObject * (*sharedNull)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Number_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Object_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Parser_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPObject * (*parse_)(NPClass *, SEL, const char *);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__String_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Buffer_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Watcher_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_JSON__Array_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct JSON__Bool {
    struct NPClass *isa;
    uint32_t retain_count;
    _Bool _value;
};
typedef struct JSON__Bool JSON__Bool;

struct JSON__Editor {
    struct NPClass *isa;
    uint32_t retain_count;
    NPObject * _root;
    _Bool _running;
    char _inputBuf[4096];
};
typedef struct JSON__Editor JSON__Editor;

struct JSON__Error {
    struct NPClass *isa;
    uint32_t retain_count;
    char * _message;
};
typedef struct JSON__Error JSON__Error;

struct JSON__Null {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct JSON__Null JSON__Null;

struct JSON__Number {
    struct NPClass *isa;
    uint32_t retain_count;
    double _value;
};
typedef struct JSON__Number JSON__Number;

struct JSON__Object {
    struct NPClass *isa;
    uint32_t retain_count;
    char * * _keys;
    NPObject * * _values;
    int _count;
    int _capacity;
};
typedef struct JSON__Object JSON__Object;

struct JSON__Parser {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct JSON__Parser JSON__Parser;

struct JSON__String {
    struct NPClass *isa;
    uint32_t retain_count;
    char * _value;
};
typedef struct JSON__String JSON__String;

struct Buffer {
    struct NPClass *isa;
    uint32_t retain_count;
    NPObject * _storage[16];
    int _count;
};
typedef struct Buffer Buffer;

struct Watcher {
    struct NPClass *isa;
    uint32_t retain_count;
    NPObject * _target;
};
typedef struct Watcher Watcher;

struct JSON__Array {
    struct NPClass *isa;
    uint32_t retain_count;
    NPObject * * _items;
    int _count;
    int _capacity;
};
typedef struct JSON__Array JSON__Array;

extern NPClass nupa___nupa_root_class;
extern NPClass nupa_NPObject_class;
extern NPClass nupa_JSON__Bool_class;
extern NPClass nupa_JSON__Editor_class;
extern NPClass nupa_JSON__Error_class;
extern NPClass nupa_JSON__Null_class;
extern NPClass nupa_JSON__Number_class;
extern NPClass nupa_JSON__Object_class;
extern NPClass nupa_JSON__Parser_class;
extern NPClass nupa_JSON__String_class;
extern NPClass nupa_Buffer_class;
extern NPClass nupa_Watcher_class;
extern NPClass nupa_JSON__Array_class;
void nupa_meta_init(void);

struct nupa_vtable nupa___nupa_root_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = NULL,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))__nupa_root_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))__nupa_root_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))__nupa_root_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))__nupa_root_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_NPObject_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = NULL,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__Bool_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = (NPObject * (*)(NPObject *, SEL))JSON__Bool_copyValue,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = (NPObject * (*)(NPObject *, SEL, _Bool))JSON__Bool_initWithBool_,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = (void (*)(NPObject *, SEL, int))JSON__Bool_printOn_,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = (void (*)(NPObject *, SEL, _Bool))JSON__Bool_setValue_,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = (const char * (*)(NPObject *, SEL))JSON__Bool_typeName,
    .value = (_Bool (*)(NPObject *, SEL))JSON__Bool_value,
};

struct nupa_vtable nupa_JSON__Editor_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = (void (*)(NPObject *, SEL, const char *))JSON__Editor_cmdDel_,
    .cmdElist = (void (*)(NPObject *, SEL))JSON__Editor_cmdElist,
    .cmdGet_ = (void (*)(NPObject *, SEL, const char *))JSON__Editor_cmdGet_,
    .cmdHelp = (void (*)(NPObject *, SEL))JSON__Editor_cmdHelp,
    .cmdKeys = (void (*)(NPObject *, SEL))JSON__Editor_cmdKeys,
    .cmdLen = (void (*)(NPObject *, SEL))JSON__Editor_cmdLen,
    .cmdNew = (void (*)(NPObject *, SEL))JSON__Editor_cmdNew,
    .cmdParse_ = (void (*)(NPObject *, SEL, const char *))JSON__Editor_cmdParse_,
    .cmdPrint = (void (*)(NPObject *, SEL))JSON__Editor_cmdPrint,
    .cmdQuit = (void (*)(NPObject *, SEL))JSON__Editor_cmdQuit,
    .cmdSels = (void (*)(NPObject *, SEL))JSON__Editor_cmdSels,
    .cmdSet_ = (void (*)(NPObject *, SEL, const char *))JSON__Editor_cmdSet_,
    .cmdType_ = (void (*)(NPObject *, SEL, const char *))JSON__Editor_cmdType_,
    .copyValue = NULL,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))JSON__Editor_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))JSON__Editor_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = NULL,
    .refreshDisplay = (void (*)(NPObject *, SEL))JSON__Editor_refreshDisplay,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = (void (*)(NPObject *, SEL))JSON__Editor_run,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__Error_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = NULL,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))JSON__Error_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = (NPObject * (*)(NPObject *, SEL, const char *))JSON__Error_initWithMessage_,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = (const char * (*)(NPObject *, SEL))JSON__Error_message,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__Null_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = (NPObject * (*)(NPObject *, SEL))JSON__Null_copyValue,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = (void (*)(NPObject *, SEL, int))JSON__Null_printOn_,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = (const char * (*)(NPObject *, SEL))JSON__Null_typeName,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__Number_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = (NPObject * (*)(NPObject *, SEL))JSON__Number_copyValue,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = (NPObject * (*)(NPObject *, SEL, double))JSON__Number_initWithDouble_,
    .initWithInt_ = (NPObject * (*)(NPObject *, SEL, int))JSON__Number_initWithInt_,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = (void (*)(NPObject *, SEL, int))JSON__Number_printOn_,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = (void (*)(NPObject *, SEL, _Bool))JSON__Number_setValue_,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = (const char * (*)(NPObject *, SEL))JSON__Number_typeName,
    .value = (_Bool (*)(NPObject *, SEL))JSON__Number_value,
};

struct nupa_vtable nupa_JSON__Object_vtable_inst = {
    .add_ = NULL,
    .atKey_ = (const char * (*)(NPObject *, SEL, int))JSON__Object_atKey_,
    .atVal_ = (NPObject * (*)(NPObject *, SEL, int))JSON__Object_atVal_,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = (NPObject * (*)(NPObject *, SEL))JSON__Object_copyValue,
    .count = (int (*)(NPObject *, SEL))JSON__Object_count,
    .dealloc = (void (*)(NPObject *, SEL))JSON__Object_dealloc,
    .each_ = (void (*)(NPObject *, SEL, void (^)(int, NPObject *)))JSON__Object_each_,
    .get_ = (NPObject * (*)(NPObject *, SEL, const char *))JSON__Object_get_,
    .init = (NPObject * (*)(NPObject *, SEL))JSON__Object_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = (void (*)(NPObject *, SEL))JSON__Object_printKeys,
    .printOn_ = (void (*)(NPObject *, SEL, int))JSON__Object_printOn_,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = (void (*)(NPObject *, SEL, const char *))JSON__Object_remove_,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = (void (*)(NPObject *, SEL, NPObject *, const char *))JSON__Object_set_forKey_,
    .target = NULL,
    .typeName = (const char * (*)(NPObject *, SEL))JSON__Object_typeName,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__Parser_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = NULL,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__String_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = (NPObject * (*)(NPObject *, SEL))JSON__String_copyValue,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))JSON__String_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = (NPObject * (*)(NPObject *, SEL, const char *))JSON__String_initWithString_,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = (void (*)(NPObject *, SEL, int))JSON__String_printOn_,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = (void (*)(NPObject *, SEL, _Bool))JSON__String_setValue_,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = (const char * (*)(NPObject *, SEL))JSON__String_typeName,
    .value = (_Bool (*)(NPObject *, SEL))JSON__String_value,
};

struct nupa_vtable nupa_Buffer_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = NULL,
    .count = (int (*)(NPObject *, SEL))Buffer_count,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .each_ = NULL,
    .get_ = (NPObject * (*)(NPObject *, SEL, const char *))Buffer_get_,
    .init = (NPObject * (*)(NPObject *, SEL))Buffer_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = (void (*)(NPObject *, SEL, NPObject *))Buffer_push_,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_Watcher_vtable_inst = {
    .add_ = NULL,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = NULL,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = NULL,
    .count = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Watcher_dealloc,
    .each_ = NULL,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = (NPObject * (*)(NPObject *, SEL, NPObject *))Watcher_initWithTarget_,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = NULL,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = NULL,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = (void (*)(NPObject *, SEL, NPObject *))Watcher_setTarget_,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = (NPObject * (*)(NPObject *, SEL))Watcher_target,
    .typeName = NULL,
    .value = NULL,
};

struct nupa_vtable nupa_JSON__Array_vtable_inst = {
    .add_ = (void (*)(NPObject *, SEL, NPObject *))JSON__Array_add_,
    .atKey_ = NULL,
    .atVal_ = NULL,
    .at_ = (NPObject * (*)(NPObject *, SEL, int))JSON__Array_at_,
    .cmdDel_ = NULL,
    .cmdElist = NULL,
    .cmdGet_ = NULL,
    .cmdHelp = NULL,
    .cmdKeys = NULL,
    .cmdLen = NULL,
    .cmdNew = NULL,
    .cmdParse_ = NULL,
    .cmdPrint = NULL,
    .cmdQuit = NULL,
    .cmdSels = NULL,
    .cmdSet_ = NULL,
    .cmdType_ = NULL,
    .copyValue = (NPObject * (*)(NPObject *, SEL))JSON__Array_copyValue,
    .count = (int (*)(NPObject *, SEL))JSON__Array_count,
    .dealloc = (void (*)(NPObject *, SEL))JSON__Array_dealloc,
    .each_ = (void (*)(NPObject *, SEL, void (^)(int, NPObject *)))JSON__Array_each_,
    .get_ = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))JSON__Array_init,
    .initWithBool_ = NULL,
    .initWithDouble_ = NULL,
    .initWithInt_ = NULL,
    .initWithMessage_ = NULL,
    .initWithString_ = NULL,
    .initWithTarget_ = NULL,
    .message = NULL,
    .printKeys = NULL,
    .printOn_ = (void (*)(NPObject *, SEL, int))JSON__Array_printOn_,
    .push_ = NULL,
    .refreshDisplay = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .removeAt_ = (void (*)(NPObject *, SEL, int))JSON__Array_removeAt_,
    .remove_ = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .run = NULL,
    .setTarget_ = NULL,
    .setValue_ = NULL,
    .set_forKey_ = NULL,
    .target = NULL,
    .typeName = (const char * (*)(NPObject *, SEL))JSON__Array_typeName,
    .value = NULL,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_JSON__Bool_meta_vtable nupa_JSON__Bool_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__Bool_getClass,
};

struct nupa_JSON__Editor_meta_vtable nupa_JSON__Editor_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__Editor_getClass,
};

struct nupa_JSON__Error_meta_vtable nupa_JSON__Error_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__Error_getClass,
};

struct nupa_JSON__Null_meta_vtable nupa_JSON__Null_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .sharedNull = JSON__Null_sharedNull,
    .class = JSON__Null_getClass,
};

struct nupa_JSON__Number_meta_vtable nupa_JSON__Number_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__Number_getClass,
};

struct nupa_JSON__Object_meta_vtable nupa_JSON__Object_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__Object_getClass,
};

struct nupa_JSON__Parser_meta_vtable nupa_JSON__Parser_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .parse_ = JSON__Parser_parse_,
    .class = JSON__Parser_getClass,
};

struct nupa_JSON__String_meta_vtable nupa_JSON__String_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__String_getClass,
};

struct nupa_Buffer_meta_vtable nupa_Buffer_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Buffer_getClass,
};

struct nupa_Watcher_meta_vtable nupa_Watcher_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Watcher_getClass,
};

struct nupa_JSON__Array_meta_vtable nupa_JSON__Array_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = JSON__Array_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Bool_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Editor_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Error_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Null_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Number_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Object_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Parser_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__String_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Buffer_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Watcher_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * JSON__Array_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nupa___nupa_root_class;
NPClass nupa_NPObject_class;
NPClass nupa_JSON__Bool_class;
NPClass nupa_JSON__Editor_class;
NPClass nupa_JSON__Error_class;
NPClass nupa_JSON__Null_class;
NPClass nupa_JSON__Number_class;
NPClass nupa_JSON__Object_class;
NPClass nupa_JSON__Parser_class;
NPClass nupa_JSON__String_class;
NPClass nupa_Buffer_class;
NPClass nupa_Watcher_class;
NPClass nupa_JSON__Array_class;

void nupa_meta_init(void) {
    nupa___nupa_root_class = (NPClass){
        .name = "__nupa_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __nupa_root),
        .vtable = &nupa___nupa_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = &nupa___nupa_root_class,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Bool_class = (NPClass){
        .name = "JSON::Bool",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Bool),
        .vtable = &nupa_JSON__Bool_vtable_inst,
        .class_vtable = &nupa_JSON__Bool_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Editor_class = (NPClass){
        .name = "JSON::Editor",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Editor),
        .vtable = &nupa_JSON__Editor_vtable_inst,
        .class_vtable = &nupa_JSON__Editor_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Error_class = (NPClass){
        .name = "JSON::Error",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Error),
        .vtable = &nupa_JSON__Error_vtable_inst,
        .class_vtable = &nupa_JSON__Error_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Null_class = (NPClass){
        .name = "JSON::Null",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Null),
        .vtable = &nupa_JSON__Null_vtable_inst,
        .class_vtable = &nupa_JSON__Null_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Number_class = (NPClass){
        .name = "JSON::Number",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Number),
        .vtable = &nupa_JSON__Number_vtable_inst,
        .class_vtable = &nupa_JSON__Number_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Object_class = (NPClass){
        .name = "JSON::Object",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Object),
        .vtable = &nupa_JSON__Object_vtable_inst,
        .class_vtable = &nupa_JSON__Object_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Parser_class = (NPClass){
        .name = "JSON::Parser",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Parser),
        .vtable = &nupa_JSON__Parser_vtable_inst,
        .class_vtable = &nupa_JSON__Parser_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__String_class = (NPClass){
        .name = "JSON::String",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__String),
        .vtable = &nupa_JSON__String_vtable_inst,
        .class_vtable = &nupa_JSON__String_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Buffer_class = (NPClass){
        .name = "Buffer",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Buffer),
        .vtable = &nupa_Buffer_vtable_inst,
        .class_vtable = &nupa_Buffer_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Watcher_class = (NPClass){
        .name = "Watcher",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Watcher),
        .vtable = &nupa_Watcher_vtable_inst,
        .class_vtable = &nupa_Watcher_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_JSON__Array_class = (NPClass){
        .name = "JSON::Array",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct JSON__Array),
        .vtable = &nupa_JSON__Array_vtable_inst,
        .class_vtable = &nupa_JSON__Array_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * __nupa_root_init(NPObject * self, SEL _cmd) {
  return nupa_init(self);
}

void __nupa_root_dealloc(NPObject * self, SEL _cmd) {
  return;
}

void __nupa_root_release(NPObject * self, SEL _cmd) {
  nupa_release(self);
}

NPObject * __nupa_root_retain(NPObject * self, SEL _cmd) {
  return nupa_retain(self);
}

NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = nupa_alloc(self);
  return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  return nupa_init(self);
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  return;
}

void NPObject_release(NPObject * self, SEL _cmd) {
  nupa_release(self);
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  return nupa_retain(self);
}

NPObject * JSON__Error_initWithMessage_(NPObject * self, SEL _cmd, const char * msg) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct JSON__Error *)self)->_message = (char *)(strdup(msg));
  }
  return self;
}

const char * JSON__Error_message(NPObject * self, SEL _cmd) {
  return ((struct JSON__Error *)self)->_message;
}

void JSON__Error_dealloc(NPObject * self, SEL _cmd) {
  free(((struct JSON__Error *)self)->_message);
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

NPObject * JSON__Null_sharedNull(NPClass * self, SEL _cmd) {
  if (!s_sharedNull)   s_sharedNull = ({ NPObject *__nupa_tmp_1 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Null_class, __nupa_sel_alloc))); __nupa_tmp_1 ? ((struct nupa_vtable *)__nupa_tmp_1->isa->vtable)->init(__nupa_tmp_1, __nupa_sel_init) : 0; });
  return s_sharedNull;
}

NPObject * JSON__Bool_initWithBool_(NPObject * self, SEL _cmd, _Bool val) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   ((struct JSON__Bool *)self)->_value = val;
  return self;
}

_Bool JSON__Bool_value(NPObject * self, SEL _cmd) {
  return ((struct JSON__Bool *)self)->_value;
}

void JSON__Bool_setValue_(NPObject * self, SEL _cmd, _Bool value) {
  ((struct JSON__Bool *)self)->_value = value;
}

NPObject * JSON__Number_initWithDouble_(NPObject * self, SEL _cmd, double val) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   ((struct JSON__Number *)self)->_value = val;
  return self;
}

NPObject * JSON__Number_initWithInt_(NPObject * self, SEL _cmd, int val) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   ((struct JSON__Number *)self)->_value = (double)val;
  return self;
}

double JSON__Number_value(NPObject * self, SEL _cmd) {
  return ((struct JSON__Number *)self)->_value;
}

void JSON__Number_setValue_(NPObject * self, SEL _cmd, double value) {
  ((struct JSON__Number *)self)->_value = value;
}

NPObject * JSON__String_initWithString_(NPObject * self, SEL _cmd, const char * val) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   ((struct JSON__String *)self)->_value = val ? strdup(val) : strdup("");
  return self;
}

void JSON__String_dealloc(NPObject * self, SEL _cmd) {
  free(((struct JSON__String *)self)->_value);
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

const char * JSON__String_value(NPObject * self, SEL _cmd) {
  return ((struct JSON__String *)self)->_value;
}

void JSON__String_setValue_(NPObject * self, SEL _cmd, const char * value) {
  ((struct JSON__String *)self)->_value = value;
}

NPObject * JSON__Array_init(NPObject * self, SEL _cmd) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct JSON__Array *)self)->_capacity = 4;
    ((struct JSON__Array *)self)->_count = 0;
    ((struct JSON__Array *)self)->_items = (NPObject * *)malloc((((struct JSON__Array *)self)->_capacity * sizeof(NPObject *)));
  }
  return self;
}

void JSON__Array_dealloc(NPObject * self, SEL _cmd) {
  for (int i = 0;
(i < ((struct JSON__Array *)self)->_count); (i)++)   ({ NPObject *__nupa_tmp_2 = ((NPObject *)(((struct JSON__Array *)self)->_items[i])); __nupa_tmp_2 ? ((struct nupa_vtable *)__nupa_tmp_2->isa->vtable)->release(__nupa_tmp_2, __nupa_sel_release) : 0; });
  free(((struct JSON__Array *)self)->_items);
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

int JSON__Array_count(NPObject * self, SEL _cmd) {
  return ((struct JSON__Array *)self)->_count;
}

NPObject * JSON__Array_at_(NPObject * self, SEL _cmd, int idx) {
  return ((idx >= 0) && (idx < ((struct JSON__Array *)self)->_count)) ? ((struct JSON__Array *)self)->_items[idx] : NULL;
}

void JSON__Array_add_(NPObject * self, SEL _cmd, NPObject * val) {
  if (!val)   return;
  if ((((struct JSON__Array *)self)->_count >= ((struct JSON__Array *)self)->_capacity))   {
    (((struct JSON__Array *)self)->_capacity *= 2);
    ((struct JSON__Array *)self)->_items = (NPObject * *)realloc(((struct JSON__Array *)self)->_items, (((struct JSON__Array *)self)->_capacity * sizeof(NPObject *)));
  }
  ((struct JSON__Array *)self)->_items[(((struct JSON__Array *)self)->_count)++] = val;
  ((struct nupa_vtable *)(val->isa->vtable))->retain((NPObject *)(val), __nupa_sel_retain);
}

void JSON__Array_removeAt_(NPObject * self, SEL _cmd, int idx) {
  if (((idx < 0) || (idx >= ((struct JSON__Array *)self)->_count)))   return;
  ({ NPObject *__nupa_tmp_3 = ((NPObject *)(((struct JSON__Array *)self)->_items[idx])); __nupa_tmp_3 ? ((struct nupa_vtable *)__nupa_tmp_3->isa->vtable)->release(__nupa_tmp_3, __nupa_sel_release) : 0; });
  memmove(&((struct JSON__Array *)self)->_items[idx], &((struct JSON__Array *)self)->_items[(idx + 1)], (((((struct JSON__Array *)self)->_count - idx) - 1) * sizeof(NPObject *)));
  (((struct JSON__Array *)self)->_count)--;
}

void JSON__Array_each_(NPObject * self, SEL _cmd, void (^block)(int, NPObject *)) {
  if (!block)   return;
  for (int i = 0;
(i < ((struct JSON__Array *)self)->_count); (i)++)   block(i, ((struct JSON__Array *)self)->_items[i]);
}

NPObject * JSON__Object_init(NPObject * self, SEL _cmd) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct JSON__Object *)self)->_capacity = 4;
    ((struct JSON__Object *)self)->_count = 0;
    ((struct JSON__Object *)self)->_keys = (char * *)malloc((((struct JSON__Object *)self)->_capacity * sizeof(char *)));
    ((struct JSON__Object *)self)->_values = (NPObject * *)malloc((((struct JSON__Object *)self)->_capacity * sizeof(NPObject *)));
  }
  return self;
}

void JSON__Object_dealloc(NPObject * self, SEL _cmd) {
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    free(((struct JSON__Object *)self)->_keys[i]);
    ({ NPObject *__nupa_tmp_4 = ((NPObject *)(((struct JSON__Object *)self)->_values[i])); __nupa_tmp_4 ? ((struct nupa_vtable *)__nupa_tmp_4->isa->vtable)->release(__nupa_tmp_4, __nupa_sel_release) : 0; });
  }
  free(((struct JSON__Object *)self)->_keys);
  free(((struct JSON__Object *)self)->_values);
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

int JSON__Object_count(NPObject * self, SEL _cmd) {
  return ((struct JSON__Object *)self)->_count;
}

NPObject * JSON__Object_get_(NPObject * self, SEL _cmd, const char * key) {
  if (!key)   return NULL;
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    if (strcmp(((struct JSON__Object *)self)->_keys[i], key) == 0)     return ((struct JSON__Object *)self)->_values[i];
  }
  return NULL;
}

void JSON__Object_set_forKey_(NPObject * self, SEL _cmd, NPObject * val, const char * key) {
  if ((!key || !val))   return;
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    if (strcmp(((struct JSON__Object *)self)->_keys[i], key) == 0)     {
      ({ NPObject *__nupa_tmp_5 = ((NPObject *)(((struct JSON__Object *)self)->_values[i])); __nupa_tmp_5 ? ((struct nupa_vtable *)__nupa_tmp_5->isa->vtable)->release(__nupa_tmp_5, __nupa_sel_release) : 0; });
      ((struct JSON__Object *)self)->_values[i] = val;
      ((struct nupa_vtable *)(val->isa->vtable))->retain((NPObject *)(val), __nupa_sel_retain);
      return;
    }
  }
  if ((((struct JSON__Object *)self)->_count >= ((struct JSON__Object *)self)->_capacity))   {
    (((struct JSON__Object *)self)->_capacity *= 2);
    ((struct JSON__Object *)self)->_keys = (char * *)realloc(((struct JSON__Object *)self)->_keys, (((struct JSON__Object *)self)->_capacity * sizeof(char *)));
    ((struct JSON__Object *)self)->_values = (NPObject * *)realloc(((struct JSON__Object *)self)->_values, (((struct JSON__Object *)self)->_capacity * sizeof(NPObject *)));
  }
  ((struct JSON__Object *)self)->_keys[((struct JSON__Object *)self)->_count] = strdup(key);
  ((struct JSON__Object *)self)->_values[((struct JSON__Object *)self)->_count] = val;
  ((struct nupa_vtable *)(val->isa->vtable))->retain((NPObject *)(val), __nupa_sel_retain);
  (((struct JSON__Object *)self)->_count)++;
}

void JSON__Object_remove_(NPObject * self, SEL _cmd, const char * key) {
  if (!key)   return;
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    if (strcmp(((struct JSON__Object *)self)->_keys[i], key) == 0)     {
      free(((struct JSON__Object *)self)->_keys[i]);
      ({ NPObject *__nupa_tmp_6 = ((NPObject *)(((struct JSON__Object *)self)->_values[i])); __nupa_tmp_6 ? ((struct nupa_vtable *)__nupa_tmp_6->isa->vtable)->release(__nupa_tmp_6, __nupa_sel_release) : 0; });
      (((struct JSON__Object *)self)->_count)--;
      if ((i < ((struct JSON__Object *)self)->_count))       {
        ((struct JSON__Object *)self)->_keys[i] = ((struct JSON__Object *)self)->_keys[((struct JSON__Object *)self)->_count];
        ((struct JSON__Object *)self)->_values[i] = ((struct JSON__Object *)self)->_values[((struct JSON__Object *)self)->_count];
      }
      return;
    }
  }
}

const char * JSON__Object_atKey_(NPObject * self, SEL _cmd, int idx) {
  return ((idx >= 0) && (idx < ((struct JSON__Object *)self)->_count)) ? ((struct JSON__Object *)self)->_keys[idx] : NULL;
}

NPObject * JSON__Object_atVal_(NPObject * self, SEL _cmd, int idx) {
  return ((idx >= 0) && (idx < ((struct JSON__Object *)self)->_count)) ? ((struct JSON__Object *)self)->_values[idx] : NULL;
}

void JSON__Object_each_(NPObject * self, SEL _cmd, void (^block)(int, NPObject *)) {
  if (!block)   return;
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   block(i, ((struct JSON__Object *)self)->_values[i]);
}

NPObject * JSON__Parser_parse_(NPClass * self, SEL _cmd, const char * input) {
  if ((!input || !*input))   THROW("Empty input");
  char * p = input;
  NPObject * result = json_parse_value(&p);
  if (!result)   THROW("Failed to parse");
  skip_ws(&p);
  if (*p)   {
    ((struct nupa_vtable *)(result->isa->vtable))->release((NPObject *)(result), __nupa_sel_release);
    THROW("Trailing characters");
  }
  return result;
}

NPObject * JSON__Editor_init(NPObject * self, SEL _cmd) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct JSON__Editor *)self)->_root = ({ NPObject *__nupa_tmp_7 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Object_class, __nupa_sel_alloc))); __nupa_tmp_7 ? ((struct nupa_vtable *)__nupa_tmp_7->isa->vtable)->init(__nupa_tmp_7, __nupa_sel_init) : 0; });
    ((struct JSON__Editor *)self)->_running = 1;
  }
  return self;
}

void JSON__Editor_dealloc(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_8 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_8 ? ((struct nupa_vtable *)__nupa_tmp_8->isa->vtable)->release(__nupa_tmp_8, __nupa_sel_release) : 0; });
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

void JSON__Editor_run(NPObject * self, SEL _cmd) {
  ((struct nupa_vtable *)(self->isa->vtable))->refreshDisplay(self, __nupa_sel_refreshDisplay);
  while (((struct JSON__Editor *)self)->_running)   {
    if ((read_line(((struct JSON__Editor *)self)->_inputBuf, sizeof(((struct JSON__Editor *)self)->_inputBuf)) <= 0))     break;
    int len = (int)strlen(((struct JSON__Editor *)self)->_inputBuf);
    if (len == 0)     {
      ((struct nupa_vtable *)(self->isa->vtable))->refreshDisplay(self, __nupa_sel_refreshDisplay);
      continue;
    }
    char * cmd = ((struct JSON__Editor *)self)->_inputBuf;
    char * arg = "";
    for (int i = 0;
((struct JSON__Editor *)self)->_inputBuf[i]; (i)++)     {
      if (((struct JSON__Editor *)self)->_inputBuf[i] == ' ')       {
        ((struct JSON__Editor *)self)->_inputBuf[i] = '\x00';
        arg = ((((struct JSON__Editor *)self)->_inputBuf + i) + 1);
        break;
      }
    }
    {
      nupa_autoreleasepool_t * __nupa_pool = nupa_autoreleasepool_push();
      SEL sel = cmdSel(cmd);
      if (sel.name[0] == '\x00')       {
        printf("  Unknown: '%s'. Type 'help'.\n", cmd);
        printf("  Press Return to continue...");
        fflush(stdout);
        read_line(((struct JSON__Editor *)self)->_inputBuf, sizeof(((struct JSON__Editor *)self)->_inputBuf));
        ((struct nupa_vtable *)(self->isa->vtable))->refreshDisplay(self, __nupa_sel_refreshDisplay);
        continue;
      }
      char * sn = sel.name;
      if (strcmp(sn, "cmdPrint") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdPrint(self, __nupa_sel_cmdPrint);
      else       if (strcmp(sn, "cmdSet:") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdSet_(self, __nupa_sel_cmdSet_, arg);
      else       if (strcmp(sn, "cmdGet:") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdGet_(self, __nupa_sel_cmdGet_, arg);
      else       if (strcmp(sn, "cmdDel:") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdDel_(self, __nupa_sel_cmdDel_, arg);
      else       if (strcmp(sn, "cmdKeys") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdKeys(self, __nupa_sel_cmdKeys);
      else       if (strcmp(sn, "cmdType:") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdType_(self, __nupa_sel_cmdType_, arg);
      else       if (strcmp(sn, "cmdLen") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdLen(self, __nupa_sel_cmdLen);
      else       if (strcmp(sn, "cmdNew") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdNew(self, __nupa_sel_cmdNew);
      else       if (strcmp(sn, "cmdParse:") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdParse_(self, __nupa_sel_cmdParse_, arg);
      else       if (strcmp(sn, "cmdElist") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdElist(self, __nupa_sel_cmdElist);
      else       if (strcmp(sn, "cmdSels") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdSels(self, __nupa_sel_cmdSels);
      else       if (strcmp(sn, "cmdHelp") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdHelp(self, __nupa_sel_cmdHelp);
      else       if (strcmp(sn, "cmdQuit") == 0)       ((struct nupa_vtable *)(self->isa->vtable))->cmdQuit(self, __nupa_sel_cmdQuit);
      nupa_autoreleasepool_pop(__nupa_pool);
    }
    if (((struct JSON__Editor *)self)->_running)     {
      printf("  Press Return to continue...");
      fflush(stdout);
      read_line(((struct JSON__Editor *)self)->_inputBuf, sizeof(((struct JSON__Editor *)self)->_inputBuf));
      ((struct nupa_vtable *)(self->isa->vtable))->refreshDisplay(self, __nupa_sel_refreshDisplay);
    }
  }
}

NPObject * Buffer_init(NPObject * self, SEL _cmd) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   ((struct Buffer *)self)->_count = 0;
  return self;
}

void Buffer_push_(NPObject * self, SEL _cmd, NPObject * item) {
  if ((((struct Buffer *)self)->_count < 16))   ((struct Buffer *)self)->_storage[(((struct Buffer *)self)->_count)++] = item;
}

NPObject * Buffer_get_(NPObject * self, SEL _cmd, int index) {
  return ((index >= 0) && (index < ((struct Buffer *)self)->_count)) ? ((struct Buffer *)self)->_storage[index] : (NPObject *)0;
}

int Buffer_count(NPObject * self, SEL _cmd) {
  return ((struct Buffer *)self)->_count;
}

NPObject * Watcher_initWithTarget_(NPObject * self, SEL _cmd, NPObject * t) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   ((struct Watcher *)self)->_target = t;
  return self;
}

NPObject * Watcher_target(NPObject * self, SEL _cmd) {
  return ((struct Watcher *)self)->_target;
}

void Watcher_setTarget_(NPObject * self, SEL _cmd, NPObject * value) {
  nupa_weak_unregister((NPObject **)&((struct Watcher *)self)->_target);
  ((struct Watcher *)self)->_target = value;
  nupa_weak_register((NPObject **)&((struct Watcher *)self)->_target, (NPObject *)value);
}

const char * JSON__Null_typeName(NPObject * self, SEL _cmd) {
  return "null";
}

void JSON__Null_printOn_(NPObject * self, SEL _cmd, int indent) {
  printf("null");
}

NPObject * JSON__Null_copyValue(NPObject * self, SEL _cmd) {
  return JSON__Null_sharedNull(&nupa_JSON__Null_class, __nupa_sel_sharedNull);
}

const char * JSON__Bool_typeName(NPObject * self, SEL _cmd) {
  return "bool";
}

void JSON__Bool_printOn_(NPObject * self, SEL _cmd, int indent) {
  printf(((struct JSON__Bool *)self)->_value ? "true" : "false");
}

NPObject * JSON__Bool_copyValue(NPObject * self, SEL _cmd) {
  return ({ NPObject *__nupa_tmp_9 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Bool_class, __nupa_sel_alloc))); __nupa_tmp_9 ? ((struct nupa_vtable *)__nupa_tmp_9->isa->vtable)->initWithBool_(__nupa_tmp_9, __nupa_sel_initWithBool_, ((struct JSON__Bool *)self)->_value) : 0; });
}

const char * JSON__Number_typeName(NPObject * self, SEL _cmd) {
  return "number";
}

void JSON__Number_printOn_(NPObject * self, SEL _cmd, int indent) {
  if (((struct JSON__Number *)self)->_value == (double)(int)((struct JSON__Number *)self)->_value)   printf("%d", (int)((struct JSON__Number *)self)->_value);
  else   printf("%g", ((struct JSON__Number *)self)->_value);
}

NPObject * JSON__Number_copyValue(NPObject * self, SEL _cmd) {
  return ({ NPObject *__nupa_tmp_10 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Number_class, __nupa_sel_alloc))); __nupa_tmp_10 ? ((struct nupa_vtable *)__nupa_tmp_10->isa->vtable)->initWithDouble_(__nupa_tmp_10, __nupa_sel_initWithDouble_, ((struct JSON__Number *)self)->_value) : 0; });
}

const char * JSON__String_typeName(NPObject * self, SEL _cmd) {
  return "string";
}

void JSON__String_printOn_(NPObject * self, SEL _cmd, int indent) {
  printf("\"");
  for (char * p = ((struct JSON__String *)self)->_value;
*p; (p)++)   {
    switch (*p)     {
      case '\"':
        printf("\\\"");
      break;
      case '\\':
        printf("\\\\");
      break;
      case '\x08':
        printf("\\b");
      break;
      case '\x0C':
        printf("\\f");
      break;
      case '\n':
        printf("\\n");
      break;
      case '\r':
        printf("\\r");
      break;
      case '\t':
        printf("\\t");
      break;
      default:
        if (((unsigned char)*p < 32))         printf("\\u%04x", (unsigned char)*p);
        else         putchar(*p);
      break;
    }
  }
  printf("\"");
}

NPObject * JSON__String_copyValue(NPObject * self, SEL _cmd) {
  return ({ NPObject *__nupa_tmp_11 = ((NPObject *)(NPObject_alloc(&nupa_JSON__String_class, __nupa_sel_alloc))); __nupa_tmp_11 ? ((struct nupa_vtable *)__nupa_tmp_11->isa->vtable)->initWithString_(__nupa_tmp_11, __nupa_sel_initWithString_, ((struct JSON__String *)self)->_value) : 0; });
}

const char * JSON__Array_typeName(NPObject * self, SEL _cmd) {
  return "array";
}

void JSON__Array_printOn_(NPObject * self, SEL _cmd, int indent) {
  if (((struct JSON__Array *)self)->_count == 0)   {
    printf("[]");
    return;
  }
  printf("[\n");
  for (int i = 0;
(i < ((struct JSON__Array *)self)->_count); (i)++)   {
    for (int j = 0;
(j < (indent + 1)); (j)++)     printf("    ");
    ({ NPObject *__nupa_tmp_12 = ((NPObject *)(((struct JSON__Array *)self)->_items[i])); __nupa_tmp_12 ? ((struct nupa_vtable *)__nupa_tmp_12->isa->vtable)->printOn_(__nupa_tmp_12, __nupa_sel_printOn_, (indent + 1)) : 0; });
    if ((i < (((struct JSON__Array *)self)->_count - 1)))     printf(",");
    printf("\n");
  }
  for (int j = 0;
(j < indent); (j)++)   printf("    ");
  printf("]");
}

NPObject * JSON__Array_copyValue(NPObject * self, SEL _cmd) {
  NPObject *__nupa_tmp_13 = (NPObject_alloc(&nupa_JSON__Array_class, __nupa_sel_alloc));
  JSON__Array * c = (JSON__Array *)(((struct nupa_vtable *)__nupa_tmp_13->isa->vtable)->init(__nupa_tmp_13, __nupa_sel_init));
  for (int i = 0;
(i < ((struct JSON__Array *)self)->_count); (i)++)   {
    NPObject * v = ({ NPObject *__nupa_tmp_14 = ((NPObject *)(((struct JSON__Array *)self)->_items[i])); __nupa_tmp_14 ? ((struct nupa_vtable *)__nupa_tmp_14->isa->vtable)->copyValue(__nupa_tmp_14, __nupa_sel_copyValue) : 0; });
    ((struct nupa_vtable *)(c->isa->vtable))->add_((NPObject *)(c), __nupa_sel_add_, (NPObject *)(v));
    ((struct nupa_vtable *)(v->isa->vtable))->release((NPObject *)(v), __nupa_sel_release);
  }
  return c;
}

const char * JSON__Object_typeName(NPObject * self, SEL _cmd) {
  return "object";
}

void JSON__Object_printOn_(NPObject * self, SEL _cmd, int indent) {
  if (((struct JSON__Object *)self)->_count == 0)   {
    printf("{}");
    return;
  }
  printf("{\n");
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    for (int j = 0;
(j < (indent + 1)); (j)++)     printf("    ");
    printf("\"%s\": ", ((struct JSON__Object *)self)->_keys[i]);
    ({ NPObject *__nupa_tmp_15 = ((NPObject *)(((struct JSON__Object *)self)->_values[i])); __nupa_tmp_15 ? ((struct nupa_vtable *)__nupa_tmp_15->isa->vtable)->printOn_(__nupa_tmp_15, __nupa_sel_printOn_, (indent + 1)) : 0; });
    if ((i < (((struct JSON__Object *)self)->_count - 1)))     printf(",");
    printf("\n");
  }
  for (int j = 0;
(j < indent); (j)++)   printf("    ");
  printf("}");
}

NPObject * JSON__Object_copyValue(NPObject * self, SEL _cmd) {
  NPObject *__nupa_tmp_16 = (NPObject_alloc(&nupa_JSON__Object_class, __nupa_sel_alloc));
  JSON__Object * c = (JSON__Object *)(((struct nupa_vtable *)__nupa_tmp_16->isa->vtable)->init(__nupa_tmp_16, __nupa_sel_init));
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    NPObject * v = ({ NPObject *__nupa_tmp_17 = ((NPObject *)(((struct JSON__Object *)self)->_values[i])); __nupa_tmp_17 ? ((struct nupa_vtable *)__nupa_tmp_17->isa->vtable)->copyValue(__nupa_tmp_17, __nupa_sel_copyValue) : 0; });
    ((struct nupa_vtable *)(c->isa->vtable))->set_forKey_((NPObject *)(c), __nupa_sel_set_forKey_, (NPObject *)(v), ((struct JSON__Object *)self)->_keys[i]);
    ((struct nupa_vtable *)(v->isa->vtable))->release((NPObject *)(v), __nupa_sel_release);
  }
  return c;
}

void JSON__Object_printKeys(NPObject * self, SEL _cmd) {
  if (((struct JSON__Object *)self)->_count == 0)   {
    printf("(empty)\n");
    return;
  }
  for (int i = 0;
(i < ((struct JSON__Object *)self)->_count); (i)++)   {
    if ((i > 0))     printf(", ");
    printf("%s", ((struct JSON__Object *)self)->_keys[i]);
  }
  printf("\n");
}

void JSON__Editor_refreshDisplay(NPObject * self, SEL _cmd) {
  printf("\033[2J\033[H");
  printf("╔══════════════════════════════════════════════╗\n");
  printf("║  JSON Preview                                ║\n");
  printf("╚══════════════════════════════════════════════╝\n");
  ({ NPObject *__nupa_tmp_18 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_18 ? ((struct nupa_vtable *)__nupa_tmp_18->isa->vtable)->printOn_(__nupa_tmp_18, __nupa_sel_printOn_, 0) : 0; });
  printf("\n");
  printf("╔══════════════════════════════════════════════╗\n");
  printf("║  Command                                     ║\n");
  printf("╚══════════════════════════════════════════════╝\n");
  printf(">>> ");
  fflush(stdout);
}

void JSON__Editor_cmdPrint(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_19 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_19 ? ((struct nupa_vtable *)__nupa_tmp_19->isa->vtable)->printOn_(__nupa_tmp_19, __nupa_sel_printOn_, 0) : 0; });
  printf("\n");
}

void JSON__Editor_cmdSet_(NPObject * self, SEL _cmd, const char * arg) {
  if ((!arg || !*arg))   {
    printf("  Usage: set <key> <json>\n");
    return;
  }
  char * space = (char *)(strchr(arg, ' '));
  if (!space)   {
    printf("  Usage: set <key> <json>\n");
    return;
  }
  int klen = (int)(space - arg);
  char key[256];
  if ((klen >= 256))   klen = 255;
  strncpy(key, arg, klen);
  key[klen] = '\x00';
  {
    jmp_buf __nupa_saved;
    memcpy(__nupa_saved, __nupa_exception_buf, sizeof(jmp_buf));
    volatile int __nupa_state = 0;
    if (setjmp(__nupa_exception_buf) != 0)     __nupa_state = 1;
    if (__nupa_state == 0)     {
      NPObject * val = JSON__Parser_parse_(&nupa_JSON__Parser_class, __nupa_sel_parse_, (space + 1));
      ((struct nupa_vtable *)(val->isa->vtable))->retain((NPObject *)(val), __nupa_sel_retain);
      ({ NPObject *__nupa_tmp_20 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_20 ? ((struct nupa_vtable *)__nupa_tmp_20->isa->vtable)->set_forKey_(__nupa_tmp_20, __nupa_sel_set_forKey_, (NPObject *)(val), key) : 0; });
      printf("  OK: %s = ", key);
      ((struct nupa_vtable *)(val->isa->vtable))->printOn_((NPObject *)(val), __nupa_sel_printOn_, 0);
      printf("\n");
      ((struct nupa_vtable *)(val->isa->vtable))->release((NPObject *)(val), __nupa_sel_release);
    }
    if (__nupa_state == 1)     {
      __nupa_state = 2;
      JSON__Error * e = __nupa_exception_value;
      {
        printf("  Error: %s\n", ((struct nupa_vtable *)(e->isa->vtable))->message((NPObject *)(e), __nupa_sel_message));
        ((struct nupa_vtable *)(e->isa->vtable))->release((NPObject *)(e), __nupa_sel_release);
      }
    }
    memcpy(__nupa_exception_buf, __nupa_saved, sizeof(jmp_buf));
    if (__nupa_state == 1)     longjmp(__nupa_exception_buf, 1);
  }
}

void JSON__Editor_cmdGet_(NPObject * self, SEL _cmd, const char * arg) {
  if ((!arg || !*arg))   {
    printf("  Usage: get <key>\n");
    return;
  }
  NPObject * val = ({ NPObject *__nupa_tmp_21 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_21 ? ((struct nupa_vtable *)__nupa_tmp_21->isa->vtable)->get_(__nupa_tmp_21, __nupa_sel_get_, arg) : 0; });
  if (!val)   {
    printf("  Not found: '%s'\n", arg);
    return;
  }
  ((struct nupa_vtable *)(val->isa->vtable))->printOn_((NPObject *)(val), __nupa_sel_printOn_, 0);
  printf("\n");
}

void JSON__Editor_cmdDel_(NPObject * self, SEL _cmd, const char * arg) {
  if ((!arg || !*arg))   {
    printf("  Usage: del <key>\n");
    return;
  }
  ({ NPObject *__nupa_tmp_22 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_22 ? ((struct nupa_vtable *)__nupa_tmp_22->isa->vtable)->remove_(__nupa_tmp_22, __nupa_sel_remove_, arg) : 0; });
  printf("  Deleted '%s'\n", arg);
}

void JSON__Editor_cmdKeys(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_23 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_23 ? ((struct nupa_vtable *)__nupa_tmp_23->isa->vtable)->printKeys(__nupa_tmp_23, __nupa_sel_printKeys) : 0; });
}

void JSON__Editor_cmdType_(NPObject * self, SEL _cmd, const char * arg) {
  if ((!arg || !*arg))   {
    printf("  Root: %s\n", ({ NPObject *__nupa_tmp_24 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_24 ? ((struct nupa_vtable *)__nupa_tmp_24->isa->vtable)->typeName(__nupa_tmp_24, __nupa_sel_typeName) : 0; }));
    return;
  }
  NPObject * val = ({ NPObject *__nupa_tmp_25 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_25 ? ((struct nupa_vtable *)__nupa_tmp_25->isa->vtable)->get_(__nupa_tmp_25, __nupa_sel_get_, arg) : 0; });
  if (!val)   {
    printf("  Not found: '%s'\n", arg);
    return;
  }
  printf("  '%s': %s\n", arg, ((struct nupa_vtable *)(val->isa->vtable))->typeName((NPObject *)(val), __nupa_sel_typeName));
}

void JSON__Editor_cmdLen(NPObject * self, SEL _cmd) {
  printf("  Count: %d\n", ({ NPObject *__nupa_tmp_26 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_26 ? ((struct nupa_vtable *)__nupa_tmp_26->isa->vtable)->count(__nupa_tmp_26, __nupa_sel_count) : 0; }));
}

void JSON__Editor_cmdNew(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_27 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_27 ? ((struct nupa_vtable *)__nupa_tmp_27->isa->vtable)->release(__nupa_tmp_27, __nupa_sel_release) : 0; });
  ((struct JSON__Editor *)self)->_root = ({ NPObject *__nupa_tmp_28 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Object_class, __nupa_sel_alloc))); __nupa_tmp_28 ? ((struct nupa_vtable *)__nupa_tmp_28->isa->vtable)->init(__nupa_tmp_28, __nupa_sel_init) : 0; });
  printf("  New empty object.\n");
}

void JSON__Editor_cmdParse_(NPObject * self, SEL _cmd, const char * arg) {
  if ((!arg || !*arg))   {
    printf("  Usage: parse <json>\n");
    return;
  }
  {
    jmp_buf __nupa_saved;
    memcpy(__nupa_saved, __nupa_exception_buf, sizeof(jmp_buf));
    volatile int __nupa_state = 0;
    if (setjmp(__nupa_exception_buf) != 0)     __nupa_state = 1;
    if (__nupa_state == 0)     {
      NPObject * nr = JSON__Parser_parse_(&nupa_JSON__Parser_class, __nupa_sel_parse_, arg);
      ((struct nupa_vtable *)(nr->isa->vtable))->retain((NPObject *)(nr), __nupa_sel_retain);
      ({ NPObject *__nupa_tmp_29 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_29 ? ((struct nupa_vtable *)__nupa_tmp_29->isa->vtable)->release(__nupa_tmp_29, __nupa_sel_release) : 0; });
      ((struct JSON__Editor *)self)->_root = nr;
      printf("  Parsed OK:\n  ");
      ({ NPObject *__nupa_tmp_30 = ((NPObject *)(((struct JSON__Editor *)self)->_root)); __nupa_tmp_30 ? ((struct nupa_vtable *)__nupa_tmp_30->isa->vtable)->printOn_(__nupa_tmp_30, __nupa_sel_printOn_, 0) : 0; });
      printf("\n");
    }
    if (__nupa_state == 1)     {
      __nupa_state = 2;
      JSON__Error * e = __nupa_exception_value;
      {
        printf("  Parse error: %s\n", ((struct nupa_vtable *)(e->isa->vtable))->message((NPObject *)(e), __nupa_sel_message));
        ((struct nupa_vtable *)(e->isa->vtable))->release((NPObject *)(e), __nupa_sel_release);
      }
    }
    memcpy(__nupa_exception_buf, __nupa_saved, sizeof(jmp_buf));
    if (__nupa_state == 1)     longjmp(__nupa_exception_buf, 1);
  }
}

void JSON__Editor_cmdElist(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_31 = ((NPObject *)((JSON__Object *)((struct JSON__Editor *)self)->_root)); __nupa_tmp_31 ? ((struct nupa_vtable *)__nupa_tmp_31->isa->vtable)->each_(__nupa_tmp_31, __nupa_sel_each_, ^void(int k, NPObject * v) {
  printf("  %s (%s): ", ((JSON__Object *)((struct JSON__Editor *)self)->_root)->_keys[k], ((struct nupa_vtable *)(v->isa->vtable))->typeName((NPObject *)(v), __nupa_sel_typeName));
  ((struct nupa_vtable *)(v->isa->vtable))->printOn_((NPObject *)(v), __nupa_sel_printOn_, 0);
  printf("\n");
}
) : 0; });
}

void JSON__Editor_cmdSels(NPObject * self, SEL _cmd) {
  printf("  ── Selectors ──\n");
  SEL sa[] = { __nupa_sel_alloc, __nupa_sel_init, __nupa_sel_release, __nupa_sel_retain, __nupa_sel_typeName, __nupa_sel_printOn_, __nupa_sel_copyValue, __nupa_sel_cmdPrint, __nupa_sel_cmdSet_ };
  for (int i = 0;
(i < 9); (i)++)   printf("  SEL{name=\"%s\", hash=%u}\n", sa[i].name, sa[i].hash);
  SEL c = sel_registerName("onValueChanged:");
  printf("  sel_registerName: {name=\"%s\", hash=%u}\n", c.name, c.hash);
}

void JSON__Editor_cmdHelp(NPObject * self, SEL _cmd) {
  printf("  ── Commands ──\n");
  cmdHelpPrint();
  cmdHelpSet();
  cmdHelpGet();
  cmdHelpDel();
  cmdHelpKeys();
  cmdHelpType();
  cmdHelpLen();
  cmdHelpNew();
  cmdHelpParse();
  cmdHelpElist();
  cmdHelpSel();
  cmdHelpHelp();
  cmdHelpQuit();
}

void JSON__Editor_cmdQuit(NPObject * self, SEL _cmd) {
  printf("  Bye!\n");
  ((struct JSON__Editor *)self)->_running = 0;
}

void Watcher_dealloc(NPObject * self, SEL _cmd) {
  printf("  [Watcher] dealloc. target=%p\n", (void *)((struct Watcher *)self)->_target);
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

NPObject * nupa_alloc(struct NPClass * cls);

NPObject * nupa_init(NPObject * self);

void nupa_release(NPObject * obj);

NPObject * nupa_retain(NPObject * obj);

int read_line(char * buf, int size) {
  if (!isatty(STDIN_FILENO))   {
    if (!fgets(buf, size, stdin))     return 0;
    int len = (int)strlen(buf);
    while (((len > 0) && (buf[(len - 1)] == '\n' || buf[(len - 1)] == '\r')))     buf[--len] = '\x00';
    return len;
  }
  struct termios old, raw;
  tcgetattr(STDIN_FILENO, &old);
  raw = old;
  (raw.c_lflag &= ~(ECHO | ICANON));
  raw.c_cc[VMIN] = 1;
  raw.c_cc[VTIME] = 0;
  tcsetattr(STDIN_FILENO, TCSANOW, &raw);
  int pos = 0, len = 0;
  while ((len < (size - 1)))   {
    char c;
    if ((read(STDIN_FILENO, &c, 1) <= 0))     break;
    if (c == '\x1B')     {
      char seq[2];
      if ((read(STDIN_FILENO, &seq[0], 1) <= 0))       break;
      if ((read(STDIN_FILENO, &seq[1], 1) <= 0))       break;
      if (seq[0] == '[')       {
        if ((seq[1] == 'D' && (pos > 0)))         {
          (pos)--;
          printf("\033[D");
          fflush(stdout);
        }
        else         if ((seq[1] == 'C' && (pos < len)))         {
          (pos)++;
          printf("\033[C");
          fflush(stdout);
        }
      }
      continue;
    }
    if ((c == '\n' || c == '\r'))     {
      buf[len] = '\x00';
      break;
    }
    if ((c == '\x08' || c == 127))     {
      if ((pos > 0))       {
        memmove(&buf[(pos - 1)], &buf[pos], (len - pos));
        (len)--;
        (pos)--;
        printf("\b%s ", &buf[pos]);
        for (int i = len;
(i > pos); (i)--)         printf("\b");
        fflush(stdout);
      }
      continue;
    }
    if ((pos < len))     memmove(&buf[(pos + 1)], &buf[pos], (len - pos));
    buf[pos] = c;
    (len)++;
    (pos)++;
    putchar(c);
    if ((pos < len))     {
      printf("%s", &buf[pos]);
      for (int i = len;
(i > pos); (i)--)       printf("\b");
    }
    fflush(stdout);
  }
  putchar('\n');
  tcsetattr(STDIN_FILENO, TCSANOW, &old);
  return len;
}

void skip_ws(const char * * p) {
  while ((**p && ((unsigned char)**p <= 32)))   (*p)++;
}

int parse_hex4(const char * * p) {
  int val = 0;
  for (int i = 0;
(i < 4); (i)++)   {
    char c = *(*p)++;
    if (((c >= '0') && (c <= '9')))     val = ((val << 4) | (c - '0'));
    else     if (((c >= 'a') && (c <= 'f')))     val = ((val << 4) | ((c - 'a') + 10));
    else     if (((c >= 'A') && (c <= 'F')))     val = ((val << 4) | ((c - 'A') + 10));
    else     return -1;
  }
  return val;
}

char * parse_raw_string(const char * * p) {
  if (**p != '\"')   return NULL;
  (*p)++;
  int cap = 64, len = 0;
  char * buf = (char *)malloc(cap);
  while (**p)   {
    char c = **p;
    if (c == '\"')     {
      (*p)++;
      break;
    }
    if (c == '\\')     {
      (*p)++;
      switch (**p)       {
        case '\"':
          buf[(len)++] = '\"';
        break;
        case '\\':
          buf[(len)++] = '\\';
        break;
        case '/':
          buf[(len)++] = '/';
        break;
        case 'b':
          buf[(len)++] = '\x08';
        break;
        case 'f':
          buf[(len)++] = '\x0C';
        break;
        case 'n':
          buf[(len)++] = '\n';
        break;
        case 'r':
          buf[(len)++] = '\r';
        break;
        case 't':
          buf[(len)++] = '\t';
        break;
        case 'u':
          {
            (*p)++;
            int cp = parse_hex4(p);
            if ((cp < 0))             {
              free(buf);
              return NULL;
            }
            if ((cp <= 127))             buf[(len)++] = (char)cp;
            else             if ((cp <= 2047))             {
              buf[(len)++] = (char)(192 | (cp >> 6));
              buf[(len)++] = (char)(128 | (cp & 63));
            }
            else             {
              buf[(len)++] = (char)(224 | (cp >> 12));
              buf[(len)++] = (char)(128 | ((cp >> 6) & 63));
              buf[(len)++] = (char)(128 | (cp & 63));
            }
            continue;
          }
        default:
          buf[(len)++] = **p;
        break;
      }
    }
    else     {
      buf[(len)++] = c;
    }
    (*p)++;
    if ((len >= (cap - 4)))     {
      (cap *= 2);
      buf = (char *)realloc(buf, cap);
    }
  }
  buf[len] = '\x00';
  return buf;
}

NPObject * json_parse_value(const char * * p);

void THROW(const char * msg) {
  NPObject *__nupa_tmp_32 = (NPObject_alloc(&nupa_JSON__Error_class, __nupa_sel_alloc));
  JSON__Error * e = (JSON__Error *)(((struct nupa_vtable *)__nupa_tmp_32->isa->vtable)->initWithMessage_(__nupa_tmp_32, __nupa_sel_initWithMessage_, msg));
  {
    __nupa_exception_value = e;
    longjmp(__nupa_exception_buf, 1);
  }
}

NPObject * json_parse_null(const char * * p) {
  if (strncmp(*p, "null", 4) == 0)   {
    (*p += 4);
    return JSON__Null_sharedNull(&nupa_JSON__Null_class, __nupa_sel_sharedNull);
  }
  THROW("Expected 'null'");
  return NULL;
}

NPObject * json_parse_true(const char * * p) {
  if (strncmp(*p, "true", 4) == 0)   {
    (*p += 4);
    return ({ NPObject *__nupa_tmp_33 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Bool_class, __nupa_sel_alloc))); __nupa_tmp_33 ? ((struct nupa_vtable *)__nupa_tmp_33->isa->vtable)->initWithBool_(__nupa_tmp_33, __nupa_sel_initWithBool_, 1) : 0; });
  }
  THROW("Expected 'true'");
  return NULL;
}

NPObject * json_parse_false(const char * * p) {
  if (strncmp(*p, "false", 5) == 0)   {
    (*p += 5);
    return ({ NPObject *__nupa_tmp_34 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Bool_class, __nupa_sel_alloc))); __nupa_tmp_34 ? ((struct nupa_vtable *)__nupa_tmp_34->isa->vtable)->initWithBool_(__nupa_tmp_34, __nupa_sel_initWithBool_, 0) : 0; });
  }
  THROW("Expected 'false'");
  return NULL;
}

NPObject * json_parse_number(const char * * p) {
  char * start = *p;
  if (**p == '-')   (*p)++;
  while ((**p && isdigit(**p)))   (*p)++;
  if (**p == '.')   {
    (*p)++;
    while ((**p && isdigit(**p)))     (*p)++;
  }
  if ((**p == 'e' || **p == 'E'))   {
    (*p)++;
    if ((**p == '+' || **p == '-'))     (*p)++;
    while ((**p && isdigit(**p)))     (*p)++;
  }
  if (*p == start)   THROW("Expected number");
  int len = (int)(*p - start);
  if ((len >= 64))   THROW("Number too long");
  char buf[64];
  strncpy(buf, start, len);
  buf[len] = '\x00';
  return ({ NPObject *__nupa_tmp_35 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Number_class, __nupa_sel_alloc))); __nupa_tmp_35 ? ((struct nupa_vtable *)__nupa_tmp_35->isa->vtable)->initWithDouble_(__nupa_tmp_35, __nupa_sel_initWithDouble_, strtod(buf, NULL)) : 0; });
}

NPObject * json_parse_string(const char * * p) {
  char * raw = (char *)(parse_raw_string(p));
  if (!raw)   THROW("Invalid string");
  NPObject *__nupa_tmp_36 = (NPObject_alloc(&nupa_JSON__String_class, __nupa_sel_alloc));
  NPObject * result = ((struct nupa_vtable *)__nupa_tmp_36->isa->vtable)->initWithString_(__nupa_tmp_36, __nupa_sel_initWithString_, raw);
  free(raw);
  return result;
}

NPObject * json_parse_array(const char * * p) {
  if (**p != '[')   THROW("Expected '['");
  (*p)++;
  JSON__Array * arr = ({ NPObject *__nupa_tmp_37 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Array_class, __nupa_sel_alloc))); __nupa_tmp_37 ? ((struct nupa_vtable *)__nupa_tmp_37->isa->vtable)->init(__nupa_tmp_37, __nupa_sel_init) : 0; });
  skip_ws(p);
  if (**p == ']')   {
    (*p)++;
    return arr;
  }
  while (1)   {
    skip_ws(p);
    NPObject * val = json_parse_value(p);
    skip_ws(p);
    if (val)     ((struct nupa_vtable *)(arr->isa->vtable))->add_((NPObject *)(arr), __nupa_sel_add_, (NPObject *)(val));
    if (**p == ',')     {
      (*p)++;
      skip_ws(p);
    }
    else     if (**p == ']')     {
      (*p)++;
      break;
    }
    else     THROW("Expected ',' or ']' in array");
  }
  return arr;
}

NPObject * json_parse_object(const char * * p) {
  if (**p != '{')   THROW("Expected '{'");
  (*p)++;
  JSON__Object * obj = ({ NPObject *__nupa_tmp_38 = ((NPObject *)(NPObject_alloc(&nupa_JSON__Object_class, __nupa_sel_alloc))); __nupa_tmp_38 ? ((struct nupa_vtable *)__nupa_tmp_38->isa->vtable)->init(__nupa_tmp_38, __nupa_sel_init) : 0; });
  skip_ws(p);
  if (**p == '}')   {
    (*p)++;
    return obj;
  }
  while (1)   {
    skip_ws(p);
    if (**p != '\"')     THROW("Expected string key");
    char * key = (char *)(parse_raw_string(p));
    skip_ws(p);
    if (**p != ':')     {
      free(key);
      THROW("Expected ':' after key");
    }
    (*p)++;
    skip_ws(p);
    NPObject * val = json_parse_value(p);
    if ((key && val))     ((struct nupa_vtable *)(obj->isa->vtable))->set_forKey_((NPObject *)(obj), __nupa_sel_set_forKey_, (NPObject *)(val), key);
    if (key)     free(key);
    skip_ws(p);
    if (**p == ',')     {
      (*p)++;
      skip_ws(p);
    }
    else     if (**p == '}')     {
      (*p)++;
      break;
    }
    else     THROW("Expected ',' or '}' in object");
  }
  return obj;
}

NPObject * json_parse_value(const char * * p) {
  skip_ws(p);
  if (**p == '\x00')   return NULL;
  if (**p == 'n')   return json_parse_null(p);
  if (**p == 't')   return json_parse_true(p);
  if (**p == 'f')   return json_parse_false(p);
  if (**p == '\"')   return json_parse_string(p);
  if (**p == '[')   return json_parse_array(p);
  if (**p == '{')   return json_parse_object(p);
  if ((**p == '-' || isdigit(**p)))   return json_parse_number(p);
  THROW("Unexpected character");
  return NULL;
}

void cmdHelpPrint(void ) {
  printf("  %-20s %s\n", "print", "Print the JSON tree");
}

void cmdHelpSet(void ) {
  printf("  %-20s %s\n", "set <key> <json>", "Set a key to a JSON value");
}

void cmdHelpGet(void ) {
  printf("  %-20s %s\n", "get <key>", "Print value at key");
}

void cmdHelpDel(void ) {
  printf("  %-20s %s\n", "del <key>", "Delete a key");
}

void cmdHelpKeys(void ) {
  printf("  %-20s %s\n", "keys", "List all keys");
}

void cmdHelpType(void ) {
  printf("  %-20s %s\n", "type [<key>]", "Show type");
}

void cmdHelpLen(void ) {
  printf("  %-20s %s\n", "len", "Count of items");
}

void cmdHelpNew(void ) {
  printf("  %-20s %s\n", "new", "Start with empty object");
}

void cmdHelpParse(void ) {
  printf("  %-20s %s\n", "parse <json>", "Parse JSON as new root");
}

void cmdHelpElist(void ) {
  printf("  %-20s %s\n", "elist", "Enumerate via Block");
}

void cmdHelpSel(void ) {
  printf("  %-20s %s\n", "sel", "Show selectors demo");
}

void cmdHelpHelp(void ) {
  printf("  %-20s %s\n", "help", "This help");
}

void cmdHelpQuit(void ) {
  printf("  %-20s %s\n", "quit", "Exit");
}

SEL cmdSel(const char * name) {
  if (strcmp(name, "print") == 0)   return __nupa_sel_cmdPrint;
  if (strcmp(name, "set") == 0)   return __nupa_sel_cmdSet_;
  if (strcmp(name, "get") == 0)   return __nupa_sel_cmdGet_;
  if (strcmp(name, "del") == 0)   return __nupa_sel_cmdDel_;
  if (strcmp(name, "keys") == 0)   return __nupa_sel_cmdKeys;
  if (strcmp(name, "type") == 0)   return __nupa_sel_cmdType_;
  if (strcmp(name, "len") == 0)   return __nupa_sel_cmdLen;
  if (strcmp(name, "new") == 0)   return __nupa_sel_cmdNew;
  if (strcmp(name, "parse") == 0)   return __nupa_sel_cmdParse_;
  if (strcmp(name, "elist") == 0)   return __nupa_sel_cmdElist;
  if (strcmp(name, "sel") == 0)   return __nupa_sel_cmdSels;
  if (strcmp(name, "help") == 0)   return __nupa_sel_cmdHelp;
  if (strcmp(name, "quit") == 0)   return __nupa_sel_cmdQuit;
  return sel_registerName("");
}

int main(int argc, const char * argv[]) {
  nupa_meta_init();
  {
    nupa_autoreleasepool_t * __nupa_pool = nupa_autoreleasepool_push();
    printf("═══ Nupa Full Feature Demo ═══\n\n");
    printf("Features:\n");
    printf("  @namespace JSON { ... } — 7 classes\n");
    printf("  @protocol Value — polymorphic dispatch\n");
    printf("  @property/@synthesize — Bool, Number, String\n");
    printf("  @selector — command dispatch table\n");
    printf("  @try/@catch/@throw — error handling\n");
    printf("  @autoreleasepool — memory management\n");
    printf("  @category — Object (Keys)\n");
    printf("  Block — enumeration callback\n");
    printf("  @public weak — Watcher zeroing\n");
    printf("  instancetype — init return types\n");
    printf("  sel_registerName — runtime API\n");
    printf("  Manual MRC — retain/release/dealloc\n\n");
    printf("─── 1. @selector + sel_registerName ───\n");
    SEL a = __nupa_sel_init;
    SEL b = sel_registerName("init");
    printf("  selA: {name=\"%s\", hash=%u}\n", a.name, a.hash);
    printf("  selB: {name=\"%s\", hash=%u}\n", b.name, b.hash);
    printf("  Match: %s\n\n", a.hash == b.hash ? "YES" : "NO");
    printf("─── 2. @public (weak) ───\n");
    NPObject *__nupa_tmp_39 = (NPObject_alloc(&nupa_JSON__Object_class, __nupa_sel_alloc));
    JSON__Object * wo = (JSON__Object *)(((struct nupa_vtable *)__nupa_tmp_39->isa->vtable)->init(__nupa_tmp_39, __nupa_sel_init));
    NPObject *__nupa_tmp_40 = (NPObject_alloc(&nupa_Watcher_class, __nupa_sel_alloc));
    Watcher * wt = (Watcher *)(((struct nupa_vtable *)__nupa_tmp_40->isa->vtable)->initWithTarget_(__nupa_tmp_40, __nupa_sel_initWithTarget_, wo));
    printf("  target before release: %p\n", (void *)wt->_target);
    ((struct nupa_vtable *)(wo->isa->vtable))->release((NPObject *)(wo), __nupa_sel_release);
    printf("  target after release:  %p\n", (void *)wt->_target);
    ((struct nupa_vtable *)(wt->isa->vtable))->release((NPObject *)(wt), __nupa_sel_release);
    printf("\n");
    printf("─── 4. @try/@catch ───\n");
    {
      jmp_buf __nupa_saved;
      memcpy(__nupa_saved, __nupa_exception_buf, sizeof(jmp_buf));
      volatile int __nupa_state = 0;
      if (setjmp(__nupa_exception_buf) != 0)       __nupa_state = 1;
      if (__nupa_state == 0)       {
        NPObject * x = JSON__Parser_parse_(&nupa_JSON__Parser_class, __nupa_sel_parse_, "{bad");
        ((struct nupa_vtable *)(x->isa->vtable))->release((NPObject *)(x), __nupa_sel_release);
      }
      if (__nupa_state == 1)       {
        __nupa_state = 2;
        JSON__Error * e = __nupa_exception_value;
        {
          printf("  Caught: %s\n", ((struct nupa_vtable *)(e->isa->vtable))->message((NPObject *)(e), __nupa_sel_message));
          ((struct nupa_vtable *)(e->isa->vtable))->release((NPObject *)(e), __nupa_sel_release);
        }
      }
      memcpy(__nupa_exception_buf, __nupa_saved, sizeof(jmp_buf));
      if (__nupa_state == 1)       longjmp(__nupa_exception_buf, 1);
    }
    printf("\n");
    printf("─── 5. Interactive JSON Editor ───\n");
    NPObject *__nupa_tmp_41 = (NPObject_alloc(&nupa_JSON__Editor_class, __nupa_sel_alloc));
    JSON__Editor * ed = (JSON__Editor *)(((struct nupa_vtable *)__nupa_tmp_41->isa->vtable)->init(__nupa_tmp_41, __nupa_sel_init));
    ((struct nupa_vtable *)(ed->isa->vtable))->run((NPObject *)(ed), __nupa_sel_run);
    ((struct nupa_vtable *)(ed->isa->vtable))->release((NPObject *)(ed), __nupa_sel_release);
    printf("\n═══ Done ═══\n");
    nupa_autoreleasepool_pop(__nupa_pool);
  }
  return 0;
}

