// Generated by nupac
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
#include <stdio.h>


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_NPCraftPilot_vtable;
struct nupa_NPShipSystem_vtable;
struct nupa_NPDiamondAbuser_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_NPCraftPilot_vtable_index_initWithName_ 4
#define nupa_NPCraftPilot_vtable_index_bindSystem_ 5
#define nupa_NPShipSystem_vtable_index_initWithId_ 4
#define nupa_NPShipSystem_vtable_index_linkPilot_ 5
#define nupa_NPDiamondAbuser_vtable_index_executeCoreTask 4
#define nupa_NPDiamondAbuser_vtable_index_leftBranchAction 5
#define nupa_NPDiamondAbuser_vtable_index_rightBranchAction 6

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_bindSystem_ = {.name = "bindSystem_", .hash = 0xDB14CD90};
static const SEL __nupa_sel_initWithId_ = {.name = "initWithId_", .hash = 0x8CE5C4CB};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_initWithName_ = {.name = "initWithName_", .hash = 0xC90744AD};
static const SEL __nupa_sel_linkPilot_ = {.name = "linkPilot_", .hash = 0xD6448F6E};
static const SEL __nupa_sel_leftBranchAction = {.name = "leftBranchAction", .hash = 0xAEBABB7A};
static const SEL __nupa_sel_rightBranchAction = {.name = "rightBranchAction", .hash = 0x88B2F89F};
static const SEL __nupa_sel_executeCoreTask = {.name = "executeCoreTask", .hash = 0x3DD99A7E};
static const SEL __nupa_sel_collisionCounter = {.name = "collisionCounter", .hash = 0x28D3BBA1};

typedef struct NPObject NPObject;
typedef struct NPCraftPilot NPCraftPilot;
typedef struct NPShipSystem NPShipSystem;
typedef struct NPDiamondAbuser NPDiamondAbuser;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * NPCraftPilot_initWithName_(NPObject * self, SEL _cmd, const char * name);
void NPCraftPilot_bindSystem_(NPObject * self, SEL _cmd, NPShipSystem * sys);
NPClass * NPCraftPilot_getClass(NPClass * self, SEL _cmd);
NPObject * NPShipSystem_initWithId_(NPObject * self, SEL _cmd, int sid);
void NPShipSystem_linkPilot_(NPObject * self, SEL _cmd, NPObject * pilot);
NPClass * NPShipSystem_getClass(NPClass * self, SEL _cmd);
void NPDiamondAbuser_executeCoreTask(NPObject * self, SEL _cmd);
void NPDiamondAbuser_leftBranchAction(NPObject * self, SEL _cmd);
void NPDiamondAbuser_rightBranchAction(NPObject * self, SEL _cmd);
int NPDiamondAbuser_collisionCounter(NPObject * self, SEL _cmd);
void NPDiamondAbuser_setCollisionCounter_(NPObject * self, SEL _cmd, int value);
NPClass * NPDiamondAbuser_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass nupa_NPObject_class;
extern NPClass nupa_NPCraftPilot_class;
extern NPClass nupa_NPShipSystem_class;
extern NPClass nupa_NPDiamondAbuser_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct NPCraftPilot {
    struct NPClass *isa;
    uint32_t retain_count;
    NPShipSystem * boundSystem;
    const char * pilotName;
};
typedef struct NPCraftPilot NPCraftPilot;
struct nupa_NPCraftPilot_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithName_)(NPObject *, SEL, const char *);
    void (*bindSystem_)(NPObject *, SEL, NPShipSystem *);
};
struct nupa_NPCraftPilot_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPShipSystem {
    struct NPClass *isa;
    uint32_t retain_count;
    NPCraftPilot * currentPilot;
    int systemStatusId;
};
typedef struct NPShipSystem NPShipSystem;
struct nupa_NPShipSystem_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithId_)(NPObject *, SEL, int);
    void (*linkPilot_)(NPObject *, SEL, NPObject *);
};
struct nupa_NPShipSystem_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPDiamondAbuser {
    struct NPClass *isa;
    uint32_t retain_count;
    int _collisionCounter;
};
typedef struct NPDiamondAbuser NPDiamondAbuser;
struct nupa_NPDiamondAbuser_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*executeCoreTask)(NPObject *, SEL);
    void (*leftBranchAction)(NPObject *, SEL);
    void (*rightBranchAction)(NPObject *, SEL);
    int (*collisionCounter)(NPObject *, SEL);
    void (*setCollisionCounter_)(NPObject *, SEL, int);
};
struct nupa_NPDiamondAbuser_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
NPObject * NPCraftPilot_initWithName_(NPObject * self, SEL _cmd, const char * name) {
    struct NPCraftPilot * _self = ((struct NPCraftPilot *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct NPCraftPilot *)(self))->pilotName = name;
                ((struct NPCraftPilot *)(self))->boundSystem = NULL;
            }
        }
        return self;
    }
}

void NPCraftPilot_bindSystem_(NPObject * self, SEL _cmd, NPShipSystem * sys) {
    struct NPCraftPilot * _self = ((struct NPCraftPilot *)(self));
    {
        ((struct NPCraftPilot *)(self))->boundSystem = sys;
    }
}

NPClass * NPCraftPilot_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPCraftPilot_class;
}

NPObject * NPShipSystem_initWithId_(NPObject * self, SEL _cmd, int sid) {
    struct NPShipSystem * _self = ((struct NPShipSystem *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct NPShipSystem *)(self))->systemStatusId = sid;
                ((struct NPShipSystem *)(self))->currentPilot = NULL;
            }
        }
        return self;
    }
}

void NPShipSystem_linkPilot_(NPObject * self, SEL _cmd, NPObject * pilot) {
    struct NPShipSystem * _self = ((struct NPShipSystem *)(self));
    {
        ((struct NPShipSystem *)(self))->currentPilot = ((NPCraftPilot *)(pilot));
        ((struct nupa_NPCraftPilot_vtable *)((struct NPShipSystem *)(self))->currentPilot->isa->vtable)->bindSystem_(((struct NPShipSystem *)(self))->currentPilot, __nupa_sel_bindSystem_, self);
    }
}

NPClass * NPShipSystem_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPShipSystem_class;
}

void NPDiamondAbuser_executeCoreTask(NPObject * self, SEL _cmd) {
    struct NPDiamondAbuser * _self = ((struct NPDiamondAbuser *)(self));
    {
        ((struct NPDiamondAbuser *)(self))->_collisionCounter = ((struct NPDiamondAbuser *)(self))->_collisionCounter + 100;
        printf("[菱形汇聚] 成功穿透 Left 和 Right 协议网，执行最底层 Base 协议核心任务！\n");
    }
}

void NPDiamondAbuser_leftBranchAction(NPObject * self, SEL _cmd) {
    struct NPDiamondAbuser * _self = ((struct NPDiamondAbuser *)(self));
    {
        ((struct NPDiamondAbuser *)(self))->_collisionCounter = ((struct NPDiamondAbuser *)(self))->_collisionCounter + 10;
        printf("[左翼协议] 触发左分支动作。\n");
    }
}

void NPDiamondAbuser_rightBranchAction(NPObject * self, SEL _cmd) {
    struct NPDiamondAbuser * _self = ((struct NPDiamondAbuser *)(self));
    {
        ((struct NPDiamondAbuser *)(self))->_collisionCounter = ((struct NPDiamondAbuser *)(self))->_collisionCounter + 5;
        printf("[右翼协议] 触发右分支动作。\n");
    }
}

int NPDiamondAbuser_collisionCounter(NPObject * self, SEL _cmd) {
    return ((struct NPDiamondAbuser *)(self))->_collisionCounter;
}

void NPDiamondAbuser_setCollisionCounter_(NPObject * self, SEL _cmd, int value) {
    ((struct NPDiamondAbuser *)(self))->_collisionCounter = value;
}

NPClass * NPDiamondAbuser_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPDiamondAbuser_class;
}

int main(int argc, const char * * argv) {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            printf("==================================================\n");
            printf(">>>  nupac 编译器「多文件交叉依赖与菱形协议」压测  <<<\n");
            printf("==================================================\n\n");
            printf("--- 测试点 1: 跨文件前置声明与双向互锁依赖 ---\n");
            NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_NPShipSystem_class, __nupa_sel_alloc));
            NPShipSystem * system = ((struct nupa_NPShipSystem_vtable *)__nupa_tmp_0->isa->vtable)->initWithId_(__nupa_tmp_0, __nupa_sel_initWithId_, 2026);
            NPObject *__nupa_tmp_1 = (NPObject_alloc(&nupa_NPCraftPilot_class, __nupa_sel_alloc));
            NPCraftPilot * pilot = ((struct nupa_NPCraftPilot_vtable *)__nupa_tmp_1->isa->vtable)->initWithName_(__nupa_tmp_1, __nupa_sel_initWithName_, "指挥官凯克特斯");
            ((struct nupa_NPShipSystem_vtable *)system->isa->vtable)->linkPilot_(system, __nupa_sel_linkPilot_, pilot);
            printf("[符号断言] 双向互锁指针解析成功！\n");
            printf("船只系统绑定的飞行员: %s\n", ((struct NPShipSystem *)(system))->currentPilot->pilotName);
            printf("飞行员反向绑定的系统ID: %d\n", ((struct NPCraftPilot *)(pilot))->boundSystem->systemStatusId);
            printf("\n--- 测试点 2: 菱形协议树多重挂载与符号分发 ---\n");
            NPObject *__nupa_tmp_2 = (NPObject_alloc(&nupa_NPDiamondAbuser_class, __nupa_sel_alloc));
            NPDiamondAbuser * abuser = ((struct nupa_NPObject_vtable *)__nupa_tmp_2->isa->vtable)->init(__nupa_tmp_2, __nupa_sel_init);
            ((struct nupa_NPDiamondAbuser_vtable *)abuser->isa->vtable)->leftBranchAction(abuser, __nupa_sel_leftBranchAction);
            ((struct nupa_NPDiamondAbuser_vtable *)abuser->isa->vtable)->rightBranchAction(abuser, __nupa_sel_rightBranchAction);
            ((struct nupa_NPDiamondAbuser_vtable *)abuser->isa->vtable)->executeCoreTask(abuser, __nupa_sel_executeCoreTask);
            printf("[状态检查] 菱形冲突计数器累加值: %d (预期为 115)\n", ((struct nupa_NPDiamondAbuser_vtable *)abuser->isa->vtable)->collisionCounter(abuser, __nupa_sel_collisionCounter));
            nupa_release(system);
            nupa_release(pilot);
            nupa_release(abuser);
            printf("\n==================================================\n");
            printf(">>>     神作中的神作！多文件联动编译全线打通！    <<<\n");
            printf("==================================================\n");
        }
        nupa_autoreleasepool_pop(__pool);
    }
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Protocol metadata ─────────────────────────────────

extern NPProtocol nupa_protocol_NPBaseProtocol;
extern NPProtocol nupa_protocol_NPLeftProtocol;
extern NPProtocol nupa_protocol_NPRightProtocol;

NPProtocol nupa_protocol_NPBaseProtocol = {
    .name = "NPBaseProtocol",
    .parents = (NPProtocol *[]){
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "executeCoreTask", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};

NPProtocol nupa_protocol_NPLeftProtocol = {
    .name = "NPLeftProtocol",
    .parents = (NPProtocol *[]){
        &nupa_protocol_NPBaseProtocol,
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "leftBranchAction", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};

NPProtocol nupa_protocol_NPRightProtocol = {
    .name = "NPRightProtocol",
    .parents = (NPProtocol *[]){
        &nupa_protocol_NPBaseProtocol,
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "rightBranchAction", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_NPCraftPilot_vtable nupa_NPCraftPilot_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithName_ = NPCraftPilot_initWithName_,
    .bindSystem_ = NPCraftPilot_bindSystem_,
};

struct nupa_NPShipSystem_vtable nupa_NPShipSystem_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithId_ = NPShipSystem_initWithId_,
    .linkPilot_ = NPShipSystem_linkPilot_,
};

struct nupa_NPDiamondAbuser_vtable nupa_NPDiamondAbuser_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .executeCoreTask = NPDiamondAbuser_executeCoreTask,
    .leftBranchAction = NPDiamondAbuser_leftBranchAction,
    .rightBranchAction = NPDiamondAbuser_rightBranchAction,
    .collisionCounter = NPDiamondAbuser_collisionCounter,
    .setCollisionCounter_ = NPDiamondAbuser_setCollisionCounter_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_NPCraftPilot_meta_vtable nupa_NPCraftPilot_meta_vtable_inst = {
    .class = NPCraftPilot_getClass,
};

struct nupa_NPShipSystem_meta_vtable nupa_NPShipSystem_meta_vtable_inst = {
    .class = NPShipSystem_getClass,
};

struct nupa_NPDiamondAbuser_meta_vtable nupa_NPDiamondAbuser_meta_vtable_inst = {
    .class = NPDiamondAbuser_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_NPCraftPilot_class;
NPClass nupa_NPShipSystem_class;
NPClass nupa_NPDiamondAbuser_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPCraftPilot_class = (NPClass){
        .name = "NPCraftPilot",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPCraftPilot),
        .vtable = &nupa_NPCraftPilot_vtable_inst,
        .class_vtable = &nupa_NPCraftPilot_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPShipSystem_class = (NPClass){
        .name = "NPShipSystem",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPShipSystem),
        .vtable = &nupa_NPShipSystem_vtable_inst,
        .class_vtable = &nupa_NPShipSystem_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPDiamondAbuser_class = (NPClass){
        .name = "NPDiamondAbuser",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPDiamondAbuser),
        .vtable = &nupa_NPDiamondAbuser_vtable_inst,
        .class_vtable = &nupa_NPDiamondAbuser_meta_vtable_inst,
        .protocols = (NPProtocol *[]){
        },
        .protocol_count = 2,
    };
}
