// Generated by nupac
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
struct nupa_vtable;
struct nupa_NPObject_meta_vtable;
struct nupa_Engine__Physics__RigidBody_meta_vtable;
struct nupa_Engine__Graphics__RenderNode_meta_vtable;
struct nupa_Engine__Math__Vector3D_meta_vtable;
struct nupa_Extension__Gameplay__CombatUnit_meta_vtable;

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nupa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nupa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nupa_sel_initWithX_Y_Z_ = {.name = "initWithX:Y:Z:", .hash = 0x59753092};
static const SEL __nupa_sel_addOffsetOfX_Y_Z_ = {.name = "addOffsetOfX:Y:Z:", .hash = 0x4F1B060F};
static const SEL __nupa_sel_scaleByFactor_ = {.name = "scaleByFactor:", .hash = 0x50AA5C6B};
static const SEL __nupa_sel_initWithMass_posX_posY_posZ_ = {.name = "initWithMass:posX:posY:posZ:", .hash = 0x3E4D8A00};
static const SEL __nupa_sel_registerCollisionCallback_ = {.name = "registerCollisionCallback:", .hash = 0x2C32AF3B};
static const SEL __nupa_sel_applyForceVector_ = {.name = "applyForceVector:", .hash = 0xA87C36F5};
static const SEL __nupa_sel_mass = {.name = "mass", .hash = 0xDF7738D1};
static const SEL __nupa_sel_setMass_ = {.name = "setMass_", .hash = 0x8CD12270};
static const SEL __nupa_sel_position = {.name = "position", .hash = 0x934F4E0A};
static const SEL __nupa_sel_setPosition_ = {.name = "setPosition_", .hash = 0x72E0787D};
static const SEL __nupa_sel_initWithName_ = {.name = "initWithName:", .hash = 0xE4076F2E};
static const SEL __nupa_sel_drawScenePass = {.name = "drawScenePass", .hash = 0x786E5304};
static const SEL __nupa_sel_nodeName = {.name = "nodeName", .hash = 0xD6DC2E2E};
static const SEL __nupa_sel_renderOffset = {.name = "renderOffset", .hash = 0xD009BA22};
static const SEL __nupa_sel_setRenderOffset_ = {.name = "setRenderOffset_", .hash = 0xC8DDC059};
static const SEL __nupa_sel_initUnitWithName_shield_mass_ = {.name = "initUnitWithName:shield:mass:", .hash = 0x9AA6C031};
static const SEL __nupa_sel_takePlasmaDamage_ = {.name = "takePlasmaDamage:", .hash = 0xC759CD51};
static const SEL __nupa_sel_shieldHp = {.name = "shieldHp", .hash = 0x9D5758C8};
static const SEL __nupa_sel_setShieldHp_ = {.name = "setShieldHp_", .hash = 0x286F5427};
static const SEL __nupa_sel_physicsBody = {.name = "physicsBody", .hash = 0xCEF1C9E6};
static const SEL __nupa_sel_setPhysicsBody_ = {.name = "setPhysicsBody_", .hash = 0xDA453A01};

#ifndef __NUPA_ROOT_DEFINED
#define __NUPA_ROOT_DEFINED
struct __nupa_root {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct __nupa_root __nupa_root;
#endif
#ifndef NPOBJECT_DEFINED
#define NPOBJECT_DEFINED
struct NPObject {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPObject NPObject;
#endif
struct Engine__Physics__RigidBody;
typedef struct Engine__Physics__RigidBody Engine__Physics__RigidBody;
struct Engine__Graphics__RenderNode;
typedef struct Engine__Graphics__RenderNode Engine__Graphics__RenderNode;
struct Engine__Math__Vector3D;
typedef struct Engine__Math__Vector3D Engine__Math__Vector3D;
struct Extension__Gameplay__CombatUnit;
typedef struct Extension__Gameplay__CombatUnit Extension__Gameplay__CombatUnit;

typedef void (^CollisionEventBlock)(int, Engine__Math__Vector3D *) ;
typedef CollisionEventBlock Engine__Physics__CollisionEventBlock;

NPObject * __nupa_root_init(NPObject * self, SEL _cmd);
void __nupa_root_dealloc(NPObject * self, SEL _cmd);
void __nupa_root_release(NPObject * self, SEL _cmd);
NPObject * __nupa_root_retain(NPObject * self, SEL _cmd);
NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
NPObject * Engine__Math__Vector3D_initWithX_Y_Z_(NPObject * self, SEL _cmd, int px, int py, int pz);
void Engine__Math__Vector3D_addOffsetOfX_Y_Z_(NPObject * self, SEL _cmd, int dx, int dy, int dz);
void Engine__Math__Vector3D_scaleByFactor_(NPObject * self, SEL _cmd, int factor);
NPObject * Engine__Physics__RigidBody_initWithMass_posX_posY_posZ_(NPObject * self, SEL _cmd, int m, int x, int y, int z);
void Engine__Physics__RigidBody_registerCollisionCallback_(NPObject * self, SEL _cmd, Engine__Physics__CollisionEventBlock callback);
void Engine__Physics__RigidBody_applyForceVector_(NPObject * self, SEL _cmd, Engine__Math__Vector3D * force);
int Engine__Physics__RigidBody_mass(NPObject * self, SEL _cmd);
void Engine__Physics__RigidBody_setMass_(NPObject * self, SEL _cmd, int value);
Engine__Math__Vector3D * Engine__Physics__RigidBody_position(NPObject * self, SEL _cmd);
void Engine__Physics__RigidBody_setPosition_(NPObject * self, SEL _cmd, Engine__Math__Vector3D * value);
void Engine__Physics__RigidBody_dealloc(NPObject * self, SEL _cmd);
NPObject * Engine__Graphics__RenderNode_initWithName_(NPObject * self, SEL _cmd, const char * name);
void Engine__Graphics__RenderNode_drawScenePass(NPObject * self, SEL _cmd);
const char * Engine__Graphics__RenderNode_nodeName(NPObject * self, SEL _cmd);
Engine__Math__Vector3D * Engine__Graphics__RenderNode_renderOffset(NPObject * self, SEL _cmd);
void Engine__Graphics__RenderNode_setRenderOffset_(NPObject * self, SEL _cmd, Engine__Math__Vector3D * value);
void Engine__Graphics__RenderNode_dealloc(NPObject * self, SEL _cmd);
NPObject * Extension__Gameplay__CombatUnit_initUnitWithName_shield_mass_(NPObject * self, SEL _cmd, const char * name, int hp, int m);
void Extension__Gameplay__CombatUnit_drawScenePass(NPObject * self, SEL _cmd);
void Extension__Gameplay__CombatUnit_takePlasmaDamage_(NPObject * self, SEL _cmd, int dmg);
int Extension__Gameplay__CombatUnit_shieldHp(NPObject * self, SEL _cmd);
void Extension__Gameplay__CombatUnit_setShieldHp_(NPObject * self, SEL _cmd, int value);
Engine__Physics__RigidBody * Extension__Gameplay__CombatUnit_physicsBody(NPObject * self, SEL _cmd);
void Extension__Gameplay__CombatUnit_setPhysicsBody_(NPObject * self, SEL _cmd, Engine__Physics__RigidBody * value);
void Extension__Gameplay__CombatUnit_dealloc(NPObject * self, SEL _cmd);
NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * self);
void nupa_release(NPObject * obj);
NPObject * nupa_retain(NPObject * obj);
int main(int argc, const char * argv[]);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * Engine__Physics__RigidBody_getClass(NPClass * self, SEL _cmd);
NPClass * Engine__Graphics__RenderNode_getClass(NPClass * self, SEL _cmd);
NPClass * Engine__Math__Vector3D_getClass(NPClass * self, SEL _cmd);
NPClass * Extension__Gameplay__CombatUnit_getClass(NPClass * self, SEL _cmd);

struct nupa_vtable {
    void (*addOffsetOfX_Y_Z_)(NPObject *, SEL, int, int, int);
    void (*applyForceVector_)(NPObject *, SEL, Engine__Math__Vector3D *);
    void (*dealloc)(NPObject *, SEL);
    void (*drawScenePass)(NPObject *, SEL);
    NPObject * (*init)(NPObject *, SEL);
    NPObject * (*initUnitWithName_shield_mass_)(NPObject *, SEL, const char *, int, int);
    NPObject * (*initWithMass_posX_posY_posZ_)(NPObject *, SEL, int, int, int, int);
    NPObject * (*initWithName_)(NPObject *, SEL, const char *);
    NPObject * (*initWithX_Y_Z_)(NPObject *, SEL, int, int, int);
    int (*mass)(NPObject *, SEL);
    const char * (*nodeName)(NPObject *, SEL);
    Engine__Physics__RigidBody * (*physicsBody)(NPObject *, SEL);
    Engine__Math__Vector3D * (*position)(NPObject *, SEL);
    void (*registerCollisionCallback_)(NPObject *, SEL, Engine__Physics__CollisionEventBlock);
    void (*release)(NPObject *, SEL);
    Engine__Math__Vector3D * (*renderOffset)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    void (*scaleByFactor_)(NPObject *, SEL, int);
    void (*setMass_)(NPObject *, SEL, int);
    void (*setPhysicsBody_)(NPObject *, SEL, Engine__Physics__RigidBody *);
    void (*setPosition_)(NPObject *, SEL, Engine__Math__Vector3D *);
    void (*setRenderOffset_)(NPObject *, SEL, Engine__Math__Vector3D *);
    void (*setShieldHp_)(NPObject *, SEL, int);
    int (*shieldHp)(NPObject *, SEL);
    void (*takePlasmaDamage_)(NPObject *, SEL, int);
};

struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Engine__Physics__RigidBody_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Engine__Graphics__RenderNode_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Engine__Math__Vector3D_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Extension__Gameplay__CombatUnit_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct Engine__Physics__RigidBody {
    struct NPClass *isa;
    uint32_t retain_count;
    int _mass;
    Engine__Math__Vector3D * _position;
    CollisionEventBlock _onCollision;
};
typedef struct Engine__Physics__RigidBody Engine__Physics__RigidBody;

struct Engine__Graphics__RenderNode {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * _nodeName;
    Engine__Math__Vector3D * _renderOffset;
};
typedef struct Engine__Graphics__RenderNode Engine__Graphics__RenderNode;

struct Engine__Math__Vector3D {
    struct NPClass *isa;
    uint32_t retain_count;
    int x;
    int y;
    int z;
};
typedef struct Engine__Math__Vector3D Engine__Math__Vector3D;

struct Extension__Gameplay__CombatUnit {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * _nodeName;
    Engine__Math__Vector3D * _renderOffset;
    int _shieldHp;
    Engine__Physics__RigidBody * _physicsBody;
};
typedef struct Extension__Gameplay__CombatUnit Extension__Gameplay__CombatUnit;

extern NPClass nupa___nupa_root_class;
extern NPClass nupa_NPObject_class;
extern NPClass nupa_Engine__Physics__RigidBody_class;
extern NPClass nupa_Engine__Graphics__RenderNode_class;
extern NPClass nupa_Engine__Math__Vector3D_class;
extern NPClass nupa_Extension__Gameplay__CombatUnit_class;
void nupa_meta_init(void);

struct nupa_vtable nupa___nupa_root_vtable_inst = {
    .addOffsetOfX_Y_Z_ = NULL,
    .applyForceVector_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))__nupa_root_dealloc,
    .drawScenePass = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))__nupa_root_init,
    .initUnitWithName_shield_mass_ = NULL,
    .initWithMass_posX_posY_posZ_ = NULL,
    .initWithName_ = NULL,
    .initWithX_Y_Z_ = NULL,
    .mass = NULL,
    .nodeName = NULL,
    .physicsBody = NULL,
    .position = NULL,
    .registerCollisionCallback_ = NULL,
    .release = (void (*)(NPObject *, SEL))__nupa_root_release,
    .renderOffset = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))__nupa_root_retain,
    .scaleByFactor_ = NULL,
    .setMass_ = NULL,
    .setPhysicsBody_ = NULL,
    .setPosition_ = NULL,
    .setRenderOffset_ = NULL,
    .setShieldHp_ = NULL,
    .shieldHp = NULL,
    .takePlasmaDamage_ = NULL,
};

struct nupa_vtable nupa_NPObject_vtable_inst = {
    .addOffsetOfX_Y_Z_ = NULL,
    .applyForceVector_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .drawScenePass = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initUnitWithName_shield_mass_ = NULL,
    .initWithMass_posX_posY_posZ_ = NULL,
    .initWithName_ = NULL,
    .initWithX_Y_Z_ = NULL,
    .mass = NULL,
    .nodeName = NULL,
    .physicsBody = NULL,
    .position = NULL,
    .registerCollisionCallback_ = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .renderOffset = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .scaleByFactor_ = NULL,
    .setMass_ = NULL,
    .setPhysicsBody_ = NULL,
    .setPosition_ = NULL,
    .setRenderOffset_ = NULL,
    .setShieldHp_ = NULL,
    .shieldHp = NULL,
    .takePlasmaDamage_ = NULL,
};

struct nupa_vtable nupa_Engine__Physics__RigidBody_vtable_inst = {
    .addOffsetOfX_Y_Z_ = NULL,
    .applyForceVector_ = (void (*)(NPObject *, SEL, Engine__Math__Vector3D *))Engine__Physics__RigidBody_applyForceVector_,
    .dealloc = (void (*)(NPObject *, SEL))Engine__Physics__RigidBody_dealloc,
    .drawScenePass = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initUnitWithName_shield_mass_ = NULL,
    .initWithMass_posX_posY_posZ_ = (NPObject * (*)(NPObject *, SEL, int, int, int, int))Engine__Physics__RigidBody_initWithMass_posX_posY_posZ_,
    .initWithName_ = NULL,
    .initWithX_Y_Z_ = NULL,
    .mass = (int (*)(NPObject *, SEL))Engine__Physics__RigidBody_mass,
    .nodeName = NULL,
    .physicsBody = NULL,
    .position = (Engine__Math__Vector3D * (*)(NPObject *, SEL))Engine__Physics__RigidBody_position,
    .registerCollisionCallback_ = (void (*)(NPObject *, SEL, Engine__Physics__CollisionEventBlock))Engine__Physics__RigidBody_registerCollisionCallback_,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .renderOffset = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .scaleByFactor_ = NULL,
    .setMass_ = (void (*)(NPObject *, SEL, int))Engine__Physics__RigidBody_setMass_,
    .setPhysicsBody_ = NULL,
    .setPosition_ = (void (*)(NPObject *, SEL, Engine__Math__Vector3D *))Engine__Physics__RigidBody_setPosition_,
    .setRenderOffset_ = NULL,
    .setShieldHp_ = NULL,
    .shieldHp = NULL,
    .takePlasmaDamage_ = NULL,
};

struct nupa_vtable nupa_Engine__Graphics__RenderNode_vtable_inst = {
    .addOffsetOfX_Y_Z_ = NULL,
    .applyForceVector_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Engine__Graphics__RenderNode_dealloc,
    .drawScenePass = (void (*)(NPObject *, SEL))Engine__Graphics__RenderNode_drawScenePass,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initUnitWithName_shield_mass_ = NULL,
    .initWithMass_posX_posY_posZ_ = NULL,
    .initWithName_ = (NPObject * (*)(NPObject *, SEL, const char *))Engine__Graphics__RenderNode_initWithName_,
    .initWithX_Y_Z_ = NULL,
    .mass = NULL,
    .nodeName = (const char * (*)(NPObject *, SEL))Engine__Graphics__RenderNode_nodeName,
    .physicsBody = NULL,
    .position = NULL,
    .registerCollisionCallback_ = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .renderOffset = (Engine__Math__Vector3D * (*)(NPObject *, SEL))Engine__Graphics__RenderNode_renderOffset,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .scaleByFactor_ = NULL,
    .setMass_ = NULL,
    .setPhysicsBody_ = NULL,
    .setPosition_ = NULL,
    .setRenderOffset_ = (void (*)(NPObject *, SEL, Engine__Math__Vector3D *))Engine__Graphics__RenderNode_setRenderOffset_,
    .setShieldHp_ = NULL,
    .shieldHp = NULL,
    .takePlasmaDamage_ = NULL,
};

struct nupa_vtable nupa_Engine__Math__Vector3D_vtable_inst = {
    .addOffsetOfX_Y_Z_ = (void (*)(NPObject *, SEL, int, int, int))Engine__Math__Vector3D_addOffsetOfX_Y_Z_,
    .applyForceVector_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .drawScenePass = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initUnitWithName_shield_mass_ = NULL,
    .initWithMass_posX_posY_posZ_ = NULL,
    .initWithName_ = NULL,
    .initWithX_Y_Z_ = (NPObject * (*)(NPObject *, SEL, int, int, int))Engine__Math__Vector3D_initWithX_Y_Z_,
    .mass = NULL,
    .nodeName = NULL,
    .physicsBody = NULL,
    .position = NULL,
    .registerCollisionCallback_ = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .renderOffset = NULL,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .scaleByFactor_ = (void (*)(NPObject *, SEL, int))Engine__Math__Vector3D_scaleByFactor_,
    .setMass_ = NULL,
    .setPhysicsBody_ = NULL,
    .setPosition_ = NULL,
    .setRenderOffset_ = NULL,
    .setShieldHp_ = NULL,
    .shieldHp = NULL,
    .takePlasmaDamage_ = NULL,
};

struct nupa_vtable nupa_Extension__Gameplay__CombatUnit_vtable_inst = {
    .addOffsetOfX_Y_Z_ = NULL,
    .applyForceVector_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))Extension__Gameplay__CombatUnit_dealloc,
    .drawScenePass = (void (*)(NPObject *, SEL))Extension__Gameplay__CombatUnit_drawScenePass,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .initUnitWithName_shield_mass_ = (NPObject * (*)(NPObject *, SEL, const char *, int, int))Extension__Gameplay__CombatUnit_initUnitWithName_shield_mass_,
    .initWithMass_posX_posY_posZ_ = NULL,
    .initWithName_ = (NPObject * (*)(NPObject *, SEL, const char *))Engine__Graphics__RenderNode_initWithName_,
    .initWithX_Y_Z_ = NULL,
    .mass = NULL,
    .nodeName = (const char * (*)(NPObject *, SEL))Engine__Graphics__RenderNode_nodeName,
    .physicsBody = (Engine__Physics__RigidBody * (*)(NPObject *, SEL))Extension__Gameplay__CombatUnit_physicsBody,
    .position = NULL,
    .registerCollisionCallback_ = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .renderOffset = (Engine__Math__Vector3D * (*)(NPObject *, SEL))Engine__Graphics__RenderNode_renderOffset,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .scaleByFactor_ = NULL,
    .setMass_ = NULL,
    .setPhysicsBody_ = (void (*)(NPObject *, SEL, Engine__Physics__RigidBody *))Extension__Gameplay__CombatUnit_setPhysicsBody_,
    .setPosition_ = NULL,
    .setRenderOffset_ = (void (*)(NPObject *, SEL, Engine__Math__Vector3D *))Engine__Graphics__RenderNode_setRenderOffset_,
    .setShieldHp_ = (void (*)(NPObject *, SEL, int))Extension__Gameplay__CombatUnit_setShieldHp_,
    .shieldHp = (int (*)(NPObject *, SEL))Extension__Gameplay__CombatUnit_shieldHp,
    .takePlasmaDamage_ = (void (*)(NPObject *, SEL, int))Extension__Gameplay__CombatUnit_takePlasmaDamage_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Engine__Physics__RigidBody_meta_vtable nupa_Engine__Physics__RigidBody_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Engine__Physics__RigidBody_getClass,
};

struct nupa_Engine__Graphics__RenderNode_meta_vtable nupa_Engine__Graphics__RenderNode_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Engine__Graphics__RenderNode_getClass,
};

struct nupa_Engine__Math__Vector3D_meta_vtable nupa_Engine__Math__Vector3D_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Engine__Math__Vector3D_getClass,
};

struct nupa_Extension__Gameplay__CombatUnit_meta_vtable nupa_Extension__Gameplay__CombatUnit_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Extension__Gameplay__CombatUnit_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Engine__Physics__RigidBody_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Engine__Graphics__RenderNode_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Engine__Math__Vector3D_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Extension__Gameplay__CombatUnit_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nupa___nupa_root_class;
NPClass nupa_NPObject_class;
NPClass nupa_Engine__Physics__RigidBody_class;
NPClass nupa_Engine__Graphics__RenderNode_class;
NPClass nupa_Engine__Math__Vector3D_class;
NPClass nupa_Extension__Gameplay__CombatUnit_class;

void nupa_meta_init(void) {
    nupa___nupa_root_class = (NPClass){
        .name = "__nupa_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __nupa_root),
        .vtable = &nupa___nupa_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = &nupa___nupa_root_class,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Engine__Physics__RigidBody_class = (NPClass){
        .name = "Engine::Physics::RigidBody",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Engine__Physics__RigidBody),
        .vtable = &nupa_Engine__Physics__RigidBody_vtable_inst,
        .class_vtable = &nupa_Engine__Physics__RigidBody_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Engine__Graphics__RenderNode_class = (NPClass){
        .name = "Engine::Graphics::RenderNode",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Engine__Graphics__RenderNode),
        .vtable = &nupa_Engine__Graphics__RenderNode_vtable_inst,
        .class_vtable = &nupa_Engine__Graphics__RenderNode_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Engine__Math__Vector3D_class = (NPClass){
        .name = "Engine::Math::Vector3D",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Engine__Math__Vector3D),
        .vtable = &nupa_Engine__Math__Vector3D_vtable_inst,
        .class_vtable = &nupa_Engine__Math__Vector3D_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Extension__Gameplay__CombatUnit_class = (NPClass){
        .name = "Extension::Gameplay::CombatUnit",
        .superclass = &nupa_Engine__Graphics__RenderNode_class,
        .instance_size = sizeof(struct Extension__Gameplay__CombatUnit),
        .vtable = &nupa_Extension__Gameplay__CombatUnit_vtable_inst,
        .class_vtable = &nupa_Extension__Gameplay__CombatUnit_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * __nupa_root_init(NPObject * self, SEL _cmd) {
  return nupa_init(self);
}

void __nupa_root_dealloc(NPObject * self, SEL _cmd) {
  return;
}

void __nupa_root_release(NPObject * self, SEL _cmd) {
  nupa_release(self);
}

NPObject * __nupa_root_retain(NPObject * self, SEL _cmd) {
  return nupa_retain(self);
}

NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = nupa_alloc(self);
  return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  return nupa_init(self);
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  return;
}

void NPObject_release(NPObject * self, SEL _cmd) {
  nupa_release(self);
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  return nupa_retain(self);
}

NPObject * Engine__Math__Vector3D_initWithX_Y_Z_(NPObject * self, SEL _cmd, int px, int py, int pz) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct Engine__Math__Vector3D *)self)->x = px;
    ((struct Engine__Math__Vector3D *)self)->y = py;
    ((struct Engine__Math__Vector3D *)self)->z = pz;
  }
  return self;
}

void Engine__Math__Vector3D_addOffsetOfX_Y_Z_(NPObject * self, SEL _cmd, int dx, int dy, int dz) {
  (((struct Engine__Math__Vector3D *)self)->x += dx);
  (((struct Engine__Math__Vector3D *)self)->y += dy);
  (((struct Engine__Math__Vector3D *)self)->z += dz);
}

void Engine__Math__Vector3D_scaleByFactor_(NPObject * self, SEL _cmd, int factor) {
  (((struct Engine__Math__Vector3D *)self)->x *= factor);
  (((struct Engine__Math__Vector3D *)self)->y *= factor);
  (((struct Engine__Math__Vector3D *)self)->z *= factor);
}

NPObject * Engine__Physics__RigidBody_initWithMass_posX_posY_posZ_(NPObject * self, SEL _cmd, int m, int x, int y, int z) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct Engine__Physics__RigidBody *)self)->_mass = m;
    ((struct Engine__Physics__RigidBody *)self)->_position = ({ NPObject *__nupa_tmp_1 = (NPObject_alloc(&nupa_Engine__Math__Vector3D_class, __nupa_sel_alloc)); __nupa_tmp_1 ? ((struct nupa_vtable *)__nupa_tmp_1->isa->vtable)->initWithX_Y_Z_(__nupa_tmp_1, __nupa_sel_initWithX_Y_Z_, x, y, z) : 0; });
    ((struct Engine__Physics__RigidBody *)self)->_onCollision = NULL;
  }
  return self;
}

void Engine__Physics__RigidBody_registerCollisionCallback_(NPObject * self, SEL _cmd, Engine__Physics__CollisionEventBlock callback) {
  ((struct Engine__Physics__RigidBody *)self)->_onCollision = callback;
}

void Engine__Physics__RigidBody_applyForceVector_(NPObject * self, SEL _cmd, Engine__Math__Vector3D * force) {
  if (force)   {
    ({ NPObject *__nupa_tmp_2 = (((struct Engine__Physics__RigidBody *)self)->_position); __nupa_tmp_2 ? ((struct nupa_vtable *)__nupa_tmp_2->isa->vtable)->addOffsetOfX_Y_Z_(__nupa_tmp_2, __nupa_sel_addOffsetOfX_Y_Z_, force->x, force->y, force->z) : 0; });
    if (((struct Engine__Physics__RigidBody *)self)->_onCollision)     {
      int finalImpulse = (((struct Engine__Physics__RigidBody *)self)->_mass * 2);
      ((struct Engine__Physics__RigidBody *)self)->_onCollision(finalImpulse, ((struct Engine__Physics__RigidBody *)self)->_position);
    }
  }
}

int Engine__Physics__RigidBody_mass(NPObject * self, SEL _cmd) {
  return ((struct Engine__Physics__RigidBody *)self)->_mass;
}

void Engine__Physics__RigidBody_setMass_(NPObject * self, SEL _cmd, int value) {
  ((struct Engine__Physics__RigidBody *)self)->_mass = value;
}

Engine__Math__Vector3D * Engine__Physics__RigidBody_position(NPObject * self, SEL _cmd) {
  return ((struct Engine__Physics__RigidBody *)self)->_position;
}

void Engine__Physics__RigidBody_setPosition_(NPObject * self, SEL _cmd, Engine__Math__Vector3D * value) {
  ((struct Engine__Physics__RigidBody *)self)->_position = value;
}

void Engine__Physics__RigidBody_dealloc(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_3 = (((struct Engine__Physics__RigidBody *)self)->_position); __nupa_tmp_3 ? ((struct nupa_vtable *)__nupa_tmp_3->isa->vtable)->release(__nupa_tmp_3, __nupa_sel_release) : 0; });
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

NPObject * Engine__Graphics__RenderNode_initWithName_(NPObject * self, SEL _cmd, const char * name) {
  self = (&nupa_NPObject_vtable_inst)->init(self, __nupa_sel_init);
  if (self)   {
    ((struct Engine__Graphics__RenderNode *)self)->_nodeName = name;
    ((struct Engine__Graphics__RenderNode *)self)->_renderOffset = ({ NPObject *__nupa_tmp_4 = (NPObject_alloc(&nupa_Engine__Math__Vector3D_class, __nupa_sel_alloc)); __nupa_tmp_4 ? ((struct nupa_vtable *)__nupa_tmp_4->isa->vtable)->initWithX_Y_Z_(__nupa_tmp_4, __nupa_sel_initWithX_Y_Z_, 0, 0, 0) : 0; });
  }
  return self;
}

void Engine__Graphics__RenderNode_drawScenePass(NPObject * self, SEL _cmd) {
  printf("[基类渲染器] 正在绘制通用背景物 -> 名字: %s | 偏置坐标: (%d, %d, %d)\n", ((struct Engine__Graphics__RenderNode *)self)->_nodeName, ((struct Engine__Graphics__RenderNode *)self)->_renderOffset->x, ((struct Engine__Graphics__RenderNode *)self)->_renderOffset->y, ((struct Engine__Graphics__RenderNode *)self)->_renderOffset->z);
}

const char * Engine__Graphics__RenderNode_nodeName(NPObject * self, SEL _cmd) {
  return ((struct Engine__Graphics__RenderNode *)self)->_nodeName;
}

Engine__Math__Vector3D * Engine__Graphics__RenderNode_renderOffset(NPObject * self, SEL _cmd) {
  return ((struct Engine__Graphics__RenderNode *)self)->_renderOffset;
}

void Engine__Graphics__RenderNode_setRenderOffset_(NPObject * self, SEL _cmd, Engine__Math__Vector3D * value) {
  ((struct Engine__Graphics__RenderNode *)self)->_renderOffset = value;
}

void Engine__Graphics__RenderNode_dealloc(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_5 = (((struct Engine__Graphics__RenderNode *)self)->_renderOffset); __nupa_tmp_5 ? ((struct nupa_vtable *)__nupa_tmp_5->isa->vtable)->release(__nupa_tmp_5, __nupa_sel_release) : 0; });
  (&nupa_NPObject_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

NPObject * Extension__Gameplay__CombatUnit_initUnitWithName_shield_mass_(NPObject * self, SEL _cmd, const char * name, int hp, int m) {
  self = (&nupa_Engine__Graphics__RenderNode_vtable_inst)->initWithName_(self, __nupa_sel_initWithName_, name);
  if (self)   {
    ((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp = hp;
    ((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody = ({ NPObject *__nupa_tmp_6 = (NPObject_alloc(&nupa_Engine__Physics__RigidBody_class, __nupa_sel_alloc)); __nupa_tmp_6 ? ((struct nupa_vtable *)__nupa_tmp_6->isa->vtable)->initWithMass_posX_posY_posZ_(__nupa_tmp_6, __nupa_sel_initWithMass_posX_posY_posZ_, m, 0, 0, 0) : 0; });
  }
  return self;
}

void Extension__Gameplay__CombatUnit_drawScenePass(NPObject * self, SEL _cmd) {
  printf("[子类战机] [VTable 静态派发] 正在绘制战斗单元 -> 名字: %s | 护盾能量: %d\n", ((struct Extension__Gameplay__CombatUnit *)self)->_nodeName, ((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp);
  printf("          -> 核心轨道刚体物理坐标: (%d, %d, %d)\n", ((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody->_position->x, ((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody->_position->y, ((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody->_position->z);
}

void Extension__Gameplay__CombatUnit_takePlasmaDamage_(NPObject * self, SEL _cmd, int dmg) {
  (((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp -= dmg);
  if ((((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp < 0))   ((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp = 0;
  printf("[战斗警告] %s 承受等离子伤害 -%d 点！当前剩余护盾: %d\n", ((struct Extension__Gameplay__CombatUnit *)self)->_nodeName, dmg, ((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp);
}

int Extension__Gameplay__CombatUnit_shieldHp(NPObject * self, SEL _cmd) {
  return ((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp;
}

void Extension__Gameplay__CombatUnit_setShieldHp_(NPObject * self, SEL _cmd, int value) {
  ((struct Extension__Gameplay__CombatUnit *)self)->_shieldHp = value;
}

Engine__Physics__RigidBody * Extension__Gameplay__CombatUnit_physicsBody(NPObject * self, SEL _cmd) {
  return ((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody;
}

void Extension__Gameplay__CombatUnit_setPhysicsBody_(NPObject * self, SEL _cmd, Engine__Physics__RigidBody * value) {
  ((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody = value;
}

void Extension__Gameplay__CombatUnit_dealloc(NPObject * self, SEL _cmd) {
  ({ NPObject *__nupa_tmp_7 = (((struct Extension__Gameplay__CombatUnit *)self)->_physicsBody); __nupa_tmp_7 ? ((struct nupa_vtable *)__nupa_tmp_7->isa->vtable)->release(__nupa_tmp_7, __nupa_sel_release) : 0; });
  (&nupa_Engine__Graphics__RenderNode_vtable_inst)->dealloc(self, __nupa_sel_dealloc);
}

NPObject * nupa_alloc(struct NPClass * cls);

NPObject * nupa_init(NPObject * self);

void nupa_release(NPObject * obj);

NPObject * nupa_retain(NPObject * obj);

int main(int argc, const char * argv[]) {
  nupa_meta_init();
  {
    nupa_autoreleasepool_t * __nupa_pool = nupa_autoreleasepool_push();
    printf("====================================================================\n");
    printf(">>>  nupac 编译器「方括号 :: 全称消息传递」终极零导入史诗级压测   <<<\n");
    printf("====================================================================\n\n");
    printf("--- 1. 验证方括号内 [ [Namespace::Class alloc] init ] 的深度解析 ---\n");
    NPObject *__nupa_tmp_8 = (NPObject_alloc(&nupa_Engine__Graphics__RenderNode_class, __nupa_sel_alloc));
    Engine__Graphics__RenderNode * planetBackground = ((struct nupa_vtable *)__nupa_tmp_8->isa->vtable)->initWithName_(__nupa_tmp_8, __nupa_sel_initWithName_, "塞伯坦外星背景层");
    NPObject *__nupa_tmp_9 = (NPObject_alloc(&nupa_Extension__Gameplay__CombatUnit_class, __nupa_sel_alloc));
    Extension__Gameplay__CombatUnit * starfighter = ((struct nupa_vtable *)__nupa_tmp_9->isa->vtable)->initUnitWithName_shield_mass_(__nupa_tmp_9, __nupa_sel_initUnitWithName_shield_mass_, "奥德修斯号巡洋战机", 150, 500);
    printf("\n--- 2. 验证跨命名空间复合类型的 Block 闭包及 __block 状态捕获 ---\n");
    struct __nupa_byref_globalTelemetryCount {
        void *__isa;
        struct __nupa_byref_globalTelemetryCount *__forwarding;
        int __flags;
        int __value;
    };
    struct __nupa_byref_globalTelemetryCount globalTelemetryCount = {
        .__forwarding = &globalTelemetryCount,
        .__flags = 0,
        .__value = 0,
    };
    struct __nupa_byref_localShieldCharge {
        void *__isa;
        struct __nupa_byref_localShieldCharge *__forwarding;
        int __flags;
        int __value;
    };
    struct __nupa_byref_localShieldCharge localShieldCharge = {
        .__forwarding = &localShieldCharge,
        .__flags = 0,
        .__value = 150,
    };
    void (^onOrbitalCollision)(int, Engine__Math__Vector3D *) = ^void(int forceImpulse, Engine__Math__Vector3D * impactPos) {
  globalTelemetryCount.__forwarding->__value++;
  (localShieldCharge.__forwarding->__value -= 10);
  printf("[星轨遥测中心] 检测到严重轨道碰撞！\n");
  printf("               -> 累加遥测触发次数: %d\n", globalTelemetryCount.__forwarding->__value);
  printf("               -> 物理冲击动量: %d\n", forceImpulse);
  printf("               -> 碰撞点绝对空间三维坐标: (%d, %d, %d)\n", impactPos->x, impactPos->y, impactPos->z);
}
;
    ({ NPObject *__nupa_tmp_10 = (((struct nupa_vtable *)(starfighter->isa->vtable))->physicsBody(starfighter, __nupa_sel_physicsBody)); __nupa_tmp_10 ? ((struct nupa_vtable *)__nupa_tmp_10->isa->vtable)->registerCollisionCallback_(__nupa_tmp_10, __nupa_sel_registerCollisionCallback_, onOrbitalCollision) : 0; });
    printf("\n--- 3. 执行物理仿真步进与 VTable 多态动态渲染 ---\n");
    NPObject *__nupa_tmp_11 = (NPObject_alloc(&nupa_Engine__Math__Vector3D_class, __nupa_sel_alloc));
    Engine__Math__Vector3D * gravityPull = ((struct nupa_vtable *)__nupa_tmp_11->isa->vtable)->initWithX_Y_Z_(__nupa_tmp_11, __nupa_sel_initWithX_Y_Z_, 15, 25, -5);
    ((struct nupa_vtable *)(planetBackground->isa->vtable))->drawScenePass(planetBackground, __nupa_sel_drawScenePass);
    ((struct nupa_vtable *)(starfighter->isa->vtable))->drawScenePass(starfighter, __nupa_sel_drawScenePass);
    printf("\n>>> 警告：引力异常！开始对巡洋战机物理刚体施加三维引力拉扯...\n");
    ({ NPObject *__nupa_tmp_12 = (((struct nupa_vtable *)(starfighter->isa->vtable))->physicsBody(starfighter, __nupa_sel_physicsBody)); __nupa_tmp_12 ? ((struct nupa_vtable *)__nupa_tmp_12->isa->vtable)->applyForceVector_(__nupa_tmp_12, __nupa_sel_applyForceVector_, gravityPull) : 0; });
    ((struct nupa_vtable *)(starfighter->isa->vtable))->takePlasmaDamage_(starfighter, __nupa_sel_takePlasmaDamage_, 30);
    printf("\n");
    ((struct nupa_vtable *)(planetBackground->isa->vtable))->drawScenePass(planetBackground, __nupa_sel_drawScenePass);
    ((struct nupa_vtable *)(starfighter->isa->vtable))->drawScenePass(starfighter, __nupa_sel_drawScenePass);
    printf("\n--- 4. 极限混淆：方括号内 :: 表达式与 C 原生副作用联合轰炸 ---\n");
    int signalActive = 1;
    int dynamicFlag = 77;
    int resolvedShield = (signalActive > 0) ? ({ NPObject *__nupa_tmp_13 = ((dynamicFlag++, starfighter)); __nupa_tmp_13 ? ((struct nupa_vtable *)__nupa_tmp_13->isa->vtable)->shieldHp(__nupa_tmp_13, __nupa_sel_shieldHp) : 0; }) : 0;
    printf("[极限语法断言] 编译后端 C 优先级还原完美！\n");
    printf("               -> dynamicFlag 链式副作用自增值: %d (预期为 78)\n", dynamicFlag);
    printf("               -> 动态抓取的战机护盾值: %d (预期为 120)\n", resolvedShield);
    printf("\n--- 5. 正在执行对象关联树资源的深度安全销毁... ---\n");
    ((struct nupa_vtable *)(gravityPull->isa->vtable))->release(gravityPull, __nupa_sel_release);
    ((struct nupa_vtable *)(planetBackground->isa->vtable))->release(planetBackground, __nupa_sel_release);
    ((struct nupa_vtable *)(starfighter->isa->vtable))->release(starfighter, __nupa_sel_release);
    printf("\n====================================================================\n");
    printf(">>>    完美无瑕！在完全禁用 @using 时，:: 全称消息调用通关！   <<<\n");
    printf("====================================================================\n");
    nupa_autoreleasepool_pop(__nupa_pool);
  }
  return 0;
}

