// Generated by nupac
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
struct nupa_Universe__Space__Cruiser_vtable;
struct nupa_Universe__Space__Cruiser_meta_vtable;
struct nupa_Engine__Core__WeaponSystem_vtable;
struct nupa_Engine__Core__WeaponSystem_meta_vtable;
struct nupa_NPObject_vtable;
struct nupa_NPObject_meta_vtable;

static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nupa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nupa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nupa_sel_createPlasmaCannon = {.name = "createPlasmaCannon", .hash = 0x30D64D9A};
static const SEL __nupa_sel_createLaserBeam = {.name = "createLaserBeam", .hash = 0xB5534EE3};
static const SEL __nupa_sel_initWithName_damage_ = {.name = "initWithName:damage:", .hash = 0xD570B7D3};
static const SEL __nupa_sel_calculateFirepowerWithModifier_ = {.name = "calculateFirepowerWithModifier:", .hash = 0xDA45CD1D};
static const SEL __nupa_sel_baseDamage = {.name = "baseDamage", .hash = 0xF3AFA719};
static const SEL __nupa_sel_setBaseDamage_ = {.name = "setBaseDamage_", .hash = 0xF98E382C};
static const SEL __nupa_sel_weaponName = {.name = "weaponName", .hash = 0x62D5A7DA};
static const SEL __nupa_sel_initCruiserWithName_ = {.name = "initCruiserWithName:", .hash = 0xE9E8A675};
static const SEL __nupa_sel_fireAllWeaponsWithGlobalMod_ = {.name = "fireAllWeaponsWithGlobalMod:", .hash = 0xD8D30024};
static const SEL __nupa_sel_shipName = {.name = "shipName", .hash = 0x999B185C};
static const SEL __nupa_sel_primaryWeapon = {.name = "primaryWeapon", .hash = 0xC9C4AD35};
static const SEL __nupa_sel_setPrimaryWeapon_ = {.name = "setPrimaryWeapon_", .hash = 0x15F53A84};
static const SEL __nupa_sel_secondaryWeapon = {.name = "secondaryWeapon", .hash = 0x90F1A7ED};
static const SEL __nupa_sel_setSecondaryWeapon_ = {.name = "setSecondaryWeapon_", .hash = 0x471CA388};

typedef struct Universe__Space__Cruiser Universe__Space__Cruiser;
typedef struct Engine__Core__WeaponSystem Engine__Core__WeaponSystem;
typedef struct NPObject NPObject;

NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
Engine__Core__WeaponSystem * Engine__Core__WeaponSystem_createPlasmaCannon(NPClass * self, SEL _cmd);
Engine__Core__WeaponSystem * Engine__Core__WeaponSystem_createLaserBeam(NPClass * self, SEL _cmd);
NPObject * Engine__Core__WeaponSystem_initWithName_damage_(NPObject * self, SEL _cmd, const char * name, int dmg);
int Engine__Core__WeaponSystem_calculateFirepowerWithModifier_(NPObject * self, SEL _cmd, Engine__Core__WeaponModifierBlock mod);
int Engine__Core__WeaponSystem_baseDamage(NPObject * self, SEL _cmd);
void Engine__Core__WeaponSystem_setBaseDamage_(NPObject * self, SEL _cmd, int value);
const char * Engine__Core__WeaponSystem_weaponName(NPObject * self, SEL _cmd);
NPObject * Universe__Space__Cruiser_initCruiserWithName_(NPObject * self, SEL _cmd, const char * name);
void Universe__Space__Cruiser_fireAllWeaponsWithGlobalMod_(NPObject * self, SEL _cmd, Engine__Core__WeaponModifierBlock globalMod);
const char * Universe__Space__Cruiser_shipName(NPObject * self, SEL _cmd);
Engine__Core__WeaponSystem * Universe__Space__Cruiser_primaryWeapon(NPObject * self, SEL _cmd);
void Universe__Space__Cruiser_setPrimaryWeapon_(NPObject * self, SEL _cmd, Engine__Core__WeaponSystem * value);
Engine__Core__WeaponSystem * Universe__Space__Cruiser_secondaryWeapon(NPObject * self, SEL _cmd);
void Universe__Space__Cruiser_setSecondaryWeapon_(NPObject * self, SEL _cmd, Engine__Core__WeaponSystem * value);
void Universe__Space__Cruiser_dealloc(NPObject * self, SEL _cmd);
NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * self);
void nupa_release(NPObject * obj);
NPObject * nupa_retain(NPObject * obj);
int main(int argc, const char * argv[]);

NPClass * Universe__Space__Cruiser_getClass(NPClass * self, SEL _cmd);
NPClass * Engine__Core__WeaponSystem_getClass(NPClass * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);

struct nupa_Universe__Space__Cruiser_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initCruiserWithName_)(NPObject *, SEL, const char *);
    void (*fireAllWeaponsWithGlobalMod_)(NPObject *, SEL, Engine__Core__WeaponModifierBlock);
    const char * (*shipName)(NPObject *, SEL);
    Engine__Core__WeaponSystem * (*primaryWeapon)(NPObject *, SEL);
    void (*setPrimaryWeapon_)(NPObject *, SEL, Engine__Core__WeaponSystem *);
    Engine__Core__WeaponSystem * (*secondaryWeapon)(NPObject *, SEL);
    void (*setSecondaryWeapon_)(NPObject *, SEL, Engine__Core__WeaponSystem *);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_Universe__Space__Cruiser_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_Engine__Core__WeaponSystem_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initWithName_damage_)(NPObject *, SEL, const char *, int);
    int (*calculateFirepowerWithModifier_)(NPObject *, SEL, Engine__Core__WeaponModifierBlock);
    int (*baseDamage)(NPObject *, SEL);
    void (*setBaseDamage_)(NPObject *, SEL, int);
    const char * (*weaponName)(NPObject *, SEL);
};
struct nupa_Engine__Core__WeaponSystem_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    Engine__Core__WeaponSystem * (*createPlasmaCannon)(NPClass *, SEL);
    Engine__Core__WeaponSystem * (*createLaserBeam)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct Universe__Space__Cruiser {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * _shipName;
    Engine__Core__WeaponSystem * _primaryWeapon;
    Engine__Core__WeaponSystem * _secondaryWeapon;
};
typedef struct Universe__Space__Cruiser Universe__Space__Cruiser;

struct Engine__Core__WeaponSystem {
    struct NPClass *isa;
    uint32_t retain_count;
    int _baseDamage;
    const char * _weaponName;
};
typedef struct Engine__Core__WeaponSystem Engine__Core__WeaponSystem;

extern NPClass nupa_Universe__Space__Cruiser_class;
extern NPClass nupa_Engine__Core__WeaponSystem_class;
extern NPClass nupa_NPObject_class;
void nupa_meta_init(void);

struct nupa_Universe__Space__Cruiser_vtable nupa_Universe__Space__Cruiser_vtable_inst = {
    .init = NPObject_init,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initCruiserWithName_ = Universe__Space__Cruiser_initCruiserWithName_,
    .fireAllWeaponsWithGlobalMod_ = Universe__Space__Cruiser_fireAllWeaponsWithGlobalMod_,
    .shipName = Universe__Space__Cruiser_shipName,
    .primaryWeapon = Universe__Space__Cruiser_primaryWeapon,
    .setPrimaryWeapon_ = Universe__Space__Cruiser_setPrimaryWeapon_,
    .secondaryWeapon = Universe__Space__Cruiser_secondaryWeapon,
    .setSecondaryWeapon_ = Universe__Space__Cruiser_setSecondaryWeapon_,
    .dealloc = Universe__Space__Cruiser_dealloc,
};

struct nupa_Engine__Core__WeaponSystem_vtable nupa_Engine__Core__WeaponSystem_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initWithName_damage_ = Engine__Core__WeaponSystem_initWithName_damage_,
    .calculateFirepowerWithModifier_ = Engine__Core__WeaponSystem_calculateFirepowerWithModifier_,
    .baseDamage = Engine__Core__WeaponSystem_baseDamage,
    .setBaseDamage_ = Engine__Core__WeaponSystem_setBaseDamage_,
    .weaponName = Engine__Core__WeaponSystem_weaponName,
};

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct nupa_Universe__Space__Cruiser_meta_vtable nupa_Universe__Space__Cruiser_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Universe__Space__Cruiser_getClass,
};

struct nupa_Engine__Core__WeaponSystem_meta_vtable nupa_Engine__Core__WeaponSystem_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .createPlasmaCannon = Engine__Core__WeaponSystem_createPlasmaCannon,
    .createLaserBeam = Engine__Core__WeaponSystem_createLaserBeam,
    .class = Engine__Core__WeaponSystem_getClass,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

NPClass * Universe__Space__Cruiser_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Engine__Core__WeaponSystem_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nupa_Universe__Space__Cruiser_class;
NPClass nupa_Engine__Core__WeaponSystem_class;
NPClass nupa_NPObject_class;

void nupa_meta_init(void) {
    nupa_Universe__Space__Cruiser_class = (NPClass){
        .name = "Universe::Space::Cruiser",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Universe__Space__Cruiser),
        .vtable = &nupa_Universe__Space__Cruiser_vtable_inst,
        .class_vtable = &nupa_Universe__Space__Cruiser_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Engine__Core__WeaponSystem_class = (NPClass){
        .name = "Engine::Core::WeaponSystem",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Engine__Core__WeaponSystem),
        .vtable = &nupa_Engine__Core__WeaponSystem_vtable_inst,
        .class_vtable = &nupa_Engine__Core__WeaponSystem_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = nupa_alloc(self);
  return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nupa_init(self);
  }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return;
  }
}

void NPObject_release(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    nupa_release(self);
  }
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nupa_retain(self);
  }
}

Engine__Core__WeaponSystem * Engine__Core__WeaponSystem_createPlasmaCannon(NPClass * self, SEL _cmd) {
  return ((struct nupa_Engine__Core__WeaponSystem_vtable *)NPObject_alloc(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("alloc"))->isa->vtable)->initWithName_damage_(NPObject_alloc(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("alloc")), sel_registerName("initWithName:damage:"), "等离子重炮", 500);
}

Engine__Core__WeaponSystem * Engine__Core__WeaponSystem_createLaserBeam(NPClass * self, SEL _cmd) {
  return ((struct nupa_Engine__Core__WeaponSystem_vtable *)NPObject_alloc(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("alloc"))->isa->vtable)->initWithName_damage_(NPObject_alloc(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("alloc")), sel_registerName("initWithName:damage:"), "聚集激光束", 250);
}

NPObject * Engine__Core__WeaponSystem_initWithName_damage_(NPObject * self, SEL _cmd, const char * name, int dmg) {
  struct Engine__Core__WeaponSystem * _self = (struct Engine__Core__WeaponSystem *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _weaponName = name;
      _baseDamage = dmg;
    }
    return self;
  }
}

int Engine__Core__WeaponSystem_calculateFirepowerWithModifier_(NPObject * self, SEL _cmd, Engine__Core__WeaponModifierBlock mod) {
  struct Engine__Core__WeaponSystem * _self = (struct Engine__Core__WeaponSystem *)self;
  {
    if (mod)     {
      return mod(_baseDamage);
    }
    return _baseDamage;
  }
}

int Engine__Core__WeaponSystem_baseDamage(NPObject * self, SEL _cmd) {
  return ((struct Engine__Core__WeaponSystem *)self)->_baseDamage;
}

void Engine__Core__WeaponSystem_setBaseDamage_(NPObject * self, SEL _cmd, int value) {
  ((struct Engine__Core__WeaponSystem *)self)->_baseDamage = value;
}

const char * Engine__Core__WeaponSystem_weaponName(NPObject * self, SEL _cmd) {
  return ((struct Engine__Core__WeaponSystem *)self)->_weaponName;
}

NPObject * Universe__Space__Cruiser_initCruiserWithName_(NPObject * self, SEL _cmd, const char * name) {
  struct Universe__Space__Cruiser * _self = (struct Universe__Space__Cruiser *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _shipName = name;
      _primaryWeapon = Engine__Core__WeaponSystem_createPlasmaCannon(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("createPlasmaCannon"));
      _secondaryWeapon = Engine__Core__WeaponSystem_createLaserBeam(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("createLaserBeam"));
    }
    return self;
  }
}

void Universe__Space__Cruiser_fireAllWeaponsWithGlobalMod_(NPObject * self, SEL _cmd, Engine__Core__WeaponModifierBlock globalMod) {
  struct Universe__Space__Cruiser * _self = (struct Universe__Space__Cruiser *)self;
  {
    printf("[战舰开火] 巡洋舰「%s」全武器主控序列启动：\n", _shipName);
    int pDmg = ((struct nupa_Engine__Core__WeaponSystem_vtable *)_primaryWeapon->isa->vtable)->calculateFirepowerWithModifier_(_primaryWeapon, sel_registerName("calculateFirepowerWithModifier:"), globalMod);
    int sDmg = ((struct nupa_Engine__Core__WeaponSystem_vtable *)_secondaryWeapon->isa->vtable)->calculateFirepowerWithModifier_(_secondaryWeapon, sel_registerName("calculateFirepowerWithModifier:"), globalMod);
    printf("          -> 武器一 [%s] 释放威力: %d 点\n", ((struct nupa_Engine__Core__WeaponSystem_vtable *)_primaryWeapon->isa->vtable)->weaponName(_primaryWeapon, sel_registerName("weaponName")), pDmg);
    printf("          -> 武器二 [%s] 释放威力: %d 点\n", ((struct nupa_Engine__Core__WeaponSystem_vtable *)_secondaryWeapon->isa->vtable)->weaponName(_secondaryWeapon, sel_registerName("weaponName")), sDmg);
    printf("          -> 总输出瞬时能级: %d 兆瓦\n", (pDmg + sDmg));
  }
}

const char * Universe__Space__Cruiser_shipName(NPObject * self, SEL _cmd) {
  return ((struct Universe__Space__Cruiser *)self)->_shipName;
}

Engine__Core__WeaponSystem * Universe__Space__Cruiser_primaryWeapon(NPObject * self, SEL _cmd) {
  return ((struct Universe__Space__Cruiser *)self)->_primaryWeapon;
}

void Universe__Space__Cruiser_setPrimaryWeapon_(NPObject * self, SEL _cmd, Engine__Core__WeaponSystem * value) {
  ((struct Universe__Space__Cruiser *)self)->_primaryWeapon = value;
}

Engine__Core__WeaponSystem * Universe__Space__Cruiser_secondaryWeapon(NPObject * self, SEL _cmd) {
  return ((struct Universe__Space__Cruiser *)self)->_secondaryWeapon;
}

void Universe__Space__Cruiser_setSecondaryWeapon_(NPObject * self, SEL _cmd, Engine__Core__WeaponSystem * value) {
  ((struct Universe__Space__Cruiser *)self)->_secondaryWeapon = value;
}

void Universe__Space__Cruiser_dealloc(NPObject * self, SEL _cmd) {
  struct Universe__Space__Cruiser * _self = (struct Universe__Space__Cruiser *)self;
  {
    ((struct nupa_NPObject_vtable *)_primaryWeapon->isa->vtable)->release(_primaryWeapon, sel_registerName("release"));
    ((struct nupa_NPObject_vtable *)_secondaryWeapon->isa->vtable)->release(_secondaryWeapon, sel_registerName("release"));
    NPObject_dealloc(self, sel_registerName("dealloc"));
  }
}

NPObject * nupa_alloc(struct NPClass * cls);

NPObject * nupa_init(NPObject * self);

void nupa_release(NPObject * obj);

NPObject * nupa_retain(NPObject * obj);

typedef int (^)(int) Engine::Core::WeaponModifierBlock;

int main(int argc, const char * argv[]) {
  nupa_meta_init();
  {
    printf("====================================================================\n");
    printf(">>> nupac 编译器「全称 :: 类方法(+) & 嵌套闭包」零导入大点兵 <<<\n");
    printf("====================================================================\n\n");
    printf("--- 1. 测试方括号直接调用命名空间全称类方法（+ Method） ---\n");
    Engine__Core__WeaponSystem * customCannon = Engine__Core__WeaponSystem_createPlasmaCannon(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("createPlasmaCannon"));
    printf("[工厂断言] 成功独立制造武器: %s, 基础威力: %d\n", ((struct nupa_Engine__Core__WeaponSystem_vtable *)customCannon->isa->vtable)->weaponName(customCannon, sel_registerName("weaponName")), ((struct nupa_Engine__Core__WeaponSystem_vtable *)customCannon->isa->vtable)->baseDamage(customCannon, sel_registerName("baseDamage")));
    printf("\n--- 2. 测试内部级联类方法的对象初始化（Cruiser 内部调用 WeaponSystem） ---\n");
    Universe__Space__Cruiser * myFleetFlagship = ((struct nupa_Universe__Space__Cruiser_vtable *)NPObject_alloc(&nupa_Universe__Space__Cruiser_class, sel_registerName("alloc"))->isa->vtable)->initCruiserWithName_(NPObject_alloc(&nupa_Universe__Space__Cruiser_class, sel_registerName("alloc")), sel_registerName("initCruiserWithName:"), "无畏征服者号");
    printf("[战舰报告] 战舰名称: %s\n", ((struct nupa_Universe__Space__Cruiser_vtable *)myFleetFlagship->isa->vtable)->shipName(myFleetFlagship, sel_registerName("shipName")));
    printf("[战舰报告] 已自动装配主炮: %s\n", ((struct nupa_Engine__Core__WeaponSystem_vtable *)((struct nupa_Universe__Space__Cruiser_vtable *)myFleetFlagship->isa->vtable)->primaryWeapon(myFleetFlagship, sel_registerName("primaryWeapon"))->isa->vtable)->weaponName(((struct nupa_Universe__Space__Cruiser_vtable *)myFleetFlagship->isa->vtable)->primaryWeapon(myFleetFlagship, sel_registerName("primaryWeapon")), sel_registerName("weaponName")));
    printf("[战舰报告] 已自动装配副炮: %s\n", ((struct nupa_Engine__Core__WeaponSystem_vtable *)((struct nupa_Universe__Space__Cruiser_vtable *)myFleetFlagship->isa->vtable)->secondaryWeapon(myFleetFlagship, sel_registerName("secondaryWeapon"))->isa->vtable)->weaponName(((struct nupa_Universe__Space__Cruiser_vtable *)myFleetFlagship->isa->vtable)->secondaryWeapon(myFleetFlagship, sel_registerName("secondaryWeapon")), sel_registerName("weaponName")));
    printf("\n--- 3. 测试 Block 进行多层跨空间传递决议 ---\n");
    Engine__Core__WeaponModifierBlock tacticalFireMod = NULL;
    ((struct nupa_Universe__Space__Cruiser_vtable *)myFleetFlagship->isa->vtable)->fireAllWeaponsWithGlobalMod_(myFleetFlagship, sel_registerName("fireAllWeaponsWithGlobalMod:"), tacticalFireMod);
    printf("\n[状态断言] 经过嵌套闭包执行后的局部变量状态：\n");
    printf("          -> 累计触发射击次数: 无捕获变量（C99 兼容模式）\n");
    printf("\n--- 4. 极限边界：将类方法置于三元表达式中 ---\n");
    int dynamicCondition = 1;
    Engine__Core__WeaponSystem * evilGeneratedWeapon = (dynamicCondition > 0) ? Engine__Core__WeaponSystem_createLaserBeam(&nupa_Engine__Core__WeaponSystem_class, sel_registerName("createLaserBeam")) : NULL;
    printf("[复合断言] 恶心边界表达式完美解析！\n");
    printf("          -> 动态生产的边界武器名称: %s\n", ((struct nupa_Engine__Core__WeaponSystem_vtable *)evilGeneratedWeapon->isa->vtable)->weaponName(evilGeneratedWeapon, sel_registerName("weaponName")));
    printf("\n--- 5. 正在释放星际军事资产内存... ---\n");
    ((struct nupa_NPObject_vtable *)customCannon->isa->vtable)->release(customCannon, sel_registerName("release"));
    ((struct nupa_NPObject_vtable *)myFleetFlagship->isa->vtable)->release(myFleetFlagship, sel_registerName("release"));
    ((struct nupa_NPObject_vtable *)evilGeneratedWeapon->isa->vtable)->release(evilGeneratedWeapon, sel_registerName("release"));
    printf("\n====================================================================\n");
    printf(">>> 卧槽！静态类方法寻址与多层 Block 投递完美闭合，无解！ <<<\n");
    printf("====================================================================\n");
  }
  return 0;
}

