// Generated by nupac
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_NPCriticalException_vtable;
struct nupa_NPRecoverableException_vtable;
struct nupa_NPMatrixSpace_vtable;
struct nupa_NPChaosEngine_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_NPCriticalException_vtable_index_initWithReason_ 4
#define nupa_NPRecoverableException_vtable_index_initWithReason_ 4
#define nupa_NPMatrixSpace_vtable_index_initWithDimension_ 4
#define nupa_NPMatrixSpace_vtable_index_fillMatrixWithSeed_ 5
#define nupa_NPMatrixSpace_vtable_index_getValueAtRow_col_ 6
#define nupa_NPMatrixSpace_vtable_index_dealloc 3
#define nupa_NPChaosEngine_vtable_index_executeChaosLoopWithLevel_ 4
#define nupa_NPChaosEngine_vtable_index_init 2
#define nupa_NPChaosEngine_vtable_index_dealloc 3

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_getValueAtRow_col_ = {.name = "getValueAtRow_col_", .hash = 0x2DB2A4F7};
static const SEL __nupa_sel_initWithReason_ = {.name = "initWithReason_", .hash = 0x23383BC0};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_initWithDimension_ = {.name = "initWithDimension_", .hash = 0x45146046};
static const SEL __nupa_sel_fillMatrixWithSeed_ = {.name = "fillMatrixWithSeed_", .hash = 0x27ACB6A9};
static const SEL __nupa_sel_executeChaosLoopWithLevel_ = {.name = "executeChaosLoopWithLevel_", .hash = 0x3CD9A575};

typedef struct NPObject NPObject;
typedef struct NPCriticalException NPCriticalException;
typedef struct NPRecoverableException NPRecoverableException;
typedef struct NPMatrixSpace NPMatrixSpace;
typedef struct NPChaosEngine NPChaosEngine;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * NPCriticalException_initWithReason_(NPObject * self, SEL _cmd, const char * r);
NPClass * NPCriticalException_getClass(NPClass * self, SEL _cmd);
NPObject * NPRecoverableException_initWithReason_(NPObject * self, SEL _cmd, const char * r);
NPClass * NPRecoverableException_getClass(NPClass * self, SEL _cmd);
NPObject * NPMatrixSpace_initWithDimension_(NPObject * self, SEL _cmd, int dim);
void NPMatrixSpace_fillMatrixWithSeed_(NPObject * self, SEL _cmd, int seed);
int NPMatrixSpace_getValueAtRow_col_(NPObject * self, SEL _cmd, int r, int c);
void NPMatrixSpace_dealloc(NPObject * self, SEL _cmd);
NPClass * NPMatrixSpace_getClass(NPClass * self, SEL _cmd);
void NPChaosEngine_executeChaosLoopWithLevel_(NPObject * self, SEL _cmd, int level);
NPObject * NPChaosEngine_init(NPObject * self, SEL _cmd);
void NPChaosEngine_dealloc(NPObject * self, SEL _cmd);
NPClass * NPChaosEngine_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass nupa_NPObject_class;
extern NPClass nupa_NPCriticalException_class;
extern NPClass nupa_NPRecoverableException_class;
extern NPClass nupa_NPMatrixSpace_class;
extern NPClass nupa_NPChaosEngine_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct NPCriticalException {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * reason;
};
typedef struct NPCriticalException NPCriticalException;
struct nupa_NPCriticalException_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithReason_)(NPObject *, SEL, const char *);
};
struct nupa_NPCriticalException_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPRecoverableException {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * reason;
};
typedef struct NPRecoverableException NPRecoverableException;
struct nupa_NPRecoverableException_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithReason_)(NPObject *, SEL, const char *);
};
struct nupa_NPRecoverableException_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPMatrixSpace {
    struct NPClass *isa;
    uint32_t retain_count;
    int * * _rawGrid;
    int _dimension;
};
typedef struct NPMatrixSpace NPMatrixSpace;
struct nupa_NPMatrixSpace_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithDimension_)(NPObject *, SEL, int);
    void (*fillMatrixWithSeed_)(NPObject *, SEL, int);
    int (*getValueAtRow_col_)(NPObject *, SEL, int, int);
};
struct nupa_NPMatrixSpace_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPChaosEngine {
    struct NPClass *isa;
    uint32_t retain_count;
    NPMatrixSpace * _space;
};
typedef struct NPChaosEngine NPChaosEngine;
struct nupa_NPChaosEngine_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*executeChaosLoopWithLevel_)(NPObject *, SEL, int);
};
struct nupa_NPChaosEngine_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
NPObject * NPCriticalException_initWithReason_(NPObject * self, SEL _cmd, const char * r) {
    struct NPCriticalException * _self = ((struct NPCriticalException *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct NPCriticalException *)(self))->reason = r;
            }
        }
        return self;
    }
}

NPClass * NPCriticalException_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPCriticalException_class;
}

NPObject * NPRecoverableException_initWithReason_(NPObject * self, SEL _cmd, const char * r) {
    struct NPRecoverableException * _self = ((struct NPRecoverableException *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct NPRecoverableException *)(self))->reason = r;
            }
        }
        return self;
    }
}

NPClass * NPRecoverableException_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPRecoverableException_class;
}

NPObject * NPMatrixSpace_initWithDimension_(NPObject * self, SEL _cmd, int dim) {
    struct NPMatrixSpace * _self = ((struct NPMatrixSpace *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct NPMatrixSpace *)(self))->_dimension = dim;
                ((struct NPMatrixSpace *)(self))->_rawGrid = ((int * *)(malloc(sizeof(int *) * dim)));
                for (int i = 0; i < dim; i++) {
                    {
                        ((struct NPMatrixSpace *)(self))->_rawGrid[i] = ((int *)(malloc(sizeof(int) * dim)));
                    }
                }
            }
        }
        return self;
    }
}

void NPMatrixSpace_fillMatrixWithSeed_(NPObject * self, SEL _cmd, int seed) {
    struct NPMatrixSpace * _self = ((struct NPMatrixSpace *)(self));
    {
        for (int i = 0; i < ((struct NPMatrixSpace *)(self))->_dimension; i++) {
            {
                for (int j = 0; j < ((struct NPMatrixSpace *)(self))->_dimension; j++) {
                    {
                        *(*(((struct NPMatrixSpace *)(self))->_rawGrid + i) + j) = i + j * seed;
                    }
                }
            }
        }
    }
}

int NPMatrixSpace_getValueAtRow_col_(NPObject * self, SEL _cmd, int r, int c) {
    struct NPMatrixSpace * _self = ((struct NPMatrixSpace *)(self));
    {
        if (r >= ((struct NPMatrixSpace *)(self))->_dimension || c >= ((struct NPMatrixSpace *)(self))->_dimension || r < 0 || c < 0) {
            {
                return -1;
            }
        }
        return ((struct NPMatrixSpace *)(self))->_rawGrid[r][c];
    }
}

void NPMatrixSpace_dealloc(NPObject * self, SEL _cmd) {
    struct NPMatrixSpace * _self = ((struct NPMatrixSpace *)(self));
    {
        for (int i = 0; i < ((struct NPMatrixSpace *)(self))->_dimension; i++) {
            {
                free(((struct NPMatrixSpace *)(self))->_rawGrid[i]);
            }
        }
        free(((struct NPMatrixSpace *)(self))->_rawGrid);
        np_object_dealloc(self);
    }
}

NPClass * NPMatrixSpace_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPMatrixSpace_class;
}

void NPChaosEngine_executeChaosLoopWithLevel_(NPObject * self, SEL _cmd, int level) {
    struct NPChaosEngine * _self = ((struct NPChaosEngine *)(self));
    {
        printf("[引擎] 进入第一层 @try 作用域...\n");
        {
            id __nupa_exception_0 = NULL;
            __nupa_try_0:
            {
                printf("[引擎] 尝试读取合法坐标 (1,1): %d\n", ((struct nupa_NPMatrixSpace_vtable *)((struct NPChaosEngine *)(self))->_space->isa->vtable)->getValueAtRow_col_(((struct NPChaosEngine *)(self))->_space, __nupa_sel_getValueAtRow_col_, 1, 1));
                printf("[引擎] 故意触发越界，尝试读取坐标 (5,5)...\n");
                if (5 >= ((struct NPMatrixSpace *)(((struct NPChaosEngine *)(self))->_space))->_dimension || 5 >= ((struct NPMatrixSpace *)(((struct NPChaosEngine *)(self))->_space))->_dimension) {
                    {
                        NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_NPRecoverableException_class, __nupa_sel_alloc));
                        NPRecoverableException * ex = ((struct nupa_NPRecoverableException_vtable *)__nupa_tmp_0->isa->vtable)->initWithReason_(__nupa_tmp_0, __nupa_sel_initWithReason_, "矩阵索引越界(可恢复)");
                        {
                            __nupa_exception_0 = ex;
                            goto __nupa_catch_0;
                        }
                    }
                }
                int dynamicBoom = ((struct nupa_NPMatrixSpace_vtable *)((struct NPChaosEngine *)(self))->_space->isa->vtable)->getValueAtRow_col_(((struct NPChaosEngine *)(self))->_space, __nupa_sel_getValueAtRow_col_, 5, 5);
                printf("[引擎] 这行代码不应该被执行！返回解: %d\n", dynamicBoom);
            }
            goto __nupa_finally_0;
            __nupa_catch_0:
            id recEx;
            recEx = __nupa_exception_0;
            {
                printf("\n【一级 @catch 成功拦截】捕获原因: %s\n", ((struct NPRecoverableException *)(recEx))->reason);
                printf("[引擎] 启动二级嵌套 @try，尝试内部修复流...\n");
                {
                    id __nupa_exception_1 = NULL;
                    __nupa_try_1:
                    {
                        if (level > 0) {
                            {
                                printf("[引擎] 内部修复失败！故意在 @catch 中再次抛出严重级别的 NPCriticalException...\n");
                                NPObject *__nupa_tmp_1 = (NPObject_alloc(&nupa_NPCriticalException_class, __nupa_sel_alloc));
                                NPCriticalException * critEx = ((struct nupa_NPCriticalException_vtable *)__nupa_tmp_1->isa->vtable)->initWithReason_(__nupa_tmp_1, __nupa_sel_initWithReason_, "二级嵌套引发的不可逆毁灭性异常");
                                nupa_release(recEx);
                                {
                                    __nupa_exception_0 = critEx;
                                    goto __nupa_finally_0;
                                }
                            }
                        }
                    }
                    goto __nupa_finally_1;
                    __nupa_catch_1:
                    id critEx;
                    critEx = __nupa_exception_1;
                    {
                        printf("【二级嵌套 @catch 成功拦截】捕获原因: %s\n", ((struct NPCriticalException *)(critEx))->reason);
                        printf("[引擎] 正在做最后向上传递抛出...\n");
                        {
                            __nupa_exception_0 = critEx;
                            goto __nupa_finally_0;
                        }
                    }
                    goto __nupa_finally_1;
                    __nupa_finally_1:
                    ;
                }
            }
            goto __nupa_finally_0;
            __nupa_finally_0:
            ;
        }
    }
}

NPObject * NPChaosEngine_init(NPObject * self, SEL _cmd) {
    struct NPChaosEngine * _self = ((struct NPChaosEngine *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct NPChaosEngine *)(self))->_space = ({ NPObject *__nupa_tmp_2 = (NPObject_alloc(&nupa_NPMatrixSpace_class, __nupa_sel_alloc)); ((struct nupa_NPMatrixSpace_vtable *)__nupa_tmp_2->isa->vtable)->initWithDimension_(__nupa_tmp_2, __nupa_sel_initWithDimension_, 3); });
                ((struct nupa_NPMatrixSpace_vtable *)((struct NPChaosEngine *)(self))->_space->isa->vtable)->fillMatrixWithSeed_(((struct NPChaosEngine *)(self))->_space, __nupa_sel_fillMatrixWithSeed_, 5);
            }
        }
        return self;
    }
}

void NPChaosEngine_dealloc(NPObject * self, SEL _cmd) {
    struct NPChaosEngine * _self = ((struct NPChaosEngine *)(self));
    {
        nupa_release(((struct NPChaosEngine *)(self))->_space);
        np_object_dealloc(self);
    }
}

NPClass * NPChaosEngine_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPChaosEngine_class;
}

int main(int argc, const char * * argv) {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            printf("==================================================\n");
            printf(">>>     nupac 编译器「混沌交织与多重重入」压测     <<<\n");
            printf("==================================================\n\n");
            NPObject *__nupa_tmp_3 = (NPObject_alloc(&nupa_NPChaosEngine_class, __nupa_sel_alloc));
            NPChaosEngine * engine = ((struct nupa_NPChaosEngine_vtable *)__nupa_tmp_3->isa->vtable)->init(__nupa_tmp_3, __nupa_sel_init);
            {
                id __nupa_exception_2 = NULL;
                __nupa_try_2:
                {
                    ((struct nupa_NPChaosEngine_vtable *)engine->isa->vtable)->executeChaosLoopWithLevel_(engine, __nupa_sel_executeChaosLoopWithLevel_, 1);
                }
                goto __nupa_finally_2;
                __nupa_catch_2:
                id finalEx;
                finalEx = __nupa_exception_2;
                {
                    printf("\n【顶层 main 成功捕获终极异常】: %s\n", ((struct NPCriticalException *)(finalEx))->reason);
                    nupa_release(finalEx);
                }
                goto __nupa_finally_2;
                __nupa_finally_2:
                ;
            }
            nupa_release(engine);
            printf("\n==================================================\n");
            printf(">>>      卧槽！多重嵌套重入异常也通过了！       <<<\n");
            printf("==================================================\n");
        }
        nupa_autoreleasepool_pop(__pool);
    }
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_NPCriticalException_vtable nupa_NPCriticalException_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithReason_ = NPCriticalException_initWithReason_,
};

struct nupa_NPRecoverableException_vtable nupa_NPRecoverableException_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithReason_ = NPRecoverableException_initWithReason_,
};

struct nupa_NPMatrixSpace_vtable nupa_NPMatrixSpace_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPMatrixSpace_dealloc,
    .initWithDimension_ = NPMatrixSpace_initWithDimension_,
    .fillMatrixWithSeed_ = NPMatrixSpace_fillMatrixWithSeed_,
    .getValueAtRow_col_ = NPMatrixSpace_getValueAtRow_col_,
};

struct nupa_NPChaosEngine_vtable nupa_NPChaosEngine_vtable_inst = {
    .init = NPChaosEngine_init,
    .dealloc = NPChaosEngine_dealloc,
    .executeChaosLoopWithLevel_ = NPChaosEngine_executeChaosLoopWithLevel_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_NPCriticalException_meta_vtable nupa_NPCriticalException_meta_vtable_inst = {
    .class = NPCriticalException_getClass,
};

struct nupa_NPRecoverableException_meta_vtable nupa_NPRecoverableException_meta_vtable_inst = {
    .class = NPRecoverableException_getClass,
};

struct nupa_NPMatrixSpace_meta_vtable nupa_NPMatrixSpace_meta_vtable_inst = {
    .class = NPMatrixSpace_getClass,
};

struct nupa_NPChaosEngine_meta_vtable nupa_NPChaosEngine_meta_vtable_inst = {
    .class = NPChaosEngine_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_NPCriticalException_class;
NPClass nupa_NPRecoverableException_class;
NPClass nupa_NPMatrixSpace_class;
NPClass nupa_NPChaosEngine_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPCriticalException_class = (NPClass){
        .name = "NPCriticalException",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPCriticalException),
        .vtable = &nupa_NPCriticalException_vtable_inst,
        .class_vtable = &nupa_NPCriticalException_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPRecoverableException_class = (NPClass){
        .name = "NPRecoverableException",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPRecoverableException),
        .vtable = &nupa_NPRecoverableException_vtable_inst,
        .class_vtable = &nupa_NPRecoverableException_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPMatrixSpace_class = (NPClass){
        .name = "NPMatrixSpace",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPMatrixSpace),
        .vtable = &nupa_NPMatrixSpace_vtable_inst,
        .class_vtable = &nupa_NPMatrixSpace_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPChaosEngine_class = (NPClass){
        .name = "NPChaosEngine",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct NPChaosEngine),
        .vtable = &nupa_NPChaosEngine_vtable_inst,
        .class_vtable = &nupa_NPChaosEngine_meta_vtable_inst,
        .protocol_count = 0,
    };
}
