// Generated by nupac
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
struct nupa_NPObject_vtable;
struct nupa_NPObject_meta_vtable;
struct nupa_CarrierCommandCenter_vtable;
struct nupa_CarrierCommandCenter_meta_vtable;
struct nupa_TacticalMechEntity_vtable;
struct nupa_TacticalMechEntity_meta_vtable;

static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nupa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nupa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nupa_sel_initWithId_fleet_ = {.name = "initWithId:fleet:", .hash = 0x3EA8B376};
static const SEL __nupa_sel_shutdownCarrierShields = {.name = "shutdownCarrierShields", .hash = 0x67677025};
static const SEL __nupa_sel_carrierId = {.name = "carrierId", .hash = 0x44FEF35A};
static const SEL __nupa_sel_setCarrierId_ = {.name = "setCarrierId_", .hash = 0xD9A36AD9};
static const SEL __nupa_sel_fleetCode = {.name = "fleetCode", .hash = 0xFB423ADE};
static const SEL __nupa_sel_assignedMech = {.name = "assignedMech", .hash = 0x460C99E4};
static const SEL __nupa_sel_setAssignedMech_ = {.name = "setAssignedMech_", .hash = 0x3BD31823};
static const SEL __nupa_sel_initWithMechId_ = {.name = "initWithMechId:", .hash = 0xD69A4C2B};
static const SEL __nupa_sel_queryTacticalUplink = {.name = "queryTacticalUplink", .hash = 0xB7D69C23};
static const SEL __nupa_sel_mechId = {.name = "mechId", .hash = 0x11E4EDC1};
static const SEL __nupa_sel_setMechId_ = {.name = "setMechId_", .hash = 0xA47819FC};
static const SEL __nupa_sel_masterCarrier = {.name = "masterCarrier", .hash = 0xD2B35CC9};
static const SEL __nupa_sel_setMasterCarrier_ = {.name = "setMasterCarrier_", .hash = 0x37CE0F64};

typedef struct NPObject NPObject;
typedef struct CarrierCommandCenter CarrierCommandCenter;
typedef struct TacticalMechEntity TacticalMechEntity;

NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
NPObject * CarrierCommandCenter_initWithId_fleet_(NPObject * self, SEL _cmd, int cid, const char * code);
void CarrierCommandCenter_shutdownCarrierShields(NPObject * self, SEL _cmd);
int CarrierCommandCenter_carrierId(NPObject * self, SEL _cmd);
void CarrierCommandCenter_setCarrierId_(NPObject * self, SEL _cmd, int value);
const char * CarrierCommandCenter_fleetCode(NPObject * self, SEL _cmd);
TacticalMechEntity * CarrierCommandCenter_assignedMech(NPObject * self, SEL _cmd);
void CarrierCommandCenter_setAssignedMech_(NPObject * self, SEL _cmd, TacticalMechEntity * value);
NPObject * TacticalMechEntity_initWithMechId_(NPObject * self, SEL _cmd, int mid);
void TacticalMechEntity_queryTacticalUplink(NPObject * self, SEL _cmd);
int TacticalMechEntity_mechId(NPObject * self, SEL _cmd);
void TacticalMechEntity_setMechId_(NPObject * self, SEL _cmd, int value);
CarrierCommandCenter * TacticalMechEntity_masterCarrier(NPObject * self, SEL _cmd);
void TacticalMechEntity_setMasterCarrier_(NPObject * self, SEL _cmd, CarrierCommandCenter * value);
void CarrierCommandCenter_dealloc(NPObject * self, SEL _cmd);
void TacticalMechEntity_dealloc(NPObject * self, SEL _cmd);
NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * self);
void nupa_release(NPObject * obj);
NPObject * nupa_retain(NPObject * obj);
int main(int argc, const char * argv[]);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * CarrierCommandCenter_getClass(NPClass * self, SEL _cmd);
NPClass * TacticalMechEntity_getClass(NPClass * self, SEL _cmd);

struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_CarrierCommandCenter_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initWithId_fleet_)(NPObject *, SEL, int, const char *);
    void (*shutdownCarrierShields)(NPObject *, SEL);
    int (*carrierId)(NPObject *, SEL);
    void (*setCarrierId_)(NPObject *, SEL, int);
    const char * (*fleetCode)(NPObject *, SEL);
    TacticalMechEntity * (*assignedMech)(NPObject *, SEL);
    void (*setAssignedMech_)(NPObject *, SEL, TacticalMechEntity *);
};
struct nupa_CarrierCommandCenter_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_TacticalMechEntity_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initWithMechId_)(NPObject *, SEL, int);
    void (*queryTacticalUplink)(NPObject *, SEL);
    int (*mechId)(NPObject *, SEL);
    void (*setMechId_)(NPObject *, SEL, int);
    CarrierCommandCenter * (*masterCarrier)(NPObject *, SEL);
    void (*setMasterCarrier_)(NPObject *, SEL, CarrierCommandCenter *);
};
struct nupa_TacticalMechEntity_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct CarrierCommandCenter {
    struct NPClass *isa;
    uint32_t retain_count;
    int _carrierId;
    const char * _fleetCode;
    TacticalMechEntity * _assignedMech;
};
typedef struct CarrierCommandCenter CarrierCommandCenter;

struct TacticalMechEntity {
    struct NPClass *isa;
    uint32_t retain_count;
    int _mechId;
    CarrierCommandCenter * _masterCarrier;
};
typedef struct TacticalMechEntity TacticalMechEntity;

extern NPClass nupa_NPObject_class;
extern NPClass nupa_CarrierCommandCenter_class;
extern NPClass nupa_TacticalMechEntity_class;
void nupa_meta_init(void);

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct nupa_CarrierCommandCenter_vtable nupa_CarrierCommandCenter_vtable_inst = {
    .init = NPObject_init,
    .dealloc = CarrierCommandCenter_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initWithId_fleet_ = CarrierCommandCenter_initWithId_fleet_,
    .shutdownCarrierShields = CarrierCommandCenter_shutdownCarrierShields,
    .carrierId = CarrierCommandCenter_carrierId,
    .setCarrierId_ = CarrierCommandCenter_setCarrierId_,
    .fleetCode = CarrierCommandCenter_fleetCode,
    .assignedMech = CarrierCommandCenter_assignedMech,
    .setAssignedMech_ = CarrierCommandCenter_setAssignedMech_,
};

struct nupa_TacticalMechEntity_vtable nupa_TacticalMechEntity_vtable_inst = {
    .init = NPObject_init,
    .dealloc = TacticalMechEntity_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initWithMechId_ = TacticalMechEntity_initWithMechId_,
    .queryTacticalUplink = TacticalMechEntity_queryTacticalUplink,
    .mechId = TacticalMechEntity_mechId,
    .setMechId_ = TacticalMechEntity_setMechId_,
    .masterCarrier = TacticalMechEntity_masterCarrier,
    .setMasterCarrier_ = TacticalMechEntity_setMasterCarrier_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_CarrierCommandCenter_meta_vtable nupa_CarrierCommandCenter_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = CarrierCommandCenter_getClass,
};

struct nupa_TacticalMechEntity_meta_vtable nupa_TacticalMechEntity_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = TacticalMechEntity_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * CarrierCommandCenter_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * TacticalMechEntity_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nupa_NPObject_class;
NPClass nupa_CarrierCommandCenter_class;
NPClass nupa_TacticalMechEntity_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_CarrierCommandCenter_class = (NPClass){
        .name = "CarrierCommandCenter",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct CarrierCommandCenter),
        .vtable = &nupa_CarrierCommandCenter_vtable_inst,
        .class_vtable = &nupa_CarrierCommandCenter_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_TacticalMechEntity_class = (NPClass){
        .name = "TacticalMechEntity",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct TacticalMechEntity),
        .vtable = &nupa_TacticalMechEntity_vtable_inst,
        .class_vtable = &nupa_TacticalMechEntity_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = nupa_alloc(self);
  return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nupa_init(self);
  }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return;
  }
}

void NPObject_release(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    nupa_release(self);
  }
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nupa_retain(self);
  }
}

NPObject * CarrierCommandCenter_initWithId_fleet_(NPObject * self, SEL _cmd, int cid, const char * code) {
  struct CarrierCommandCenter * _self = (struct CarrierCommandCenter *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->_carrierId = cid;
      _self->_fleetCode = code;
      _self->_assignedMech = NULL;
    }
    return self;
  }
}

void CarrierCommandCenter_shutdownCarrierShields(NPObject * self, SEL _cmd) {
  struct CarrierCommandCenter * _self = (struct CarrierCommandCenter *)self;
  {
    printf("[战术控制] 正在下线母舰反应堆，准备触发静态 ARC 释放流...\n");
  }
}

int CarrierCommandCenter_carrierId(NPObject * self, SEL _cmd) {
  return ((struct CarrierCommandCenter *)self)->_carrierId;
}

void CarrierCommandCenter_setCarrierId_(NPObject * self, SEL _cmd, int value) {
  ((struct CarrierCommandCenter *)self)->_carrierId = value;
}

const char * CarrierCommandCenter_fleetCode(NPObject * self, SEL _cmd) {
  return ((struct CarrierCommandCenter *)self)->_fleetCode;
}

TacticalMechEntity * CarrierCommandCenter_assignedMech(NPObject * self, SEL _cmd) {
  return ((struct CarrierCommandCenter *)self)->_assignedMech;
}

void CarrierCommandCenter_setAssignedMech_(NPObject * self, SEL _cmd, TacticalMechEntity * value) {
  ((struct CarrierCommandCenter *)self)->_assignedMech = value;
}

NPObject * TacticalMechEntity_initWithMechId_(NPObject * self, SEL _cmd, int mid) {
  struct TacticalMechEntity * _self = (struct TacticalMechEntity *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->_mechId = mid;
      _self->_masterCarrier = NULL;
    }
    return self;
  }
}

void TacticalMechEntity_queryTacticalUplink(NPObject * self, SEL _cmd) {
  struct TacticalMechEntity * _self = (struct TacticalMechEntity *)self;
  {
    if (_self->_masterCarrier)     {
      printf("[机甲-%d] 链路正常，当前弱引用母舰仍然在线: 舰队编号=%s\n", _self->_mechId, ({ NPObject *__nupa_tmp_1 = (_self->_masterCarrier); __nupa_tmp_1 ? ((struct nupa_CarrierCommandCenter_vtable *)__nupa_tmp_1->isa->vtable)->fleetCode(__nupa_tmp_1, sel_registerName("fleetCode")) : 0; }));
    }
    else     {
      printf("[机甲-%d] 警报！弱引用母舰已静态析构，该 __weak 指针已自动清零(nil)！\n", _self->_mechId);
    }
  }
}

int TacticalMechEntity_mechId(NPObject * self, SEL _cmd) {
  return ((struct TacticalMechEntity *)self)->_mechId;
}

void TacticalMechEntity_setMechId_(NPObject * self, SEL _cmd, int value) {
  ((struct TacticalMechEntity *)self)->_mechId = value;
}

CarrierCommandCenter * TacticalMechEntity_masterCarrier(NPObject * self, SEL _cmd) {
  return ((struct TacticalMechEntity *)self)->_masterCarrier;
}

void TacticalMechEntity_setMasterCarrier_(NPObject * self, SEL _cmd, CarrierCommandCenter * value) {
  nupa_weak_unregister((NPObject **)&((struct TacticalMechEntity *)self)->_masterCarrier);
  ((struct TacticalMechEntity *)self)->_masterCarrier = value;
  nupa_weak_register((NPObject **)&((struct TacticalMechEntity *)self)->_masterCarrier, (NPObject *)value);
}

void CarrierCommandCenter_dealloc(NPObject * self, SEL _cmd) {
  struct CarrierCommandCenter * _self = (struct CarrierCommandCenter *)self;
  {
    printf("[母舰析构] 指挥母舰 [%s] 正在静态断开所有物理链路并释放资源...\n", _self->_fleetCode);
    if (_self->_assignedMech)     {
      ({ NPObject *__nupa_tmp_2 = (_self->_assignedMech); __nupa_tmp_2 ? ((struct nupa_NPObject_vtable *)__nupa_tmp_2->isa->vtable)->release(__nupa_tmp_2, sel_registerName("release")) : 0; });
    }
    NPObject_dealloc(self, sel_registerName("dealloc"));
  }
}

void TacticalMechEntity_dealloc(NPObject * self, SEL _cmd) {
  struct TacticalMechEntity * _self = (struct TacticalMechEntity *)self;
  {
    printf("[机甲销毁] 战术机甲-%d 物理框架已安全拆卸。\n", _self->_mechId);
    NPObject_dealloc(self, sel_registerName("dealloc"));
  }
}

NPObject * nupa_alloc(struct NPClass * cls);

NPObject * nupa_init(NPObject * self);

void nupa_release(NPObject * obj);

NPObject * nupa_retain(NPObject * obj);

int main(int argc, const char * argv[]) {
  nupa_meta_init();
  {
    printf("====================================================================\n");
    printf(">>>    nupac 编译器「静态弱引用 __weak 与零污染」镜像健壮性压测   <<<\n");
    printf("====================================================================\n\n");
    printf("--- 1. 建立指挥母舰与战术机甲的交叉强弱引用 ---\n");
    NPObject *__nupa_tmp_3 = (NPObject_alloc(&nupa_CarrierCommandCenter_class, sel_registerName("alloc")));
    CarrierCommandCenter * alphaCarrier = ((struct nupa_CarrierCommandCenter_vtable *)__nupa_tmp_3->isa->vtable)->initWithId_fleet_(__nupa_tmp_3, sel_registerName("initWithId:fleet:"), 8008, "Hyperion-XII");
    NPObject *__nupa_tmp_4 = (NPObject_alloc(&nupa_TacticalMechEntity_class, sel_registerName("alloc")));
    TacticalMechEntity * gundamMech = ((struct nupa_TacticalMechEntity_vtable *)__nupa_tmp_4->isa->vtable)->initWithMechId_(__nupa_tmp_4, sel_registerName("initWithMechId:"), 3);
    ((struct nupa_CarrierCommandCenter_vtable *)(alphaCarrier)->isa->vtable)->setAssignedMech_(alphaCarrier, sel_registerName("setAssignedMech:"), gundamMech);
    ((struct nupa_TacticalMechEntity_vtable *)(gundamMech)->isa->vtable)->setMasterCarrier_(gundamMech, sel_registerName("setMasterCarrier:"), alphaCarrier);
    ((struct nupa_TacticalMechEntity_vtable *)(gundamMech)->isa->vtable)->queryTacticalUplink(gundamMech, sel_registerName("queryTacticalUplink"));
    printf("\n--- 2. 验证多个局部 __weak 指针同时指向同一个强对象 ---\n");
    __block CarrierCommandCenter * __attribute__((cleanup(nupa_weak_auto_cleanup))) tacticalMonitor1 = alphaCarrier;
    nupa_weak_register((NPObject**)&tacticalMonitor1, (NPObject*)alphaCarrier);
    __block CarrierCommandCenter * __attribute__((cleanup(nupa_weak_auto_cleanup))) tacticalMonitor2 = alphaCarrier;
    nupa_weak_register((NPObject**)&tacticalMonitor2, (NPObject*)alphaCarrier);
    printf("[初始弱指针快照]：\n");
    printf("          -> tacticalMonitor1 状态: %s\n", tacticalMonitor1 ? "有效指针" : "nil");
    printf("          -> tacticalMonitor2 状态: %s\n", tacticalMonitor2 ? "有效指针" : "nil");
    printf("\n--- 3. 测试 Block 闭包内部对 __weak 指针的静态安全捕获与执行 ---\n");
    __block int combatTelemetryRuns = 0;
    void (^combatUplinkBlock)(void) = ^void() {
  combatTelemetryRuns++;
  if (tacticalMonitor1)   {
    printf("[战术闭包] 运行第 %d 次同步，母舰依然存活：%s\n", combatTelemetryRuns, ((struct nupa_CarrierCommandCenter_vtable *)(tacticalMonitor1)->isa->vtable)->fleetCode(tacticalMonitor1, sel_registerName("fleetCode")));
  }
  else   {
    printf("[战术闭包] 运行第 %d 次同步，监测到目标母舰已沉没，弱指针安全置空。\n", combatTelemetryRuns);
  }
}
;
    combatUplinkBlock();
    printf("\n--- 4. 核心压测：彻底释放强引用母舰，验证所有衍生弱指针静态全归零 ---\n");
    ((struct nupa_CarrierCommandCenter_vtable *)(alphaCarrier)->isa->vtable)->shutdownCarrierShields(alphaCarrier, sel_registerName("shutdownCarrierShields"));
    ((struct nupa_NPObject_vtable *)(alphaCarrier)->isa->vtable)->release(alphaCarrier, sel_registerName("release"));
    alphaCarrier = NULL;
    printf("\n[静态度量清除断言]：\n");
    ((struct nupa_TacticalMechEntity_vtable *)(gundamMech)->isa->vtable)->queryTacticalUplink(gundamMech, sel_registerName("queryTacticalUplink"));
    printf("[局部弱指针清除断言]：\n");
    printf("          -> 销毁后 tacticalMonitor1 状态: %s (预期: 成功清零)\n", tacticalMonitor1 ? "未清空(Bug)" : "成功清零(nil)");
    printf("          -> 销毁后 tacticalMonitor2 状态: %s (预期: 成功清零)\n", tacticalMonitor2 ? "未清空(Bug)" : "成功清零(nil)");
    combatUplinkBlock();
    printf("\n--- 5. 混合边界守门员：三元表达式内包含带副作用的已置空弱指针消息发送 ---\n");
    int isTacticalNetOnline = 1;
    int carrierStepCounter = 88888;
    char * finalFleetReport = (isTacticalNetOnline > 0) ? ({ NPObject *__nupa_tmp_5 = ((carrierStepCounter++, tacticalMonitor2)); __nupa_tmp_5 ? ((struct nupa_CarrierCommandCenter_vtable *)__nupa_tmp_5->isa->vtable)->fleetCode(__nupa_tmp_5, sel_registerName("fleetCode")) : 0; }) : "OFFLINE";
    printf("[终极弱引用收网断言] 弱指针置空机制与自增优先级语法树完全融合！\n");
    printf("          -> 副作用自增计数器最终值: %d (预期: 88889)\n", carrierStepCounter);
    printf("          -> 弱引用置空后的安全返回报告: %s (预期: (null) 或 空指针安全值)\n", finalFleetReport ? finalFleetReport : "nil安全拦截");
    printf("\n--- 6. 正在释放战术机甲实体... ---\n");
    ((struct nupa_NPObject_vtable *)(gundamMech)->isa->vtable)->release(gundamMech, sel_registerName("release"));
    printf("\n====================================================================\n");
    printf(">>> 奇迹！静态弱引用机制镜像高压稳定性测试 100% 完美通关！       <<<\n");
    printf("====================================================================\n");
  }
  return 0;
}

