// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Game_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Game_vtable_index_initBoard 4
#define nupa_Game_vtable_index_play_player_ 5

static const SEL __nupa_sel_board = {.name = "board", .hash = 0xEF92FE2B};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_initBoard = {.name = "initBoard", .hash = 0xA9928889};
static const SEL __nupa_sel_play_player_ = {.name = "play_player_", .hash = 0xDDCB8502};

typedef struct NPObject NPObject;
typedef struct Game Game;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
void Game_initBoard(NPObject * self, SEL _cmd);
void Game_play_player_(NPObject * self, SEL _cmd, int pos, int p);
int * Game_board(NPObject * self, SEL _cmd);
void Game_setBoard_(NPObject * self, SEL _cmd, int * value);
NPClass * Game_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Game_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Game {
    struct NPClass *isa;
    uint32_t retain_count;
    int _board[9];
};
typedef struct Game Game;
struct nupa_Game_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*initBoard)(NPObject *, SEL);
    void (*play_player_)(NPObject *, SEL, int, int);
    int * (*board)(NPObject *, SEL);
    void (*setBoard_)(NPObject *, SEL, int *);
};
struct nupa_Game_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
void Game_initBoard(NPObject * self, SEL _cmd) {
    struct Game * _self = ((struct Game *)(self));
    {
        for (int i = 0; i < 9; i++) {
            {
                ((struct nupa_Game_vtable *)self->isa->vtable)->board(self, __nupa_sel_board)[i] = 0;
            }
        }
    }
}

void Game_play_player_(NPObject * self, SEL _cmd, int pos, int p) {
    struct Game * _self = ((struct Game *)(self));
    {
        if (pos >= 0 && pos < 9) {
            {
                ((struct nupa_Game_vtable *)self->isa->vtable)->board(self, __nupa_sel_board)[pos] = p;
            }
        }
    }
}

int * Game_board(NPObject * self, SEL _cmd) {
    return ((struct Game *)(self))->_board;
}

void Game_setBoard_(NPObject * self, SEL _cmd, int * value) {
    memcpy(&((struct Game *)(self))->_board, value, sizeof(((struct Game *)(0))->_board));
}

NPClass * Game_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Game_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    Game * game = NPObject_alloc(&nupa_Game_class, __nupa_sel_alloc);
    ((struct nupa_Game_vtable *)game->isa->vtable)->initBoard(game, __nupa_sel_initBoard);
    ((struct nupa_Game_vtable *)game->isa->vtable)->play_player_(game, __nupa_sel_play_player_, 4, 1);
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Game_vtable nupa_Game_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initBoard = Game_initBoard,
    .play_player_ = Game_play_player_,
    .board = Game_board,
    .setBoard_ = Game_setBoard_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Game_meta_vtable nupa_Game_meta_vtable_inst = {
    .class = Game_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Game_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Game_class = (NPClass){
        .name = "Game",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Game),
        .vtable = &nupa_Game_vtable_inst,
        .class_vtable = &nupa_Game_meta_vtable_inst,
        .protocol_count = 0,
    };
}
