// Generated by nupac
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable;
struct nupa_NPObject_vtable;
struct nupa_Core__Swarm__MechEntity_vtable;

#define nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable_index_init 2
#define nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable_index_pushPayload_ 4
#define nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable_index_popPayload 5
#define nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable_index_dealloc 3
#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Core__Swarm__MechEntity_vtable_index_initWithId_model_ 4
#define nupa_Core__Swarm__MechEntity_vtable_index_dealloc 3

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_initWithId_model_ = {.name = "initWithId_model_", .hash = 0x797D9C35};
static const SEL __nupa_sel_pushPayload_ = {.name = "pushPayload_", .hash = 0xCAEA5A66};
static const SEL __nupa_sel_popPayload = {.name = "popPayload", .hash = 0x824B1E7E};
static const SEL __nupa_sel_mechId = {.name = "mechId", .hash = 0x11E4EDC1};
static const SEL __nupa_sel_modelName = {.name = "modelName", .hash = 0x4A8A4B01};

typedef struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr;
typedef struct NPObject NPObject;
typedef struct Core__Swarm__MechEntity Core__Swarm__MechEntity;



// ─── Struct definitions (early) ───────────────────────

struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Core__Swarm__MechEntity {
    struct NPClass *isa;
    uint32_t retain_count;
    int _mechId;
    const char * _modelName;
};
typedef struct Core__Swarm__MechEntity Core__Swarm__MechEntity;
struct nupa_Core__Swarm__MechEntity_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithId_model_)(NPObject *, SEL, int, const char *);
    int (*mechId)(NPObject *, SEL);
    void (*setMechId_)(NPObject *, SEL, int);
    const char * (*modelName)(NPObject *, SEL);
};
struct nupa_Core__Swarm__MechEntity_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr {
    struct NPClass *isa;
    uint32_t retain_count;
    int _payloadCount;
    Core__Swarm__MechEntity * _slots[2];
};
typedef struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr;
struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*pushPayload_)(NPObject *, SEL, Core__Swarm__MechEntity *);
    Core__Swarm__MechEntity * (*popPayload)(NPObject *, SEL);
    int (*payloadCount)(NPObject *, SEL);
};
struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_meta_vtable {
    // (empty)
};

static int syncLoopCount = 0;
static id innerMech;

// ─── Block helper functions ──────────────────────────────

static void _block_fn_0(Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * packet) {
    syncLoopCount++;
    innerMech = ((struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable *)packet->isa->vtable)->popPayload(packet, __nupa_sel_popPayload);
    printf("[战术闭包内] 成功同步信号 -> 机甲ID: %d | 闭包计数: %d\n", innerMech ? ((struct nupa_Core__Swarm__MechEntity_vtable *)innerMech->isa->vtable)->mechId(innerMech, __nupa_sel_mechId) : 0, syncLoopCount);
}


NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * Core__Swarm__MechEntity_initWithId_model_(NPObject * self, SEL _cmd, int mid, const char * model);
void Core__Swarm__MechEntity_dealloc(NPObject * self, SEL _cmd);
int Core__Swarm__MechEntity_mechId(NPObject * self, SEL _cmd);
void Core__Swarm__MechEntity_setMechId_(NPObject * self, SEL _cmd, int value);
const char * Core__Swarm__MechEntity_modelName(NPObject * self, SEL _cmd);
NPClass * Core__Swarm__MechEntity_getClass(NPClass * self, SEL _cmd);
NPObject * Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_init(NPObject * self, SEL _cmd);
void Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_pushPayload_(NPObject * self, SEL _cmd, Core__Swarm__MechEntity * payload);
Core__Swarm__MechEntity * Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_popPayload(NPObject * self, SEL _cmd);
void Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_dealloc(NPObject * self, SEL _cmd);
int Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_payloadCount(NPObject * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_class;
extern NPClass nupa_NPObject_class;
extern NPClass nupa_Core__Swarm__MechEntity_class;
void nupa_meta_init(void);

// struct NPClass defined in object.h
// struct NPObject defined in object.h
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
NPObject * Core__Swarm__MechEntity_initWithId_model_(NPObject * self, SEL _cmd, int mid, const char * model) {
    struct Core__Swarm__MechEntity * _self = ((struct Core__Swarm__MechEntity *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct Core__Swarm__MechEntity *)(self))->_mechId = mid;
                ((struct Core__Swarm__MechEntity *)(self))->_modelName = model;
            }
        }
        return self;
    }
}

void Core__Swarm__MechEntity_dealloc(NPObject * self, SEL _cmd) {
    struct Core__Swarm__MechEntity * _self = ((struct Core__Swarm__MechEntity *)(self));
    {
        printf("[机甲销毁] 空间 [Core::Swarm] 战术机甲-%d (%s) 已完全静态熔断。\n", ((struct Core__Swarm__MechEntity *)(self))->_mechId, ((struct Core__Swarm__MechEntity *)(self))->_modelName);
        np_object_dealloc(self);
    }
}

int Core__Swarm__MechEntity_mechId(NPObject * self, SEL _cmd) {
    return ((struct Core__Swarm__MechEntity *)(self))->_mechId;
}

void Core__Swarm__MechEntity_setMechId_(NPObject * self, SEL _cmd, int value) {
    ((struct Core__Swarm__MechEntity *)(self))->_mechId = value;
}

const char * Core__Swarm__MechEntity_modelName(NPObject * self, SEL _cmd) {
    return ((struct Core__Swarm__MechEntity *)(self))->_modelName;
}

NPClass * Core__Swarm__MechEntity_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Core__Swarm__MechEntity_class;
}

NPObject * Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_init(NPObject * self, SEL _cmd) {
    struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * _self = ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount = 0;
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[0] = 0;
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[1] = 0;
            }
        }
        return self;
    }
}

void Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_pushPayload_(NPObject * self, SEL _cmd, Core__Swarm__MechEntity * payload) {
    struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * _self = ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self));
    {
        if (((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount < 2) {
            {
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount] = nupa_retain(payload);
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount++;
                printf("[安全通道] 跨空间泛型负载已注入物理槽，当前深度: %d\n", ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount);
            }
        } else {
            {
                printf("[安全通道] 警告：信道已满，拒绝写入！\n");
            }
        }
    }
}

Core__Swarm__MechEntity * Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_popPayload(NPObject * self, SEL _cmd) {
    struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * _self = ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self));
    {
        if (((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount > 0) {
            {
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount--;
                Core__Swarm__MechEntity * tempPayload = ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount];
                ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount] = 0;
                return nupa_autorelease(tempPayload);
            }
        }
        return 0;
    }
}

void Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_dealloc(NPObject * self, SEL _cmd) {
    struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * _self = ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self));
    {
        printf("[通道物理析构] 正在清空单态化跨空间物理插槽内存...\n");
        if (((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[0]) {
            nupa_release(((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[0]);
        }
        if (((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[1]) {
            nupa_release(((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_slots[1]);
        }
        np_object_dealloc(self);
    }
}

int Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_payloadCount(NPObject * self, SEL _cmd) {
    return ((struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr *)(self))->_payloadCount;
}

int main(int argc, const char * * argv) {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            printf("====================================================================\n");
            printf(">>>    nupac 编译器「命名空间+别名+零开销泛型」终极融合压测       <<<\n");
            printf("====================================================================\n\n");
            printf("--- 1. 实例化跨命名空间特化泛型类 ---\n");
            NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_class, __nupa_sel_alloc));
            Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * rawPacket = ((struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable *)__nupa_tmp_0->isa->vtable)->init(__nupa_tmp_0, __nupa_sel_init);
            NPObject *__nupa_tmp_1 = (NPObject_alloc(&nupa_Core__Swarm__MechEntity_class, __nupa_sel_alloc));
            Core__Swarm__MechEntity * m1 = ((struct nupa_Core__Swarm__MechEntity_vtable *)__nupa_tmp_1->isa->vtable)->initWithId_model_(__nupa_tmp_1, __nupa_sel_initWithId_model_, 901, "Gundam-Exia");
            NPObject *__nupa_tmp_2 = (NPObject_alloc(&nupa_Core__Swarm__MechEntity_class, __nupa_sel_alloc));
            Core__Swarm__MechEntity * m2 = ((struct nupa_Core__Swarm__MechEntity_vtable *)__nupa_tmp_2->isa->vtable)->initWithId_model_(__nupa_tmp_2, __nupa_sel_initWithId_model_, 902, "Gundam-Dynames");
            ((struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable *)rawPacket->isa->vtable)->pushPayload_(rawPacket, __nupa_sel_pushPayload_, m1);
            ((struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable *)rawPacket->isa->vtable)->pushPayload_(rawPacket, __nupa_sel_pushPayload_, m2);
            nupa_release(m1);
            nupa_release(m2);
            printf("\n--- 2. 验证使用 @using 泛型别名 SecTunnel 进行多态派发与数据还原 ---\n");
            NPObject * tunnelController = rawPacket;
            Core__Swarm__MechEntity * poppedMech = ((struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable *)tunnelController->isa->vtable)->popPayload(tunnelController, __nupa_sel_popPayload);
            printf("[别名还原断言] 成功取出特化跨空间机甲: ID=%d | 型号=%s\n", ((struct nupa_Core__Swarm__MechEntity_vtable *)poppedMech->isa->vtable)->mechId(poppedMech, __nupa_sel_mechId), ((struct nupa_Core__Swarm__MechEntity_vtable *)poppedMech->isa->vtable)->modelName(poppedMech, __nupa_sel_modelName));
            printf("\n--- 3. 验证跨命名空间泛型作为 Block 参数的静态 ARC 表现 ---\n");
            void (*tacticalUplinkBlock)(Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr * packet) = _block_fn_0;
            tacticalUplinkBlock(rawPacket);
            printf("\n--- 4. 终极融合守门员：跨命名空间泛型别名、方法路由与复合副作用完美大同 ---\n");
            int isCommandChainSecure = 1;
            int globalFusionStep = 55555;
            Core__Swarm__MechEntity * finalFusionMech = isCommandChainSecure > 0 ? ({ NPObject *__nupa_tmp_3 = (globalFusionStep++, tunnelController); ((struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable *)__nupa_tmp_3->isa->vtable)->popPayload(__nupa_tmp_3, __nupa_sel_popPayload); }) : 0;
            printf("[终极多维断言] 编译期单态化、命名空间隔离、别名展开与复合语法树 100% 收敛！\n");
            printf("          -> 复合副作用自增计数器: %d (预期: 55556)\n", globalFusionStep);
            printf("          -> 动态解密弹出的最终机甲型号: %s (预期: (null) / 因为先前已Pop空，或nil安全拦截)\n", finalFusionMech ? ((struct nupa_Core__Swarm__MechEntity_vtable *)finalFusionMech->isa->vtable)->modelName(finalFusionMech, __nupa_sel_modelName) : "nil安全拦截");
            printf("\n--- 5. 正在静态触发生命周期释放... ---\n");
            nupa_release(rawPacket);
            printf("\n====================================================================\n");
            printf(">>>  神迹！@namespace + @using + 单态化泛型 三位一体终极测试通过！  <<<\n");
            printf("====================================================================\n");
            ;
        }
        nupa_autoreleasepool_pop(__pool);
    }
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable_inst = {
    .init = Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_init,
    .dealloc = Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_dealloc,
    .pushPayload_ = Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_pushPayload_,
    .popPayload = Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_popPayload,
    .payloadCount = Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_payloadCount,
};

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Core__Swarm__MechEntity_vtable nupa_Core__Swarm__MechEntity_vtable_inst = {
    .init = NPObject_init,
    .dealloc = Core__Swarm__MechEntity_dealloc,
    .initWithId_model_ = Core__Swarm__MechEntity_initWithId_model_,
    .mechId = Core__Swarm__MechEntity_mechId,
    .setMechId_ = Core__Swarm__MechEntity_setMechId_,
    .modelName = Core__Swarm__MechEntity_modelName,
};

struct nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_meta_vtable nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_meta_vtable_inst = {
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Core__Swarm__MechEntity_meta_vtable nupa_Core__Swarm__MechEntity_meta_vtable_inst = {
    .class = Core__Swarm__MechEntity_getClass,
};

NPClass nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_class;
NPClass nupa_NPObject_class;
NPClass nupa_Core__Swarm__MechEntity_class;

void nupa_meta_init(void) {
    nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_class = (NPClass){
        .name = "Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr),
        .vtable = &nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_vtable_inst,
        .class_vtable = &nupa_Network__Security__QuantumPacket_Core__Swarm__MechEntity_ptr_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Core__Swarm__MechEntity_class = (NPClass){
        .name = "Core__Swarm__MechEntity",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Core__Swarm__MechEntity),
        .vtable = &nupa_Core__Swarm__MechEntity_vtable_inst,
        .class_vtable = &nupa_Core__Swarm__MechEntity_meta_vtable_inst,
        .protocol_count = 0,
    };
}
