// Generated by nupac
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Ledger__Core__TransactionBlock_vtable;
struct nupa_Network__Engine__ValidatorEngine_vtable;
struct nupa_Network__Extensions__RouterPlugin_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Ledger__Core__TransactionBlock_vtable_index_initWithHash_count_ 6
#define nupa_Network__Engine__ValidatorEngine_vtable_index_initWithIdentity_stake_ 4
#define nupa_Network__Engine__ValidatorEngine_vtable_index_validateBlock_withVerifier_ 5
#define nupa_Network__Extensions__RouterPlugin_vtable_index_initWithName_multiplier_ 4
#define nupa_Network__Extensions__RouterPlugin_vtable_index_attachToValidator_ 5

static const SEL __nupa_sel_initWithHash_count_ = {.name = "initWithHash_count_", .hash = 0xD541F244};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_blockHash = {.name = "blockHash", .hash = 0x94443496};
static const SEL __nupa_sel_txCount = {.name = "txCount", .hash = 0xF20C0158};
static const SEL __nupa_sel_stakeAmount = {.name = "stakeAmount", .hash = 0x2E0B7805};
static const SEL __nupa_sel_setStakeAmount_ = {.name = "setStakeAmount_", .hash = 0x0F4A58E8};
static const SEL __nupa_sel_createGenesisBlock = {.name = "createGenesisBlock", .hash = 0xBC19C0B6};
static const SEL __nupa_sel_initWithIdentity_stake_ = {.name = "initWithIdentity_stake_", .hash = 0xD1090B81};
static const SEL __nupa_sel_nodeIdentity = {.name = "nodeIdentity", .hash = 0x70FBA9A3};
static const SEL __nupa_sel_initWithName_multiplier_ = {.name = "initWithName_multiplier_", .hash = 0x500A9193};
static const SEL __nupa_sel_pluginName = {.name = "pluginName", .hash = 0x2A6701E1};
static const SEL __nupa_sel_attachToValidator_ = {.name = "attachToValidator_", .hash = 0xA0FFA812};
static const SEL __nupa_sel_validateBlock_withVerifier_ = {.name = "validateBlock_withVerifier_", .hash = 0xB304DE64};
static const SEL __nupa_sel_createStandardBlock = {.name = "createStandardBlock", .hash = 0xC0FE1041};

typedef struct NPObject NPObject;
typedef struct Ledger__Core__TransactionBlock Ledger__Core__TransactionBlock;
typedef struct Network__Engine__ValidatorEngine Network__Engine__ValidatorEngine;
typedef struct Network__Extensions__RouterPlugin Network__Extensions__RouterPlugin;


typedef int (^SignatureVerifyBlock)(int);

NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
Ledger__Core__TransactionBlock * Ledger__Core__TransactionBlock_createGenesisBlock(NPClass * self, SEL _cmd);
Ledger__Core__TransactionBlock * Ledger__Core__TransactionBlock_createStandardBlock(NPClass * self, SEL _cmd);
NPObject * Ledger__Core__TransactionBlock_initWithHash_count_(NPObject * self, SEL _cmd, const char * hash, int c);
int Ledger__Core__TransactionBlock_txCount(NPObject * self, SEL _cmd);
void Ledger__Core__TransactionBlock_setTxCount_(NPObject * self, SEL _cmd, int value);
const char * Ledger__Core__TransactionBlock_blockHash(NPObject * self, SEL _cmd);
NPClass * Ledger__Core__TransactionBlock_getClass(NPClass * self, SEL _cmd);
NPObject * Network__Engine__ValidatorEngine_initWithIdentity_stake_(NPObject * self, SEL _cmd, const char * idInfo, int s);
int Network__Engine__ValidatorEngine_validateBlock_withVerifier_(NPObject * self, SEL _cmd, Ledger__Core__TransactionBlock * block, SignatureVerifyBlock verifier);
int Network__Engine__ValidatorEngine_stakeAmount(NPObject * self, SEL _cmd);
void Network__Engine__ValidatorEngine_setStakeAmount_(NPObject * self, SEL _cmd, int value);
const char * Network__Engine__ValidatorEngine_nodeIdentity(NPObject * self, SEL _cmd);
NPClass * Network__Engine__ValidatorEngine_getClass(NPClass * self, SEL _cmd);
NPObject * Network__Extensions__RouterPlugin_initWithName_multiplier_(NPObject * self, SEL _cmd, const char * name, int m);
void Network__Extensions__RouterPlugin_attachToValidator_(NPObject * self, SEL _cmd, Network__Engine__ValidatorEngine * validator);
int Network__Extensions__RouterPlugin_bandwidthMultiplier(NPObject * self, SEL _cmd);
void Network__Extensions__RouterPlugin_setBandwidthMultiplier_(NPObject * self, SEL _cmd, int value);
const char * Network__Extensions__RouterPlugin_pluginName(NPObject * self, SEL _cmd);
NPClass * Network__Extensions__RouterPlugin_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Ledger__Core__TransactionBlock_class;
extern NPClass nupa_Network__Engine__ValidatorEngine_class;
extern NPClass nupa_Network__Extensions__RouterPlugin_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Ledger__Core__TransactionBlock {
    struct NPClass *isa;
    uint32_t retain_count;
    int _txCount;
    const char * _blockHash;
};
typedef struct Ledger__Core__TransactionBlock Ledger__Core__TransactionBlock;
struct nupa_Ledger__Core__TransactionBlock_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithHash_count_)(NPObject *, SEL, const char *, int);
    int (*txCount)(NPObject *, SEL);
    void (*setTxCount_)(NPObject *, SEL, int);
    const char * (*blockHash)(NPObject *, SEL);
};
struct nupa_Ledger__Core__TransactionBlock_meta_vtable {
    Ledger__Core__TransactionBlock * (*createGenesisBlock)(NPClass *, SEL);
    Ledger__Core__TransactionBlock * (*createStandardBlock)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
typedef int (^SignatureVerifyBlock)(int);
struct Network__Engine__ValidatorEngine {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * _nodeIdentity;
    int _stakeAmount;
};
typedef struct Network__Engine__ValidatorEngine Network__Engine__ValidatorEngine;
struct nupa_Network__Engine__ValidatorEngine_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithIdentity_stake_)(NPObject *, SEL, const char *, int);
    int (*validateBlock_withVerifier_)(NPObject *, SEL, Ledger__Core__TransactionBlock *, SignatureVerifyBlock);
    int (*stakeAmount)(NPObject *, SEL);
    void (*setStakeAmount_)(NPObject *, SEL, int);
    const char * (*nodeIdentity)(NPObject *, SEL);
};
struct nupa_Network__Engine__ValidatorEngine_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct Network__Extensions__RouterPlugin {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * _pluginName;
    int _bandwidthMultiplier;
};
typedef struct Network__Extensions__RouterPlugin Network__Extensions__RouterPlugin;
struct nupa_Network__Extensions__RouterPlugin_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithName_multiplier_)(NPObject *, SEL, const char *, int);
    void (*attachToValidator_)(NPObject *, SEL, Network__Engine__ValidatorEngine *);
    int (*bandwidthMultiplier)(NPObject *, SEL);
    void (*setBandwidthMultiplier_)(NPObject *, SEL, int);
    const char * (*pluginName)(NPObject *, SEL);
};
struct nupa_Network__Extensions__RouterPlugin_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
Ledger__Core__TransactionBlock * Ledger__Core__TransactionBlock_createGenesisBlock(NPClass * self, SEL _cmd) {
    return ({ NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Ledger__Core__TransactionBlock_class, __nupa_sel_alloc)); ((struct nupa_Ledger__Core__TransactionBlock_vtable *)__nupa_tmp_0->isa->vtable)->initWithHash_count_(__nupa_tmp_0, __nupa_sel_initWithHash_count_, "0000000000abc123", 1); });
}

Ledger__Core__TransactionBlock * Ledger__Core__TransactionBlock_createStandardBlock(NPClass * self, SEL _cmd) {
    return ({ NPObject *__nupa_tmp_1 = (NPObject_alloc(&nupa_Ledger__Core__TransactionBlock_class, __nupa_sel_alloc)); ((struct nupa_Ledger__Core__TransactionBlock_vtable *)__nupa_tmp_1->isa->vtable)->initWithHash_count_(__nupa_tmp_1, __nupa_sel_initWithHash_count_, "00000000ff987d6a", 500); });
}

NPObject * Ledger__Core__TransactionBlock_initWithHash_count_(NPObject * self, SEL _cmd, const char * hash, int c) {
    struct Ledger__Core__TransactionBlock * _self = ((struct Ledger__Core__TransactionBlock *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct Ledger__Core__TransactionBlock *)(self))->_blockHash = hash;
                ((struct Ledger__Core__TransactionBlock *)(self))->_txCount = c;
            }
        }
        return self;
    }
}

int Ledger__Core__TransactionBlock_txCount(NPObject * self, SEL _cmd) {
    return ((struct Ledger::Core::TransactionBlock *)(self))->_txCount;
}

void Ledger__Core__TransactionBlock_setTxCount_(NPObject * self, SEL _cmd, int value) {
    ((struct Ledger__Core__TransactionBlock *)(self))->_txCount = value;
}

const char * Ledger__Core__TransactionBlock_blockHash(NPObject * self, SEL _cmd) {
    return ((struct Ledger::Core::TransactionBlock *)(self))->_blockHash;
}

NPClass * Ledger__Core__TransactionBlock_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Ledger__Core__TransactionBlock_class;
}

NPObject * Network__Engine__ValidatorEngine_initWithIdentity_stake_(NPObject * self, SEL _cmd, const char * idInfo, int s) {
    struct Network__Engine__ValidatorEngine * _self = ((struct Network__Engine__ValidatorEngine *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct Network__Engine__ValidatorEngine *)(self))->_nodeIdentity = idInfo;
                ((struct Network__Engine__ValidatorEngine *)(self))->_stakeAmount = s;
            }
        }
        return self;
    }
}

int Network__Engine__ValidatorEngine_validateBlock_withVerifier_(NPObject * self, SEL _cmd, Ledger__Core__TransactionBlock * block, SignatureVerifyBlock verifier) {
    struct Network__Engine__ValidatorEngine * _self = ((struct Network__Engine__ValidatorEngine *)(self));
    {
        if (!block) {
            return 0;
        }
        printf("[%s] 节点启动共识校验，正在处理区块哈希: %s, 包含交易: %d 笔\n", ((struct Network__Engine__ValidatorEngine *)(self))->_nodeIdentity, ((struct nupa_Ledger__Core__TransactionBlock_vtable *)block->isa->vtable)->blockHash(block, __nupa_sel_blockHash), ((struct nupa_Ledger__Core__TransactionBlock_vtable *)block->isa->vtable)->txCount(block, __nupa_sel_txCount));
        int processYield = ((struct nupa_Ledger__Core__TransactionBlock_vtable *)block->isa->vtable)->txCount(block, __nupa_sel_txCount);
        if (verifier) {
            {
                processYield = verifier(((struct nupa_Ledger__Core__TransactionBlock_vtable *)block->isa->vtable)->txCount(block, __nupa_sel_txCount));
            }
        }
        int rewardScore = processYield * ((struct Network__Engine__ValidatorEngine *)(self))->_stakeAmount / 1000;
        if (rewardScore > 5000) {
            rewardScore = 5000;
        }
        return rewardScore;
    }
}

int Network__Engine__ValidatorEngine_stakeAmount(NPObject * self, SEL _cmd) {
    return ((struct Network::Engine::ValidatorEngine *)(self))->_stakeAmount;
}

void Network__Engine__ValidatorEngine_setStakeAmount_(NPObject * self, SEL _cmd, int value) {
    ((struct Network__Engine__ValidatorEngine *)(self))->_stakeAmount = value;
}

const char * Network__Engine__ValidatorEngine_nodeIdentity(NPObject * self, SEL _cmd) {
    return ((struct Network::Engine::ValidatorEngine *)(self))->_nodeIdentity;
}

NPClass * Network__Engine__ValidatorEngine_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Network__Engine__ValidatorEngine_class;
}

NPObject * Network__Extensions__RouterPlugin_initWithName_multiplier_(NPObject * self, SEL _cmd, const char * name, int m) {
    struct Network__Extensions__RouterPlugin * _self = ((struct Network__Extensions__RouterPlugin *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            {
                ((struct Network__Extensions__RouterPlugin *)(self))->_pluginName = name;
                ((struct Network__Extensions__RouterPlugin *)(self))->_bandwidthMultiplier = m;
            }
        }
        return self;
    }
}

void Network__Extensions__RouterPlugin_attachToValidator_(NPObject * self, SEL _cmd, Network__Engine__ValidatorEngine * validator) {
    struct Network__Extensions__RouterPlugin * _self = ((struct Network__Extensions__RouterPlugin *)(self));
    {
        if (validator) {
            {
                int originalStake = ((struct nupa_Network__Engine__ValidatorEngine_vtable *)validator->isa->vtable)->stakeAmount(validator, __nupa_sel_stakeAmount);
                ((struct nupa_Network__Engine__ValidatorEngine_vtable *)validator->isa->vtable)->setStakeAmount_(validator, __nupa_sel_setStakeAmount_, originalStake * ((struct Network__Extensions__RouterPlugin *)(self))->_bandwidthMultiplier);
                printf("[路由升级] 成功激活超级插件「%s」! 节点共识权重从 %d 飙升至: %d\n", ((struct Network__Extensions__RouterPlugin *)(self))->_pluginName, originalStake, ((struct nupa_Network__Engine__ValidatorEngine_vtable *)validator->isa->vtable)->stakeAmount(validator, __nupa_sel_stakeAmount));
            }
        }
    }
}

int Network__Extensions__RouterPlugin_bandwidthMultiplier(NPObject * self, SEL _cmd) {
    return ((struct Network::Extensions::RouterPlugin *)(self))->_bandwidthMultiplier;
}

void Network__Extensions__RouterPlugin_setBandwidthMultiplier_(NPObject * self, SEL _cmd, int value) {
    ((struct Network__Extensions__RouterPlugin *)(self))->_bandwidthMultiplier = value;
}

const char * Network__Extensions__RouterPlugin_pluginName(NPObject * self, SEL _cmd) {
    return ((struct Network::Extensions::RouterPlugin *)(self))->_pluginName;
}

NPClass * Network__Extensions__RouterPlugin_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Network__Extensions__RouterPlugin_class;
}

int main(int argc, const char * * argv) {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            printf("====================================================================\n");
            printf(">>>    nupac 编译器「区块链综合验证 - 三大 @using & 复合边界」     <<<\n");
            printf("====================================================================\n\n");
            printf("--- 1. 测试 Form 1 短名称类消息传递及静态工厂 (+ Method) ---\n");
            Ledger__Core__TransactionBlock * genesis = Ledger__Core__TransactionBlock_createGenesisBlock(&nupa_Ledger__Core__TransactionBlock_class, __nupa_sel_createGenesisBlock);
            printf("[区块生成] 成功利用短名称调用 + 方法: 哈希=%s | 交易=%d\n", ((struct nupa_Ledger__Core__TransactionBlock_vtable *)genesis->isa->vtable)->blockHash(genesis, __nupa_sel_blockHash), ((struct nupa_Ledger__Core__TransactionBlock_vtable *)genesis->isa->vtable)->txCount(genesis, __nupa_sel_txCount));
            printf("\n--- 2. 测试 Form 2 别名类的实例化与 Property 读写 ---\n");
            NPObject *__nupa_tmp_2 = (NPObject_alloc(&nupa_Network__Engine__ValidatorEngine_class, __nupa_sel_alloc));
            Network__Engine__ValidatorEngine * mainNode = ((struct nupa_Network__Engine__ValidatorEngine_vtable *)__nupa_tmp_2->isa->vtable)->initWithIdentity_stake_(__nupa_tmp_2, __nupa_sel_initWithIdentity_stake_, "东京-主网验证节点-01", 2000);
            printf("[节点报告] 别名实例化完成: %s | 初始权重: %d\n", ((struct nupa_Network__Engine__ValidatorEngine_vtable *)mainNode->isa->vtable)->nodeIdentity(mainNode, __nupa_sel_nodeIdentity), ((struct nupa_Network__Engine__ValidatorEngine_vtable *)mainNode->isa->vtable)->stakeAmount(mainNode, __nupa_sel_stakeAmount));
            printf("\n--- 3. 测试 Form 3 命名空间批量导入及插件挂载 ---\n");
            NPObject *__nupa_tmp_3 = (NPObject_alloc(&nupa_Network__Extensions__RouterPlugin_class, __nupa_sel_alloc));
            Network__Extensions__RouterPlugin * lightningModule = ((struct nupa_Network__Extensions__RouterPlugin_vtable *)__nupa_tmp_3->isa->vtable)->initWithName_multiplier_(__nupa_tmp_3, __nupa_sel_initWithName_multiplier_, "闪电网络共识加速器", 2);
            printf("[网络报告] 抓取到 Form 3 空间内的插件: %s\n", ((struct nupa_Network__Extensions__RouterPlugin_vtable *)lightningModule->isa->vtable)->pluginName(lightningModule, __nupa_sel_pluginName));
            ((struct nupa_Network__Extensions__RouterPlugin_vtable *)lightningModule->isa->vtable)->attachToValidator_(lightningModule, __nupa_sel_attachToValidator_, mainNode);
            printf("\n--- 4. 测试加密校验 Block 高阶闭包跨命名空间深度投递 ---\n");
            ;
            ;
            Network__Engine__SignatureVerifyBlock cryptographicVerifier = ^int(int txs) {
    totalBlocksValidated++;
    gasPriceMod = gasPriceMod + 15;
    return txs * 2 + gasPriceMod;
}
;
            int scoreGenesis = ((struct nupa_Network__Engine__ValidatorEngine_vtable *)mainNode->isa->vtable)->validateBlock_withVerifier_(mainNode, __nupa_sel_validateBlock_withVerifier_, genesis, cryptographicVerifier);
            Ledger__Core__TransactionBlock * standardBlock = Ledger__Core__TransactionBlock_createStandardBlock(&nupa_Ledger__Core__TransactionBlock_class, __nupa_sel_createStandardBlock);
            int scoreStandard = ((struct nupa_Network__Engine__ValidatorEngine_vtable *)mainNode->isa->vtable)->validateBlock_withVerifier_(mainNode, __nupa_sel_validateBlock_withVerifier_, standardBlock, cryptographicVerifier);
            printf("\n[共识记账最终账本报告]：\n");
            printf("          -> 创世区块验证节点获得信用分: %d\n", scoreGenesis);
            printf("          -> 标称区块验证节点获得信用分: %d\n", scoreStandard);
            printf("[闭包捕获状态断言]：\n");
            printf("          -> 共识闭包累计执行次数: %d (预期为 2)\n", totalBlocksValidated);
            printf("          -> 被捕获的外部 Gas 调整最终值: %d (预期为 80)\n", gasPriceMod);
            printf("\n--- 5. 回归核心：别名接收者、三元判断与逗号表达式副作用自增 ---\n");
            int isNetworkCongested = 1;
            int blockchainStepCounter = 7777;
            int finalVerifiedStake = isNetworkCongested > 0 ? ({ NPObject *__nupa_tmp_4 = (blockchainStepCounter++, mainNode); ((struct nupa_Network__Engine__ValidatorEngine_vtable *)__nupa_tmp_4->isa->vtable)->stakeAmount(__nupa_tmp_4, __nupa_sel_stakeAmount); }) : 0;
            printf("[终极复合断言] 编译树状态稳如泰山，未发生任何代码退化！\n");
            printf("          -> 副作用计数器自增值: %d (预期为 7778)\n", blockchainStepCounter);
            printf("          -> 动态通过表达式链抓取的节点质押权重: %d\n", finalVerifiedStake);
            printf("\n--- 6. 正在释放分布式节点拓扑资产内存... ---\n");
            nupa_release(genesis);
            nupa_release(standardBlock);
            nupa_release(mainNode);
            nupa_release(lightningModule);
            printf("\n====================================================================\n");
            printf(">>> 奇迹！综合压力与别名优先级测试全线绿灯！你太强了！  <<<\n");
            printf("====================================================================\n");
        }
        nupa_autoreleasepool_pop(__pool);
    }
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Ledger__Core__TransactionBlock_vtable nupa_Ledger__Core__TransactionBlock_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithHash_count_ = Ledger__Core__TransactionBlock_initWithHash_count_,
    .txCount = Ledger__Core__TransactionBlock_txCount,
    .setTxCount_ = Ledger__Core__TransactionBlock_setTxCount_,
    .blockHash = Ledger__Core__TransactionBlock_blockHash,
};

struct nupa_Network__Engine__ValidatorEngine_vtable nupa_Network__Engine__ValidatorEngine_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithIdentity_stake_ = Network__Engine__ValidatorEngine_initWithIdentity_stake_,
    .validateBlock_withVerifier_ = Network__Engine__ValidatorEngine_validateBlock_withVerifier_,
    .stakeAmount = Network__Engine__ValidatorEngine_stakeAmount,
    .setStakeAmount_ = Network__Engine__ValidatorEngine_setStakeAmount_,
    .nodeIdentity = Network__Engine__ValidatorEngine_nodeIdentity,
};

struct nupa_Network__Extensions__RouterPlugin_vtable nupa_Network__Extensions__RouterPlugin_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithName_multiplier_ = Network__Extensions__RouterPlugin_initWithName_multiplier_,
    .attachToValidator_ = Network__Extensions__RouterPlugin_attachToValidator_,
    .bandwidthMultiplier = Network__Extensions__RouterPlugin_bandwidthMultiplier,
    .setBandwidthMultiplier_ = Network__Extensions__RouterPlugin_setBandwidthMultiplier_,
    .pluginName = Network__Extensions__RouterPlugin_pluginName,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Ledger__Core__TransactionBlock_meta_vtable nupa_Ledger__Core__TransactionBlock_meta_vtable_inst = {
    .createGenesisBlock = Ledger__Core__TransactionBlock_createGenesisBlock,
    .createStandardBlock = Ledger__Core__TransactionBlock_createStandardBlock,
    .class = Ledger__Core__TransactionBlock_getClass,
};

struct nupa_Network__Engine__ValidatorEngine_meta_vtable nupa_Network__Engine__ValidatorEngine_meta_vtable_inst = {
    .class = Network__Engine__ValidatorEngine_getClass,
};

struct nupa_Network__Extensions__RouterPlugin_meta_vtable nupa_Network__Extensions__RouterPlugin_meta_vtable_inst = {
    .class = Network__Extensions__RouterPlugin_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Ledger__Core__TransactionBlock_class;
NPClass nupa_Network__Engine__ValidatorEngine_class;
NPClass nupa_Network__Extensions__RouterPlugin_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Ledger__Core__TransactionBlock_class = (NPClass){
        .name = "Ledger__Core__TransactionBlock",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Ledger__Core__TransactionBlock),
        .vtable = &nupa_Ledger__Core__TransactionBlock_vtable_inst,
        .class_vtable = &nupa_Ledger__Core__TransactionBlock_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Network__Engine__ValidatorEngine_class = (NPClass){
        .name = "Network__Engine__ValidatorEngine",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Network__Engine__ValidatorEngine),
        .vtable = &nupa_Network__Engine__ValidatorEngine_vtable_inst,
        .class_vtable = &nupa_Network__Engine__ValidatorEngine_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Network__Extensions__RouterPlugin_class = (NPClass){
        .name = "Network__Extensions__RouterPlugin",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Network__Extensions__RouterPlugin),
        .vtable = &nupa_Network__Extensions__RouterPlugin_vtable_inst,
        .class_vtable = &nupa_Network__Extensions__RouterPlugin_meta_vtable_inst,
        .protocol_count = 0,
    };
}
