// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Board_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_board = {.name = "board", .hash = 0xEF92FE2B};

typedef struct NPObject NPObject;
typedef struct Board Board;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
int * Board_board(NPObject * self, SEL _cmd);
void Board_setBoard_(NPObject * self, SEL _cmd, int * value);
NPClass * Board_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Board_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Board {
    struct NPClass *isa;
    uint32_t retain_count;
    int _board[9];
};
typedef struct Board Board;
struct nupa_Board_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    int * (*board)(NPObject *, SEL);
    void (*setBoard_)(NPObject *, SEL, int *);
};
struct nupa_Board_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
int * Board_board(NPObject * self, SEL _cmd) {
    return ((struct Board *)(self))->_board;
}

void Board_setBoard_(NPObject * self, SEL _cmd, int * value) {
    memcpy(&((struct Board *)(self))->_board, value, sizeof(((struct Board *)(0))->_board));
}

NPClass * Board_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Board_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Board_class, __nupa_sel_alloc));
    Board * b = ((struct nupa_NPObject_vtable *)__nupa_tmp_0->isa->vtable)->init(__nupa_tmp_0, __nupa_sel_init);
    b->_board[0] = 1;
    b->_board[4] = 2;
    b->_board[8] = 3;
    printf("%d %d %d\n", ((struct nupa_Board_vtable *)b->isa->vtable)->board(b, __nupa_sel_board)[0], ((struct nupa_Board_vtable *)b->isa->vtable)->board(b, __nupa_sel_board)[4], ((struct nupa_Board_vtable *)b->isa->vtable)->board(b, __nupa_sel_board)[8]);
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Board_vtable nupa_Board_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .board = Board_board,
    .setBoard_ = Board_setBoard_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Board_meta_vtable nupa_Board_meta_vtable_inst = {
    .class = Board_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Board_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Board_class = (NPClass){
        .name = "Board",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Board),
        .vtable = &nupa_Board_vtable_inst,
        .class_vtable = &nupa_Board_meta_vtable_inst,
        .protocol_count = 0,
    };
}
