// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Printer_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Printer_vtable_index_print_ 4

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_print_ = {.name = "print_", .hash = 0xD06F9075};

typedef struct NPObject NPObject;
typedef struct Printer Printer;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
void Printer_print_(NPObject * self, SEL _cmd, char * msg);
NPClass * Printer_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Printer_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Printer {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Printer Printer;
struct nupa_Printer_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*print_)(NPObject *, SEL, char *);
};
struct nupa_Printer_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
void Printer_print_(NPObject * self, SEL _cmd, char * msg) {
    struct Printer * _self = ((struct Printer *)(self));
    {
        printf("%s\n", msg);
    }
}

NPClass * Printer_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Printer_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Printer_class, __nupa_sel_alloc));
    Printer * p = ((struct nupa_NPObject_vtable *)__nupa_tmp_0->isa->vtable)->init(__nupa_tmp_0, __nupa_sel_init);
    ((struct nupa_Printer_vtable *)p->isa->vtable)->print_(p, __nupa_sel_print_, "Hello from Micrit!");
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Printer_vtable nupa_Printer_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .print_ = Printer_print_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Printer_meta_vtable nupa_Printer_meta_vtable_inst = {
    .class = Printer_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Printer_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Printer_class = (NPClass){
        .name = "Printer",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Printer),
        .vtable = &nupa_Printer_vtable_inst,
        .class_vtable = &nupa_Printer_meta_vtable_inst,
        .protocol_count = 0,
    };
}
