[package]
name = "nupac"
version = "0.1.0"
edition = "2021"

[dependencies]
nupa-cst = { path = "../cst" }
nupa-parser = { path = "../parser" }
nupa-binder = { path = "../binder" }
nupa-elaborator = { path = "../elaborator" }
nupa-codegen = { path = "../codegen" }
nupa-preprocessor = { path = "../preprocessor" }
nupa-symbol = { path = "../symbol" }
nupa-ast = { path = "../ast" }
nupa-cfg = { path = "../cfg" }
nupa-arc = { path = "../arc" }
nupa-trace = { path = "../trace" }
nupa-checker = { path = "../checker" }
attrs = { path = "../attrs" }
clap = "4.6.6"
clap_complete = "4.6.9"

[build-dependencies]
cc = "1.0"
