// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3

typedef struct NPObject NPObject;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            NPLog("mix: %d + %s = ok", 42, "nupa");
            NPLog("just text");
        }
        nupa_autoreleasepool_pop(__pool);
    }
    printf("NPLog format OK\n");
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

NPClass nupa_NPObject_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
}
