// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Foo_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Foo_vtable_index_init 2

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NPObject NPObject;
typedef struct Foo Foo;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * Foo_init(NPObject * self, SEL _cmd);
NPClass * Foo_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Foo_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Foo {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Foo Foo;
struct nupa_Foo_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_Foo_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
NPObject * Foo_init(NPObject * self, SEL _cmd) {
    struct Foo * _self = ((struct Foo *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        return self;
    }
}

NPClass * Foo_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Foo_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Foo_class, __nupa_sel_alloc));
            Foo * f = ((struct nupa_Foo_vtable *)__nupa_tmp_0->isa->vtable)->init(__nupa_tmp_0, __nupa_sel_init);
            NPLog("obj: %@", f);
            NPLog("null: %@", ((void *)(0)));
            nupa_release(f);
        }
        nupa_autoreleasepool_pop(__pool);
    }
    printf("NPLog %% OK\n");
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Foo_vtable nupa_Foo_vtable_inst = {
    .init = Foo_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Foo_meta_vtable nupa_Foo_meta_vtable_inst = {
    .class = Foo_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Foo_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Foo_class = (NPClass){
        .name = "Foo",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Foo),
        .vtable = &nupa_Foo_vtable_inst,
        .class_vtable = &nupa_Foo_meta_vtable_inst,
        .protocol_count = 0,
    };
}
