// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Game__Player_vtable;
struct nupa_UI__HUD_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Game__Player_vtable_index_initWithLevel_ 4
#define nupa_UI__HUD_vtable_index_initWithValue_ 4

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_initWithLevel_ = {.name = "initWithLevel_", .hash = 0x335A278C};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_initWithValue_ = {.name = "initWithValue_", .hash = 0xF0E5A305};

typedef struct NPObject NPObject;
typedef struct Game__Player Game__Player;
typedef struct UI__HUD UI__HUD;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * Game__Player_initWithLevel_(NPObject * self, SEL _cmd, int l);
NPClass * Game__Player_getClass(NPClass * self, SEL _cmd);
NPObject * UI__HUD_initWithValue_(NPObject * self, SEL _cmd, int v);
NPClass * UI__HUD_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Game__Player_class;
extern NPClass nupa_UI__HUD_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Game__Player {
    struct NPClass *isa;
    uint32_t retain_count;
    int level;
};
typedef struct Game__Player Game__Player;
struct nupa_Game__Player_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithLevel_)(NPObject *, SEL, int);
};
struct nupa_Game__Player_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct UI__HUD {
    struct NPClass *isa;
    uint32_t retain_count;
    int value;
};
typedef struct UI__HUD UI__HUD;
struct nupa_UI__HUD_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithValue_)(NPObject *, SEL, int);
};
struct nupa_UI__HUD_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
NPObject * Game__Player_initWithLevel_(NPObject * self, SEL _cmd, int l) {
    struct Game__Player * _self = ((struct Game__Player *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            ((struct Game__Player *)(self))->level = l;
        }
        return self;
    }
}

NPClass * Game__Player_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Game__Player_class;
}

NPObject * UI__HUD_initWithValue_(NPObject * self, SEL _cmd, int v) {
    struct UI__HUD * _self = ((struct UI__HUD *)(self));
    {
        self = NPObject_init(self, __nupa_sel_init);
        if (self) {
            ((struct UI__HUD *)(self))->value = v;
        }
        return self;
    }
}

NPClass * UI__HUD_getClass(NPClass * self, SEL _cmd) {
    return &nupa_UI__HUD_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __pool = nupa_autoreleasepool_push();
        {
            NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Game__Player_class, __nupa_sel_alloc));
            Game__Player * p = ((struct nupa_Game__Player_vtable *)__nupa_tmp_0->isa->vtable)->initWithLevel_(__nupa_tmp_0, __nupa_sel_initWithLevel_, 10);
            NPObject *__nupa_tmp_1 = (NPObject_alloc(&nupa_UI__HUD_class, __nupa_sel_alloc));
            UI__HUD * h = ((struct nupa_UI__HUD_vtable *)__nupa_tmp_1->isa->vtable)->initWithValue_(__nupa_tmp_1, __nupa_sel_initWithValue_, 42);
            printf("[alias] Player level=%d, HUD value=%d\n", ((struct Game__Player *)(p))->level, ((struct UI__HUD *)(h))->value);
            nupa_release(p);
            nupa_release(h);
        }
        nupa_autoreleasepool_pop(__pool);
    }
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Game__Player_vtable nupa_Game__Player_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithLevel_ = Game__Player_initWithLevel_,
};

struct nupa_UI__HUD_vtable nupa_UI__HUD_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithValue_ = UI__HUD_initWithValue_,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Game__Player_meta_vtable nupa_Game__Player_meta_vtable_inst = {
    .class = Game__Player_getClass,
};

struct nupa_UI__HUD_meta_vtable nupa_UI__HUD_meta_vtable_inst = {
    .class = UI__HUD_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Game__Player_class;
NPClass nupa_UI__HUD_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Game__Player_class = (NPClass){
        .name = "Game__Player",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Game__Player),
        .vtable = &nupa_Game__Player_vtable_inst,
        .class_vtable = &nupa_Game__Player_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_UI__HUD_class = (NPClass){
        .name = "UI__HUD",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct UI__HUD),
        .vtable = &nupa_UI__HUD_vtable_inst,
        .class_vtable = &nupa_UI__HUD_meta_vtable_inst,
        .protocol_count = 0,
    };
}
