use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    // Identifiers / Keywords
    Identifier,
    Keyword,

    // Literals
    Integer,
    Float,
    String,
    AtString,
    Char,
    Bool,

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    Exclam,
    Less,
    Greater,
    Assign,
    Comma,
    Dot,
    Semicolon,
    Colon,
    ColonColon,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    LParen,
    RParen,
    Arrow,
    Ellipsis,

    // Compound operators
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AndAssign,
    OrAssign,
    XorAssign,
    LShiftAssign,
    RShiftAssign,
    Eq,
    Neq,
    Leq,
    Geq,
    LShift,
    RShift,
    LogicalAnd,
    LogicalOr,
    Incr,
    Decr,
    ArrowStar,
    Question,

    // Preprocessor
    PpHash,
    PpDoubleHash,

    // Special
    Newline,
    Eof,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeywordKind {
    AtInterface,
    AtImplementation,
    AtEnd,
    AtProperty,
    AtSynthesize,
    AtDynamic,
    AtSelector,
    AtEncode,
    AtProtocol,
    AtOptional,
    AtRequired,
    AtClass,
    AtTry,
    AtCatch,
    AtFinally,
    AtThrow,
    AtSynchronized,
    AtAutoreleasepool,
    AtPublic,
    AtPackage,
    AtProtected,
    AtPrivate,
    AtDefs,
    AtNamespace,
    AtUsing,
    AtReadwrite,
    AtReadonly,
    AtWeak,
    AtStrong,
    AtAssign,
    AtRetain,
    AtCopy,
    AtNonatomic,
    AtGetter,
    AtSetter,

    Yes,
    No,
    Nil,
    Null,

    Self_,
    Super,
    Cmd,

    Block,
    Weak,
    Strong,
    Autoreleasing,
    UnsafeUnretained,

    Instancetype,
    Id,
    Class,
    Sel,
    Bool,
    Imp,
    NpZone,

    Return,
    If,
    Else,
    Switch,
    Case,
    Default,
    While,
    Do,
    For,
    In,
    Break,
    Continue,
    Goto,
    Sizeof,
    Typeof,
    Struct,
    Union,
    Enum,
    Typedef,

    Void,
    Char,
    Short,
    Int,
    Long,
    Float,
    Double,
    Signed,
    Unsigned,
    Const,
    Volatile,
    Static,
    Extern,
    Auto,
    Register,
    Inline,
    Restrict,

    Import,
    Include,
    Define,
    Ifdef,
    Ifndef,
    Endif,
    Pragma,
    Elif,
    Undef,

    Asm,

    None,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub keyword: KeywordKind,
    pub start: usize,
    pub length: usize,
    pub line: usize,
    pub column: usize,
    pub char_val: u8,
}

impl Token {
    pub fn text<'a>(&self, source: &'a str) -> &'a str {
        &source[self.start..self.start + self.length]
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Identifier => write!(f, "identifier"),
            TokenKind::Keyword => write!(f, "keyword"),
            TokenKind::Integer => write!(f, "integer"),
            TokenKind::Float => write!(f, "float"),
            TokenKind::String => write!(f, "string"),
            TokenKind::AtString => write!(f, "at-string"),
            TokenKind::Char => write!(f, "char"),
            TokenKind::Bool => write!(f, "bool"),
            TokenKind::Plus => write!(f, "'+'"),
            TokenKind::Minus => write!(f, "'-'"),
            TokenKind::Star => write!(f, "'*'"),
            TokenKind::Slash => write!(f, "'/'"),
            TokenKind::Percent => write!(f, "'%'"),
            TokenKind::Ampersand => write!(f, "'&'"),
            TokenKind::Pipe => write!(f, "'|'"),
            TokenKind::Caret => write!(f, "'^'"),
            TokenKind::Tilde => write!(f, "'~'"),
            TokenKind::Exclam => write!(f, "'!'"),
            TokenKind::Less => write!(f, "'<'"),
            TokenKind::Greater => write!(f, "'>'"),
            TokenKind::Assign => write!(f, "'='"),
            TokenKind::Comma => write!(f, "','"),
            TokenKind::Dot => write!(f, "'.'"),
            TokenKind::Semicolon => write!(f, "';'"),
            TokenKind::Colon => write!(f, "':'"),
            TokenKind::ColonColon => write!(f, "'::'"),
            TokenKind::LBracket => write!(f, "'['"),
            TokenKind::RBracket => write!(f, "']'"),
            TokenKind::LBrace => write!(f, "'{{'"),
            TokenKind::RBrace => write!(f, "'}}'"),
            TokenKind::LParen => write!(f, "'('"),
            TokenKind::RParen => write!(f, "')'"),
            TokenKind::Arrow => write!(f, "'->'"),
            TokenKind::Ellipsis => write!(f, "'...'"),
            TokenKind::PlusAssign => write!(f, "'+='"),
            TokenKind::MinusAssign => write!(f, "'-='"),
            TokenKind::StarAssign => write!(f, "'*='"),
            TokenKind::SlashAssign => write!(f, "'/='"),
            TokenKind::PercentAssign => write!(f, "'%='"),
            TokenKind::AndAssign => write!(f, "'&='"),
            TokenKind::OrAssign => write!(f, "'|='"),
            TokenKind::XorAssign => write!(f, "'^='"),
            TokenKind::LShiftAssign => write!(f, "'<<='"),
            TokenKind::RShiftAssign => write!(f, "'>>='"),
            TokenKind::Eq => write!(f, "'=='"),
            TokenKind::Neq => write!(f, "'!='"),
            TokenKind::Leq => write!(f, "'<='"),
            TokenKind::Geq => write!(f, "'>='"),
            TokenKind::LShift => write!(f, "'<<'"),
            TokenKind::RShift => write!(f, "'>>'"),
            TokenKind::LogicalAnd => write!(f, "'&&'"),
            TokenKind::LogicalOr => write!(f, "'||'"),
            TokenKind::Incr => write!(f, "'++'"),
            TokenKind::Decr => write!(f, "'--'"),
            TokenKind::ArrowStar => write!(f, "'->*'"),
            TokenKind::Question => write!(f, "'?'"),
            TokenKind::PpHash => write!(f, "'#'"),
            TokenKind::PpDoubleHash => write!(f, "'##'"),
            TokenKind::Newline => write!(f, "newline"),
            TokenKind::Eof => write!(f, "EOF"),
            TokenKind::Error => write!(f, "error"),
        }
    }
}