// Generated by nupac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"


#include <string.h>

struct nupa_NPObject_vtable;
struct nupa_Animal_vtable;

#define nupa_NPObject_vtable_index_init 2
#define nupa_NPObject_vtable_index_dealloc 3
#define nupa_Animal_vtable_index_speak 4

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_speak = {.name = "speak", .hash = 0xA2780A89};

typedef struct NPObject NPObject;
typedef struct Animal Animal;
typedef struct Dog Dog;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
void Animal_speak(NPObject * self, SEL _cmd);
NPClass * Animal_getClass(NPClass * self, SEL _cmd);
NPClass * Dog_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nupa_NPObject_class;
extern NPClass nupa_Animal_class;
extern NPClass nupa_Dog_class;
void nupa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nupa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Animal {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Animal Animal;
struct nupa_Animal_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*speak)(NPObject *, SEL);
};
struct nupa_Animal_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct Dog {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Dog Dog;
struct nupa_Dog_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*speak)(NPObject *, SEL);
};
struct nupa_Dog_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nupa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nupa_NPObject_class;
}

NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * );
void Animal_speak(NPObject * self, SEL _cmd) {
    struct Animal * _self = ((struct Animal *)(self));
    {
        printf("Animal speaks\n");
    }
}

NPClass * Animal_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Animal_class;
}

NPClass * Dog_getClass(NPClass * self, SEL _cmd) {
    return &nupa_Dog_class;
}

int main() {
    nupa_autoreleasepool_t *__pool = nupa_autoreleasepool_push();
    nupa_meta_init();
    NPObject *__nupa_tmp_0 = (NPObject_alloc(&nupa_Dog_class, __nupa_sel_alloc));
    Dog * d = ((struct nupa_NPObject_vtable *)__nupa_tmp_0->isa->vtable)->init(__nupa_tmp_0, __nupa_sel_init);
    ((struct nupa_Animal_vtable *)d->isa->vtable)->speak(d, __nupa_sel_speak);
    return 0;
    nupa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nupa_NPObject_vtable nupa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nupa_Animal_vtable nupa_Animal_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .speak = Animal_speak,
};

struct nupa_Dog_vtable nupa_Dog_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .speak = Animal_speak,
};

struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nupa_Animal_meta_vtable nupa_Animal_meta_vtable_inst = {
    .class = Animal_getClass,
};

struct nupa_Dog_meta_vtable nupa_Dog_meta_vtable_inst = {
    .class = Dog_getClass,
};

NPClass nupa_NPObject_class;
NPClass nupa_Animal_class;
NPClass nupa_Dog_class;

void nupa_meta_init(void) {
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Animal_class = (NPClass){
        .name = "Animal",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct Animal),
        .vtable = &nupa_Animal_vtable_inst,
        .class_vtable = &nupa_Animal_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_Dog_class = (NPClass){
        .name = "Dog",
        .superclass = &nupa_Animal_class,
        .instance_size = sizeof(struct Dog),
        .vtable = &nupa_Dog_vtable_inst,
        .class_vtable = &nupa_Dog_meta_vtable_inst,
        .protocol_count = 0,
    };
}
