// Generated by nupac
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ui.h>
#include <stdint.h>
#include <stddef.h>
#include "nupa/runtime.h"
#ifndef LIBUI_NH
#define LIBUI_NH
#endif
struct nupa_vtable;
struct nupa_NPObject_meta_vtable;
struct nupa_LibUI__Entry_meta_vtable;
struct nupa_LibUI__Group_meta_vtable;
struct nupa_LibUI__Label_meta_vtable;
struct nupa_LibUI__MultilineEntry_meta_vtable;
struct nupa_LibUI__Separator_meta_vtable;
struct nupa_LibUI__Tab_meta_vtable;
struct nupa_LibUI__Window_meta_vtable;
struct nupa_LibUI__Box_meta_vtable;
struct nupa_LibUI__Button_meta_vtable;

static const SEL __nupa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nupa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nupa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nupa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nupa_sel_isKindOf_ = {.name = "isKindOf:", .hash = 0x6E8A60C4};
static const SEL __nupa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nupa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nupa_sel_withTitle_width_height_ = {.name = "withTitle:width:height:", .hash = 0x6785AAB6};
static const SEL __nupa_sel_show = {.name = "show", .hash = 0xA947E23C};
static const SEL __nupa_sel_activate = {.name = "activate", .hash = 0x3F434070};
static const SEL __nupa_sel_onClosingQuit = {.name = "onClosingQuit", .hash = 0x5BA7F2E0};
static const SEL __nupa_sel_setChild_ = {.name = "setChild:", .hash = 0x2DBAE9B3};
static const SEL __nupa_sel_handle = {.name = "handle", .hash = 0x2E7FCBD3};
static const SEL __nupa_sel_vertical = {.name = "vertical", .hash = 0x8729D53B};
static const SEL __nupa_sel_horizontal = {.name = "horizontal", .hash = 0x55358A69};
static const SEL __nupa_sel_append_stretch_ = {.name = "append:stretch:", .hash = 0xCA894D44};
static const SEL __nupa_sel_withText_ = {.name = "withText:", .hash = 0x98C265B0};
static const SEL __nupa_sel_onClicked_data_ = {.name = "onClicked:data:", .hash = 0x98EBDA19};
static const SEL __nupa_sel_setText_ = {.name = "setText:", .hash = 0x4C43F6DA};
static const SEL __nupa_sel_create = {.name = "create", .hash = 0x26BB595D};
static const SEL __nupa_sel_text = {.name = "text", .hash = 0xBDE64E3E};
static const SEL __nupa_sel_withTitle_ = {.name = "withTitle:", .hash = 0xA307D66D};
static const SEL __nupa_sel_append_child_ = {.name = "append:child:", .hash = 0x7CE50211};

#ifndef __NUPA_ROOT_DEFINED
#define __NUPA_ROOT_DEFINED
struct __nupa_root {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct __nupa_root __nupa_root;
#endif
#ifndef NPOBJECT_DEFINED
#define NPOBJECT_DEFINED
struct NPObject {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPObject NPObject;
#endif
struct LibUI__Entry;
typedef struct LibUI__Entry LibUI__Entry;
struct LibUI__Group;
typedef struct LibUI__Group LibUI__Group;
struct LibUI__Label;
typedef struct LibUI__Label LibUI__Label;
struct LibUI__MultilineEntry;
typedef struct LibUI__MultilineEntry LibUI__MultilineEntry;
struct LibUI__Separator;
typedef struct LibUI__Separator LibUI__Separator;
struct LibUI__Tab;
typedef struct LibUI__Tab LibUI__Tab;
struct LibUI__Window;
typedef struct LibUI__Window LibUI__Window;
struct LibUI__Box;
typedef struct LibUI__Box LibUI__Box;
struct LibUI__Button;
typedef struct LibUI__Button LibUI__Button;

struct CounterCtx {
    int value;
    struct uiLabel * label;
};

NPObject * __nupa_root_init(NPObject * self, SEL _cmd);
void __nupa_root_dealloc(NPObject * self, SEL _cmd);
void __nupa_root_release(NPObject * self, SEL _cmd);
NPObject * __nupa_root_retain(NPObject * self, SEL _cmd);
_Bool __nupa_root_isKindOf_(NPObject * self, SEL _cmd, NPClass * cls);
NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
LibUI__Window * LibUI__Window_withTitle_width_height_(NPClass * self, SEL _cmd, const char * title, int w, int h);
void LibUI__Window_show(NPObject * self, SEL _cmd);
void LibUI__Window_activate(NPClass * self, SEL _cmd);
void LibUI__Window_onClosingQuit(NPObject * self, SEL _cmd);
void LibUI__Window_setChild_(NPObject * self, SEL _cmd, struct uiControl * child);
struct uiWindow * LibUI__Window_handle(NPObject * self, SEL _cmd);
LibUI__Box * LibUI__Box_vertical(NPClass * self, SEL _cmd);
LibUI__Box * LibUI__Box_horizontal(NPClass * self, SEL _cmd);
void LibUI__Box_append_stretch_(NPObject * self, SEL _cmd, struct uiControl * child, int stretch);
struct uiBox * LibUI__Box_handle(NPObject * self, SEL _cmd);
LibUI__Button * LibUI__Button_withText_(NPClass * self, SEL _cmd, const char * text);
void LibUI__Button_onClicked_data_(NPObject * self, SEL _cmd, void * cb, void * data);
struct uiButton * LibUI__Button_handle(NPObject * self, SEL _cmd);
LibUI__Label * LibUI__Label_withText_(NPClass * self, SEL _cmd, const char * text);
void LibUI__Label_setText_(NPObject * self, SEL _cmd, const char * text);
struct uiLabel * LibUI__Label_handle(NPObject * self, SEL _cmd);
LibUI__Entry * LibUI__Entry_create(NPClass * self, SEL _cmd);
const char * LibUI__Entry_text(NPObject * self, SEL _cmd);
void LibUI__Entry_setText_(NPObject * self, SEL _cmd, const char * text);
struct uiEntry * LibUI__Entry_handle(NPObject * self, SEL _cmd);
LibUI__MultilineEntry * LibUI__MultilineEntry_create(NPClass * self, SEL _cmd);
const char * LibUI__MultilineEntry_text(NPObject * self, SEL _cmd);
void LibUI__MultilineEntry_setText_(NPObject * self, SEL _cmd, const char * text);
struct uiMultilineEntry * LibUI__MultilineEntry_handle(NPObject * self, SEL _cmd);
LibUI__Separator * LibUI__Separator_horizontal(NPClass * self, SEL _cmd);
LibUI__Separator * LibUI__Separator_vertical(NPClass * self, SEL _cmd);
struct uiSeparator * LibUI__Separator_handle(NPObject * self, SEL _cmd);
LibUI__Group * LibUI__Group_withTitle_(NPClass * self, SEL _cmd, const char * title);
void LibUI__Group_setChild_(NPObject * self, SEL _cmd, struct uiControl * child);
struct uiGroup * LibUI__Group_handle(NPObject * self, SEL _cmd);
LibUI__Tab * LibUI__Tab_create(NPClass * self, SEL _cmd);
void LibUI__Tab_append_child_(NPObject * self, SEL _cmd, const char * name, struct uiControl * child);
struct uiTab * LibUI__Tab_handle(NPObject * self, SEL _cmd);
NPObject * nupa_alloc(struct NPClass * cls);
NPObject * nupa_init(NPObject * self);
void nupa_release(NPObject * obj);
NPObject * nupa_retain(NPObject * obj);
void onGreet(struct uiButton * b, void * data);
void * counter_ctx_create(struct uiLabel * label);
void onInc(struct uiButton * b, void * data);
void onDec(struct uiButton * b, void * data);
void onReset(struct uiButton * b, void * data);
int main(void);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Entry_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Group_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Label_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__MultilineEntry_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Separator_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Tab_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Window_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Box_getClass(NPClass * self, SEL _cmd);
NPClass * LibUI__Button_getClass(NPClass * self, SEL _cmd);

struct nupa_vtable {
    void (*append_child_)(NPObject *, SEL, const char *, struct uiControl *);
    void (*append_stretch_)(NPObject *, SEL, struct uiControl *, int);
    void (*dealloc)(NPObject *, SEL);
    struct uiEntry * (*handle)(NPObject *, SEL);
    NPObject * (*init)(NPObject *, SEL);
    _Bool (*isKindOf_)(NPObject *, SEL, NPClass *);
    void (*onClicked_data_)(NPObject *, SEL, void *, void *);
    void (*onClosingQuit)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    void (*setChild_)(NPObject *, SEL, struct uiControl *);
    void (*setText_)(NPObject *, SEL, const char *);
    void (*show)(NPObject *, SEL);
    const char * (*text)(NPObject *, SEL);
};

struct nupa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Entry_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Entry * (*create)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Group_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Group * (*withTitle_)(NPClass *, SEL, const char *);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Label_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Label * (*withText_)(NPClass *, SEL, const char *);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__MultilineEntry_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__MultilineEntry * (*create)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Separator_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Separator * (*horizontal)(NPClass *, SEL);
    LibUI__Separator * (*vertical)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Tab_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Tab * (*create)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Window_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Window * (*withTitle_width_height_)(NPClass *, SEL, const char *, int, int);
    void (*activate)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Box_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Box * (*vertical)(NPClass *, SEL);
    LibUI__Box * (*horizontal)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nupa_LibUI__Button_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    LibUI__Button * (*withText_)(NPClass *, SEL, const char *);
    NPClass * (*class)(NPClass *, SEL);
};

struct LibUI__Entry {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiEntry * _handle;
};
typedef struct LibUI__Entry LibUI__Entry;

struct LibUI__Group {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiGroup * _handle;
};
typedef struct LibUI__Group LibUI__Group;

struct LibUI__Label {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiLabel * _handle;
};
typedef struct LibUI__Label LibUI__Label;

struct LibUI__MultilineEntry {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiMultilineEntry * _handle;
};
typedef struct LibUI__MultilineEntry LibUI__MultilineEntry;

struct LibUI__Separator {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiSeparator * _handle;
};
typedef struct LibUI__Separator LibUI__Separator;

struct LibUI__Tab {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiTab * _handle;
};
typedef struct LibUI__Tab LibUI__Tab;

struct LibUI__Window {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiWindow * _handle;
};
typedef struct LibUI__Window LibUI__Window;

struct LibUI__Box {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiBox * _handle;
};
typedef struct LibUI__Box LibUI__Box;

struct LibUI__Button {
    struct NPClass *isa;
    uint32_t retain_count;
    struct uiButton * _handle;
    void * _cbData;
};
typedef struct LibUI__Button LibUI__Button;

extern NPClass nupa___nupa_root_class;
extern NPClass nupa_NPObject_class;
extern NPClass nupa_LibUI__Entry_class;
extern NPClass nupa_LibUI__Group_class;
extern NPClass nupa_LibUI__Label_class;
extern NPClass nupa_LibUI__MultilineEntry_class;
extern NPClass nupa_LibUI__Separator_class;
extern NPClass nupa_LibUI__Tab_class;
extern NPClass nupa_LibUI__Window_class;
extern NPClass nupa_LibUI__Box_class;
extern NPClass nupa_LibUI__Button_class;
void nupa_meta_init(void);

__attribute__((weak)) struct nupa_vtable nupa___nupa_root_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))__nupa_root_dealloc,
    .handle = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))__nupa_root_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))__nupa_root_release,
    .retain = (NPObject * (*)(NPObject *, SEL))__nupa_root_retain,
    .setChild_ = NULL,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_NPObject_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = NULL,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Entry_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Entry_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = (void (*)(NPObject *, SEL, const char *))LibUI__Entry_setText_,
    .show = NULL,
    .text = (const char * (*)(NPObject *, SEL))LibUI__Entry_text,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Group_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Group_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = (void (*)(NPObject *, SEL, struct uiControl *))LibUI__Group_setChild_,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Label_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Label_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = (void (*)(NPObject *, SEL, const char *))LibUI__Label_setText_,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__MultilineEntry_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__MultilineEntry_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = (void (*)(NPObject *, SEL, const char *))LibUI__MultilineEntry_setText_,
    .show = NULL,
    .text = (const char * (*)(NPObject *, SEL))LibUI__MultilineEntry_text,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Separator_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Separator_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Tab_vtable_inst = {
    .append_child_ = (void (*)(NPObject *, SEL, const char *, struct uiControl *))LibUI__Tab_append_child_,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Tab_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Window_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Window_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = (void (*)(NPObject *, SEL))LibUI__Window_onClosingQuit,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = (void (*)(NPObject *, SEL, struct uiControl *))LibUI__Window_setChild_,
    .setText_ = NULL,
    .show = (void (*)(NPObject *, SEL))LibUI__Window_show,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Box_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = (void (*)(NPObject *, SEL, struct uiControl *, int))LibUI__Box_append_stretch_,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Box_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = NULL,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_vtable nupa_LibUI__Button_vtable_inst = {
    .append_child_ = NULL,
    .append_stretch_ = NULL,
    .dealloc = (void (*)(NPObject *, SEL))NPObject_dealloc,
    .handle = (struct uiEntry * (*)(NPObject *, SEL))LibUI__Button_handle,
    .init = (NPObject * (*)(NPObject *, SEL))NPObject_init,
    .isKindOf_ = (_Bool (*)(NPObject *, SEL, NPClass *))__nupa_root_isKindOf_,
    .onClicked_data_ = (void (*)(NPObject *, SEL, void *, void *))LibUI__Button_onClicked_data_,
    .onClosingQuit = NULL,
    .release = (void (*)(NPObject *, SEL))NPObject_release,
    .retain = (NPObject * (*)(NPObject *, SEL))NPObject_retain,
    .setChild_ = NULL,
    .setText_ = NULL,
    .show = NULL,
    .text = NULL,
};

__attribute__((weak)) struct nupa_NPObject_meta_vtable nupa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Entry_meta_vtable nupa_LibUI__Entry_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .create = LibUI__Entry_create,
    .class = LibUI__Entry_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Group_meta_vtable nupa_LibUI__Group_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .withTitle_ = LibUI__Group_withTitle_,
    .class = LibUI__Group_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Label_meta_vtable nupa_LibUI__Label_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .withText_ = LibUI__Label_withText_,
    .class = LibUI__Label_getClass,
};

__attribute__((weak)) struct nupa_LibUI__MultilineEntry_meta_vtable nupa_LibUI__MultilineEntry_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .create = LibUI__MultilineEntry_create,
    .class = LibUI__MultilineEntry_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Separator_meta_vtable nupa_LibUI__Separator_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .horizontal = LibUI__Separator_horizontal,
    .vertical = LibUI__Separator_vertical,
    .class = LibUI__Separator_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Tab_meta_vtable nupa_LibUI__Tab_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .create = LibUI__Tab_create,
    .class = LibUI__Tab_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Window_meta_vtable nupa_LibUI__Window_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .withTitle_width_height_ = LibUI__Window_withTitle_width_height_,
    .activate = LibUI__Window_activate,
    .class = LibUI__Window_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Box_meta_vtable nupa_LibUI__Box_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .vertical = LibUI__Box_vertical,
    .horizontal = LibUI__Box_horizontal,
    .class = LibUI__Box_getClass,
};

__attribute__((weak)) struct nupa_LibUI__Button_meta_vtable nupa_LibUI__Button_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .withText_ = LibUI__Button_withText_,
    .class = LibUI__Button_getClass,
};

__attribute__((weak)) NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Entry_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Group_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Label_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__MultilineEntry_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Separator_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Tab_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Window_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Box_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

__attribute__((weak)) NPClass * LibUI__Button_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nupa___nupa_root_class;
NPClass nupa_NPObject_class;
NPClass nupa_LibUI__Entry_class;
NPClass nupa_LibUI__Group_class;
NPClass nupa_LibUI__Label_class;
NPClass nupa_LibUI__MultilineEntry_class;
NPClass nupa_LibUI__Separator_class;
NPClass nupa_LibUI__Tab_class;
NPClass nupa_LibUI__Window_class;
NPClass nupa_LibUI__Box_class;
NPClass nupa_LibUI__Button_class;

__attribute__((weak)) void nupa_meta_init(void) {
    nupa___nupa_root_class = (NPClass){
        .name = "__nupa_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __nupa_root),
        .vtable = &nupa___nupa_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    nupa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = &nupa___nupa_root_class,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nupa_NPObject_vtable_inst,
        .class_vtable = &nupa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Entry_class = (NPClass){
        .name = "LibUI::Entry",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Entry),
        .vtable = &nupa_LibUI__Entry_vtable_inst,
        .class_vtable = &nupa_LibUI__Entry_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Group_class = (NPClass){
        .name = "LibUI::Group",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Group),
        .vtable = &nupa_LibUI__Group_vtable_inst,
        .class_vtable = &nupa_LibUI__Group_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Label_class = (NPClass){
        .name = "LibUI::Label",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Label),
        .vtable = &nupa_LibUI__Label_vtable_inst,
        .class_vtable = &nupa_LibUI__Label_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__MultilineEntry_class = (NPClass){
        .name = "LibUI::MultilineEntry",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__MultilineEntry),
        .vtable = &nupa_LibUI__MultilineEntry_vtable_inst,
        .class_vtable = &nupa_LibUI__MultilineEntry_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Separator_class = (NPClass){
        .name = "LibUI::Separator",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Separator),
        .vtable = &nupa_LibUI__Separator_vtable_inst,
        .class_vtable = &nupa_LibUI__Separator_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Tab_class = (NPClass){
        .name = "LibUI::Tab",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Tab),
        .vtable = &nupa_LibUI__Tab_vtable_inst,
        .class_vtable = &nupa_LibUI__Tab_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Window_class = (NPClass){
        .name = "LibUI::Window",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Window),
        .vtable = &nupa_LibUI__Window_vtable_inst,
        .class_vtable = &nupa_LibUI__Window_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Box_class = (NPClass){
        .name = "LibUI::Box",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Box),
        .vtable = &nupa_LibUI__Box_vtable_inst,
        .class_vtable = &nupa_LibUI__Box_meta_vtable_inst,
        .protocol_count = 0,
    };
    nupa_LibUI__Button_class = (NPClass){
        .name = "LibUI::Button",
        .superclass = &nupa_NPObject_class,
        .instance_size = sizeof(struct LibUI__Button),
        .vtable = &nupa_LibUI__Button_vtable_inst,
        .class_vtable = &nupa_LibUI__Button_meta_vtable_inst,
        .protocol_count = 0,
    };
}
__attribute__((weak)) NPObject * __nupa_root_init(NPObject * self, SEL _cmd) {
    return nupa_init(self);
}

__attribute__((weak)) void __nupa_root_dealloc(NPObject * self, SEL _cmd) {
    return;
}

__attribute__((weak)) void __nupa_root_release(NPObject * self, SEL _cmd) {
    nupa_release(self);
}

__attribute__((weak)) NPObject * __nupa_root_retain(NPObject * self, SEL _cmd) {
    return nupa_retain(self);
}

__attribute__((weak)) _Bool __nupa_root_isKindOf_(NPObject * self, SEL _cmd, NPClass * cls) {
    return nupa_isKindOf(self, cls);
}

__attribute__((weak)) NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nupa_alloc(self);
}

__attribute__((weak)) NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nupa_alloc(self);
    return nupa_init(obj);
}

__attribute__((weak)) NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    return nupa_init(self);
}

__attribute__((weak)) void NPObject_dealloc(NPObject * self, SEL _cmd) {
    return;
}

__attribute__((weak)) void NPObject_release(NPObject * self, SEL _cmd) {
    nupa_release(self);
}

__attribute__((weak)) NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
    return nupa_retain(self);
}

LibUI__Window * LibUI__Window_withTitle_width_height_(NPClass * self, SEL _cmd, const char * title, int w, int h);

void LibUI__Window_show(NPObject * self, SEL _cmd);

void LibUI__Window_activate(NPClass * self, SEL _cmd);

void LibUI__Window_onClosingQuit(NPObject * self, SEL _cmd);

void LibUI__Window_setChild_(NPObject * self, SEL _cmd, struct uiControl * child);

struct uiWindow * LibUI__Window_handle(NPObject * self, SEL _cmd);

LibUI__Box * LibUI__Box_vertical(NPClass * self, SEL _cmd);

LibUI__Box * LibUI__Box_horizontal(NPClass * self, SEL _cmd);

void LibUI__Box_append_stretch_(NPObject * self, SEL _cmd, struct uiControl * child, int stretch);

struct uiBox * LibUI__Box_handle(NPObject * self, SEL _cmd);

LibUI__Button * LibUI__Button_withText_(NPClass * self, SEL _cmd, const char * text);

void LibUI__Button_onClicked_data_(NPObject * self, SEL _cmd, void * cb, void * data);

struct uiButton * LibUI__Button_handle(NPObject * self, SEL _cmd);

LibUI__Label * LibUI__Label_withText_(NPClass * self, SEL _cmd, const char * text);

void LibUI__Label_setText_(NPObject * self, SEL _cmd, const char * text);

struct uiLabel * LibUI__Label_handle(NPObject * self, SEL _cmd);

LibUI__Entry * LibUI__Entry_create(NPClass * self, SEL _cmd);

const char * LibUI__Entry_text(NPObject * self, SEL _cmd);

void LibUI__Entry_setText_(NPObject * self, SEL _cmd, const char * text);

struct uiEntry * LibUI__Entry_handle(NPObject * self, SEL _cmd);

LibUI__MultilineEntry * LibUI__MultilineEntry_create(NPClass * self, SEL _cmd);

const char * LibUI__MultilineEntry_text(NPObject * self, SEL _cmd);

void LibUI__MultilineEntry_setText_(NPObject * self, SEL _cmd, const char * text);

struct uiMultilineEntry * LibUI__MultilineEntry_handle(NPObject * self, SEL _cmd);

LibUI__Separator * LibUI__Separator_horizontal(NPClass * self, SEL _cmd);

LibUI__Separator * LibUI__Separator_vertical(NPClass * self, SEL _cmd);

struct uiSeparator * LibUI__Separator_handle(NPObject * self, SEL _cmd);

LibUI__Group * LibUI__Group_withTitle_(NPClass * self, SEL _cmd, const char * title);

void LibUI__Group_setChild_(NPObject * self, SEL _cmd, struct uiControl * child);

struct uiGroup * LibUI__Group_handle(NPObject * self, SEL _cmd);

LibUI__Tab * LibUI__Tab_create(NPClass * self, SEL _cmd);

void LibUI__Tab_append_child_(NPObject * self, SEL _cmd, const char * name, struct uiControl * child);

struct uiTab * LibUI__Tab_handle(NPObject * self, SEL _cmd);

NPObject * nupa_alloc(struct NPClass * cls);

NPObject * nupa_init(NPObject * self);

void nupa_release(NPObject * obj);

NPObject * nupa_retain(NPObject * obj);

__attribute__((weak)) void onGreet(struct uiButton * b, void * data) {
    (void)b;
    struct uiEntry * e = (struct uiEntry *)data;
    char * name = (char *)(uiEntryText(e));
    printf("Hello, %s!\n", name);
}

__attribute__((weak)) void * counter_ctx_create(struct uiLabel * label) {
    struct CounterCtx * ctx = (struct CounterCtx *)malloc(sizeof(struct CounterCtx));
    ctx->value = 0;
    ctx->label = label;
    return ctx;
}

__attribute__((weak)) void onInc(struct uiButton * b, void * data) {
    (void)b;
    struct CounterCtx * ctx = (struct CounterCtx *)data;
    (ctx->value)++;
    char buf[64];
    snprintf(buf, sizeof(buf), "Counter: %d", ctx->value);
    uiLabelSetText(ctx->label, buf);
}

__attribute__((weak)) void onDec(struct uiButton * b, void * data) {
    (void)b;
    struct CounterCtx * ctx = (struct CounterCtx *)data;
    (ctx->value)--;
    char buf[64];
    snprintf(buf, sizeof(buf), "Counter: %d", ctx->value);
    uiLabelSetText(ctx->label, buf);
}

__attribute__((weak)) void onReset(struct uiButton * b, void * data) {
    (void)b;
    struct CounterCtx * ctx = (struct CounterCtx *)data;
    ctx->value = 0;
    char buf[64];
    snprintf(buf, sizeof(buf), "Counter: %d", ctx->value);
    uiLabelSetText(ctx->label, buf);
}

__attribute__((weak)) int main(void) {
    nupa_meta_init();
    {
        nupa_autoreleasepool_t * __nupa_pool = nupa_autoreleasepool_push();
        LibUI__Window * win = (LibUI__Window *)(LibUI__Window_withTitle_width_height_(&nupa_LibUI__Window_class, __nupa_sel_withTitle_width_height_, "Nupa + libui-ng", 600, 400));
        LibUI__Tab * tab = (LibUI__Tab *)(LibUI__Tab_create(&nupa_LibUI__Tab_class, __nupa_sel_create));
        LibUI__Box * ctrlBox = (LibUI__Box *)(LibUI__Box_vertical(&nupa_LibUI__Box_class, __nupa_sel_vertical));
        LibUI__Label * lbl = (LibUI__Label *)(LibUI__Label_withText_(&nupa_LibUI__Label_class, __nupa_sel_withText_, "Enter your name:"));
        ((struct nupa_vtable *)(ctrlBox->isa->vtable))->append_stretch_((NPObject *)(ctrlBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(lbl->isa->vtable))->handle((NPObject *)(lbl), __nupa_sel_handle)), 0);
        LibUI__Entry * entry = (LibUI__Entry *)(LibUI__Entry_create(&nupa_LibUI__Entry_class, __nupa_sel_create));
        ((struct nupa_vtable *)(ctrlBox->isa->vtable))->append_stretch_((NPObject *)(ctrlBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(entry->isa->vtable))->handle((NPObject *)(entry), __nupa_sel_handle)), 0);
        LibUI__Button * greetBtn = (LibUI__Button *)(LibUI__Button_withText_(&nupa_LibUI__Button_class, __nupa_sel_withText_, "Say Hello"));
        ((struct nupa_vtable *)(greetBtn->isa->vtable))->onClicked_data_((NPObject *)(greetBtn), __nupa_sel_onClicked_data_, (void *)(onGreet), (void *)(((struct nupa_vtable *)(entry->isa->vtable))->handle((NPObject *)(entry), __nupa_sel_handle)));
        ((struct nupa_vtable *)(ctrlBox->isa->vtable))->append_stretch_((NPObject *)(ctrlBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(greetBtn->isa->vtable))->handle((NPObject *)(greetBtn), __nupa_sel_handle)), 0);
        LibUI__Separator * sep = (LibUI__Separator *)(LibUI__Separator_horizontal(&nupa_LibUI__Separator_class, __nupa_sel_horizontal));
        ((struct nupa_vtable *)(ctrlBox->isa->vtable))->append_stretch_((NPObject *)(ctrlBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(sep->isa->vtable))->handle((NPObject *)(sep), __nupa_sel_handle)), 0);
        LibUI__Box * infoBox = (LibUI__Box *)(LibUI__Box_vertical(&nupa_LibUI__Box_class, __nupa_sel_vertical));
        LibUI__MultilineEntry * info = (LibUI__MultilineEntry *)(LibUI__MultilineEntry_create(&nupa_LibUI__MultilineEntry_class, __nupa_sel_create));
        ((struct nupa_vtable *)(info->isa->vtable))->setText_((NPObject *)(info), __nupa_sel_setText_, "Nupa + libui-ng Demo\nlibui-ng is a cross-platform GUI library.\nNupa wraps it with ObjC-style syntax.");
        ((struct nupa_vtable *)(infoBox->isa->vtable))->append_stretch_((NPObject *)(infoBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(info->isa->vtable))->handle((NPObject *)(info), __nupa_sel_handle)), 1);
        LibUI__Box * countBox = (LibUI__Box *)(LibUI__Box_vertical(&nupa_LibUI__Box_class, __nupa_sel_vertical));
        LibUI__Label * countLabel = (LibUI__Label *)(LibUI__Label_withText_(&nupa_LibUI__Label_class, __nupa_sel_withText_, "Counter: 0"));
        void * ctx = counter_ctx_create(((struct nupa_vtable *)(countLabel->isa->vtable))->handle((NPObject *)(countLabel), __nupa_sel_handle));
        ((struct nupa_vtable *)(countBox->isa->vtable))->append_stretch_((NPObject *)(countBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(countLabel->isa->vtable))->handle((NPObject *)(countLabel), __nupa_sel_handle)), 0);
        LibUI__Button * incBtn = (LibUI__Button *)(LibUI__Button_withText_(&nupa_LibUI__Button_class, __nupa_sel_withText_, "+1"));
        ((struct nupa_vtable *)(incBtn->isa->vtable))->onClicked_data_((NPObject *)(incBtn), __nupa_sel_onClicked_data_, (void *)(onInc), (void *)(ctx));
        ((struct nupa_vtable *)(countBox->isa->vtable))->append_stretch_((NPObject *)(countBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(incBtn->isa->vtable))->handle((NPObject *)(incBtn), __nupa_sel_handle)), 0);
        LibUI__Button * decBtn = (LibUI__Button *)(LibUI__Button_withText_(&nupa_LibUI__Button_class, __nupa_sel_withText_, "-1"));
        ((struct nupa_vtable *)(decBtn->isa->vtable))->onClicked_data_((NPObject *)(decBtn), __nupa_sel_onClicked_data_, (void *)(onDec), (void *)(ctx));
        ((struct nupa_vtable *)(countBox->isa->vtable))->append_stretch_((NPObject *)(countBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(decBtn->isa->vtable))->handle((NPObject *)(decBtn), __nupa_sel_handle)), 0);
        LibUI__Button * resetBtn = (LibUI__Button *)(LibUI__Button_withText_(&nupa_LibUI__Button_class, __nupa_sel_withText_, "Reset"));
        ((struct nupa_vtable *)(resetBtn->isa->vtable))->onClicked_data_((NPObject *)(resetBtn), __nupa_sel_onClicked_data_, (void *)(onReset), (void *)(ctx));
        ((struct nupa_vtable *)(countBox->isa->vtable))->append_stretch_((NPObject *)(countBox), __nupa_sel_append_stretch_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(resetBtn->isa->vtable))->handle((NPObject *)(resetBtn), __nupa_sel_handle)), 0);
        ((struct nupa_vtable *)(tab->isa->vtable))->append_child_((NPObject *)(tab), __nupa_sel_append_child_, "Controls", (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(ctrlBox->isa->vtable))->handle((NPObject *)(ctrlBox), __nupa_sel_handle)));
        ((struct nupa_vtable *)(tab->isa->vtable))->append_child_((NPObject *)(tab), __nupa_sel_append_child_, "Info", (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(infoBox->isa->vtable))->handle((NPObject *)(infoBox), __nupa_sel_handle)));
        ((struct nupa_vtable *)(tab->isa->vtable))->append_child_((NPObject *)(tab), __nupa_sel_append_child_, "Counter", (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(countBox->isa->vtable))->handle((NPObject *)(countBox), __nupa_sel_handle)));
        ((struct nupa_vtable *)(win->isa->vtable))->setChild_((NPObject *)(win), __nupa_sel_setChild_, (struct uiControl *)((struct uiControl *)((struct nupa_vtable *)(tab->isa->vtable))->handle((NPObject *)(tab), __nupa_sel_handle)));
        ((struct nupa_vtable *)(win->isa->vtable))->onClosingQuit((NPObject *)(win), __nupa_sel_onClosingQuit);
        ((struct nupa_vtable *)(win->isa->vtable))->show((NPObject *)(win), __nupa_sel_show);
        LibUI__Window_activate(&nupa_LibUI__Window_class, __nupa_sel_activate);
        uiMain();
        printf("Done.\n");
        nupa_release(resetBtn);
        nupa_release(decBtn);
        nupa_release(incBtn);
        nupa_release(countLabel);
        nupa_release(countBox);
        nupa_release(info);
        nupa_release(infoBox);
        nupa_release(sep);
        nupa_release(greetBtn);
        nupa_release(entry);
        nupa_release(lbl);
        nupa_release(ctrlBox);
        nupa_release(tab);
        nupa_release(win);
        nupa_autoreleasepool_pop(__nupa_pool);
    }
    return 0;
}

